### ISSUE TITLE
history.push(?module=moduleName) on file navigation

### ISSUE THREAD

**Issue by faceyspacey** [codesandbox/codesandbox-client#110]
As requested, here's the issue to further discuss this. I'd be happy to do this one with a little direction. 

I've done a little test in chrome where I entered the following in the console:

```js
history.pushState({}, '', window.location.pathname + '?module=foo')
```

It worked fine and did not break the iframe in any way. Perhaps the issue you ran into was the result of changing the path...did that too:

```js
history.pushState({}, '', window.location.pathname + '/foo')
```

No issues, the iframe continued to behave fine, even when navigating. 

Either way, let me know what files to touch to make this happen and what code bits to look out for.

**Comment by CompuIves** [comment]
Thanks for opening this issue!

I have a way to reproduce the problem:

1. Open https://codesandbox.io/s/github/faceyspacey/redux-first-router-codesandbox
2. Go to a route in the sandbox
3. run `history.pushState({}, '', window.location.pathname + '?module=foo')` in console
4. Press the back button of the sandbox

In my case the back button doesn't work anymore, since the `back()` of history is called on `?module=foo`. A solution would be to make the back button of the sandbox preview just go to the previous url in the list of urls we keep track of, but then we don't have a native back button anymore for the preview. I'm not sure if that's desirable.

**Comment by faceyspacey** [comment]
if thats all we can do, its all we can do. the most important thing is URLs u can deep link to that u can copy paste from the native place they live, the address bar.

**Comment by CompuIves** [comment]
Agreed, let's keep the current functionality for now.

**Comment by faceyspacey** [comment]
What I was saying is we build it just without back functionality. So as u navigate the module Id is in the URL. That's the important part. It's not only useful but gives visibility to this feature to people who otherwise might not know.

**Comment by CompuIves** [comment]
Hmm, I do not completely understand what you mean. I think there is a solution though, we could use `history.replaceState` instead of `pushState`, this way we don't pollute the history and are still able to change the URL.

**Comment by TrevorSayre** [comment]
Perhaps this should include updating `moduleview=1` on view toggle as mentioned in #188

**Comment by lbogdan** [comment]
With the new [sandbox history](https://github.com/CompuIves/codesandbox-client/pull/198) this should be doable.

**Comment by lbogdan** [comment]
Are we still pursuing this?
