### ISSUE TITLE
DevTools failed to parse SourceMap

### ISSUE THREAD

**Issue by vegarringdal** [codesandbox/codesandbox-client#1196]
# 🐛 bug report

## Description of the problem

I get a lot of warnings in dev console in chrome about sourcemaps.

What I see with sourcemaps
![image](https://user-images.githubusercontent.com/2901416/47024662-6ff30d80-d162-11e8-9200-202e1e1480a7.png)

Also if I use `import()` with html it breaks it. 
See `loadTemplate()` function in index.html.

## How has this issue affected you? What are you trying to accomplish?

Not working as expected.
I do not get any of these issues when download it and test it locally

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1539599104-8713bb1 -parcel template ?
| Browser | Chrome 69
| Operating System | Window 64

**Comment by vegarringdal** [comment]
I tried to use the react-ts with my hobby framework, I also get sourcemap warnings here.
But `import()` works, so that issue is related to just parcel template
https://codesandbox.io/s/28ww10j0r

Looking at default angular template I can see the sourcemaps warnings here too.
https://codesandbox.io/s/angular?from-embed

**Off topic:**
@CompuIves
Would have been nice if we had a clean typescript like react ts one that just looked for typescript dependency instead of react-ts.
Having simple extension like ES6 string html highlight would ahve been nice too
Like this one: https://github.com/mydesireiscoma/es6-string-html
I can create own issues on this if its something u would consider/want.

**Comment by lbogdan** [comment]
Hey @vegarringdal ,

Regarding the source map warnings, those are generated by the browser, and I'm not aware of any way to stop them, application-wise. A workaround would be to configure the console to not show the warnings, but this has the side-effect of maybe missing some relevant ones.

Also, TIL: You can also [disable source maps](https://stackoverflow.com/a/35004929), which will stop showing those annoying warnings.

Other than that, I see the initial sandbox is working now (although the one in your follow-up comment isn't anymore). Can you please give us an update on that, as there were lots of changes since you opened this?

**Comment by SaraVieira** [comment]
Closed for lack of activity
