### ISSUE TITLE
Add dependencies automatically

### ISSUE THREAD

**Issue by gkiely** [codesandbox/codesandbox-client#1227]
# 🌈 Feature

**Use case:**
User copies code into codesandbox, but they have to install dependencies to get it to work. Would be great if it just did this automatically for you.

**Current behavior:**
You have to install dependencies with the add dependency button.

**Awesome behavior:**
Codesandbox detects import and installs it automatically for you

**Some kind of regex that looks for the dependencies and installs them.**
import Modal from "@material-ui/core/Modal";
import autoBind from "react-autobind";

**Comment by lbogdan** [comment]
Currently when you're trying to import / require a module that's not in dependencies, you'll get message prompting you to add it:

![image](https://user-images.githubusercontent.com/2083930/55037712-4ef2ea80-5027-11e9-8d1b-7b4910dc5d6d.png)

As this was there since before you opened this, I'm guessing this doesn't suit your needs?

**Comment by gkiely** [comment]
Nice fix, yep this solves it 👍
