### ISSUE TITLE
How to make a sandbox from scratch?

### ISSUE THREAD

**Issue by trusktr** [codesandbox/codesandbox-client#1236]
# ❔ Question

I don't find any docs on how to make a sandbox from scratch in my own empty repo. F.e., What are the requirements? Do I just need to have a `start` script in `package.json`? What are the requirements to get something running in the sandbox browser? Does a server need to run on a specific port?

It'd be great to know exactly what is required.

**Comment by trusktr** [comment]
Do we have to have `src/index.html`? Is that how the web app gets loaded?

**Comment by trusktr** [comment]
Here's the sandbox I'm trying to make work: https://codesandbox.io/s/ly6jp49z7

**Comment by lbogdan** [comment]
Hey @trusktr !

First of all, do you want a client sandbox (that runs completely in the browser), or a [server / container sandbox](https://hackernoon.com/codesandbox-containers-5864a8f26715)?

**Comment by trusktr** [comment]
Good question. I just wanted to make a custom Webpack config, and have it display content in the sandbox browser, but I don't need it to hit any APIs. So I think just client sandbox?

**Comment by lbogdan** [comment]
If you want webpack, you'll probably need a server one. The browser bundler is "webpack like", but it doesn't support actual webpack config, loaders etc.

**Comment by trusktr** [comment]
oh okay. How would one do that?

I mean, I'm am familiar with Webpack, I've made plenty of Webpack projects. But how to we make one for codesandbox?

**Comment by trusktr** [comment]
ping. This would be great to know. Then we can figure how to take any template and use it on codesandbox.

**Comment by CompuIves** [comment]
Hey! Sorry for the silence on this issue!

For CodeSandbox we have two kind of templates: client and server templates. Client templates fully execute in the browser with a custom bundler that works in the browser. The bundler is not Webpack, so custom Webpack configurations don't work for those scenarios.

Partly because custom Webpack doesn't work for client sandboxes, we started to develop a way to execute on the code on a server. We call those server sandboxes/container sandboxes. When running these kinds of sandboxes you can run any code that works locally.

Here's a container sandbox that you can get started with: https://codesandbox.io/s/node.
