### ISSUE TITLE
Feature idea: view a diff comparing saved sandbox to whichever sandbox the user started from

### ISSUE THREAD

**Issue by kylegach** [codesandbox/codesandbox-client#133]
This could be useful to illustrate how to properly use a package, for instance. It would allow the viewer to separate the relevant bits from the boilerplate.

**Comment by CompuIves** [comment]
This is a nice idea, especially since both CodeMirror and Monaco already support diff views. I'm thinking of adding a snapshot feature that lets you save different 'snapshots' or 'versions' of a sandbox and a diff view between them would be very beneficial.

A snapshot system would also be very nice for creating tutorials with different steps, or even as a _basic_ version control.

**Comment by lbogdan** [comment]
> A snapshot system would also be very nice for creating tutorials
^ this! :heart:

**Comment by noobling** [comment]
Could this possibly be extended to code diffs for git commits?

**Comment by Saeris** [comment]
Added this to our public backlog as two separate items. Closing this thread for now. Please refer to the links below for status updates for each:

https://www.notion.so/Add-Diff-View-5a5530bf1e244aada03eea43997d22a7
https://www.notion.so/Add-Sandbox-Snapshots-243352d1f71842edb219178e740db789
