### ISSUE TITLE
Switching to another branch

### ISSUE THREAD

**Issue by zixuan75** [codesandbox/codesandbox-client#1347]
# 🌈 Feature

For now, we only could commit and send PR, but can we switch to another branch? 
Feature name: Switch to another branch

If you click on a button, that will show you all the branches of the repository. Then navigate and click on the branch you want to switch to.

For example, there could be a "Switch branches" button. Now, I'm in the csb-1543761723396 branch, and I want to switch to the master branch. So I click the "Switch branches" button and then I navigate to the master branch. Then I click on "master", then it should be switched to the master branch.

**Comment by CompuIves** [comment]
This is a good feature request, we should query all git sandboxes created from the sandbox and show those in the sidebar.

This can be part of the feature where we show your GitHub sandboxes in the dashboard.

**Comment by zixuan75** [comment]
:rainbow:

**Comment by timoa** [comment]
Hi! Awesome work, guys!

I started few days ago to play with CodeSandbox for my open-source projects but I got stuck on temporary branch (due to the use of npm instead of yarn => `package-lock.json`).

I can't find how to switch to return to `master` instead of `csb-xxxxxx` that is closed.

![Screenshot 2019-05-17 at 08 09 17](https://user-images.githubusercontent.com/1432989/57909610-2810a200-787b-11e9-84c2-109a953474fe.png)

Only workaround for now is to delete the sandbox and create a new one from `master` again.

Any advise or plan to implement a way to switch to other branches from the UI?

I will have a look in the code but wanted to avoid to start something that is already in progress :)

Thanks!

**Comment by zixuan75** [comment]
@timoa That's exactly what I wanted!

**Comment by Shriram-Balaji** [comment]
@CompuIves Would it be possible to use the container sandbox terminal to switch branches like `git checkout <branch>` instead, and trigger a sandbox restart instead? Currently the `/sandbox` directory doesn't have a valid `.git` sub-directory to perform git operations, but I'm not sure if that's feasible with the `git-extractor` as Ive not looked into it.

**Comment by opensas** [comment]
Is there some way to switch branches right now in codesandbox? it's pretty hard to work with git wthout this feature. At least some command line workaround?

**Comment by CodeSandboxNotifications** [comment]
Hello there!


Currently Codesandbox does not have Git support, it uses the Github API with its benefits and limitations. We are currently working on improving the flow of this Github integration as a first step. We have proper Git support on the roadmap, but it requires bigger changes in our infrastructure. 


The closest thing you get to a workaround now is that you insert your Github url on Codesandbox. This will create a synced sandbox which you can fork and make changes to. For example:


https://codesandbox.io/s/github/some-username/some-repo/tree/some-branch


The good thing though is that the sandbox created when inserting this url will always be up to date 


I hope this was helpful and please let me know if you have any more question related to this.




Best regards
Christian



--- original message ---
On June 13, 2020, 10:16 PM GMT+2 notifications@github.com wrote:



Is there some way to switch branches right now in codesandbox? it's pretty hard to work with git wthout this feature. At least some command line workaround?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by umeshjain1999** [comment]
I think for now what we can do is export the CodeSandbox file then cloning the required GitHub project in your local device. Copy all the files from CodeSandbox one to GitHub one push the changes in any branch of GitHub using git.
Thank you ✌

**Comment by zixuan75** [comment]
So you mean we can't use this feature?

**Comment by SaraVieira** [comment]
Hey!

There is no feature that allows this for now but proper support for git is already on our backlog and its gonna get started being worked in beginning next year and that will include changing branches and basically it will be full git but it's not an easy project. 

The only thing that can be done is what Christian said and re copy the link, sorry for the issue


Will close this as it is already in our backlog and will work on making our internal backlog public

Thank you!

**Comment by vikrantsingh47** [comment]
can we switch to another branch now in codesandbox?

**Comment by SaraVieira** [comment]
I don't think so, let me ping @christianalfoni as i don't work here anymore

**Comment by wojm** [comment]
@SaraVieira  @christianalfoni any update on this? Working on a curriculum that requires users to switch branches. Thanks!!

**Comment by gbraad** [comment]
I populate 'forks' of projects I work on for my employer with a new default branch called 'fork' to indicate this is NOT to be used. This means that each GItHub project checkout I do using codesandbox is unusable. Is there a way to track the what the progress is from a backlog related to the more generic git support?

**Comment by AnthumChris** [comment]
Is it possible to re-open this? I'm also trying to import a Git repo and specify the branch.

**Comment by Verminous** [comment]
Please implement this feature....

**Comment by tristandubbeld** [comment]
Hey @AnthumChris and @Verminous, switching branches is now possible in the new editor after importing your repository into CodeSandbox. Let me know if you have more questions about this!
