### ISSUE TITLE
Cleanup function from testing framework doesn't work in codesandbox.

### ISSUE THREAD

**Issue by dhuber666** [codesandbox/codesandbox-client#1525]
# 🐛 bug report

## Description of the problem
If you have tests in your project and you want to cleanup after each test it won't cleanup. 
I think that's because the tests run in the browser and not in jsdom. In my example the `cleanup` function from `react-testing-library`

## How has this issue affected you? What are you trying to accomplish?
The problem is the tests getting useless for me because it won't clean up and therefore it has several "input" or other tags and I can't relyable find the correct element. Because the same element exists several times when you have more tests. Look at the codesandbox where you can see the problem. 
This same test will work on local machine and won't fail. 
Corresponding files: `TodoHeader.js` and `TodoHeader.test.js`
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Chrome |  72| 
| Windows |10|

**Comment by ardeaf** [comment]
The real problem is the Sandbox's entrypoint renders one DOM and react-testing-library doesn't get rendered in it's own DOM, I think.

the `cleanup` function works. Try removing it from your sandbox, and when your tests run you'll see your tests continue to render new elements in the DOM.

The reason your test is failing `index.js` is still rendered when Jest runs react-testing-library tests which just seem to add to the existing DOM rendered by `index.js`. So, when you try to add change the value of the input, you are finding the wrong input, and you're not even doing anything to the new `inputs` rendered by `react-testing-library`. 

Also, the mock function isn't getting run because it's part of the new form rendered by `react-testing-library` which isn't even being touched. 

In any case, to get your test to pass with react-testing-library I had to just comment out `ReactDOM.render(...)` from `index.js`

**Comment by lbogdan** [comment]
Hey @dhuber666 ,

Did @ardeaf 's comment solve the issue for you? If so, can you please close this? Thanks!

And thanks @ardeaf for your comprehensive comment! 🙂

**Comment by robertcoopercode** [comment]
I run into the same issue as @dhuber666, but I'm able to get the cleanup to work as expected when I comment out the `render(...)` of my React app in the entry point of my app (as suggested by @ardeaf). Here's a sandbox that demonstrates the issue: https://codesandbox.io/s/l242wzo837

Ideally, we don't have to comment out the render method each time we want the cleanup to work as expected.

Thanks @ardeaf for insights into this 👍

**Comment by CompuIves** [comment]
Hmm yes this definitely is an issue in CodeSandbox. I've been meaning to fix this for a while by running the tests on something like `jsdom` instead, I'll see what I can do!

**Comment by berlirumapea** [comment]
I run the same issue with cleanup, tried the suggestion by @ardeaf and it works. But my fireEvent doesn't work. Link to the code: https://codesandbox.io/s/mqm2w49y1x
