### ISSUE TITLE
Git SubModules

### ISSUE THREAD

**Issue by Weedshaker** [codesandbox/codesandbox-client#1568]
Git Submodules don't get pulled in.

I have a website on github and wanted to edit it in CodeSandbox -> https://codesandbox.io/s/github/Shoga9Team/website
Sadly, it doesn't init/load the submodules within my repo. And even worse, it does delete submodules on commits from within sandbox.

Is it possible to support submodules, its more like a feature request but then still a bug, since codesandbox does scramble up repos with submodules.

Thank you and else, I LOVE your project!

**Comment by Weedshaker** [comment]
@CompuIves , sorry to misuse this issue, but I also wanted to tell you, that I found the JS Party with you fantastic. Just pure genius!

**Comment by Weedshaker** [comment]
Really?

**Comment by KBeDevel** [comment]
Having the same problem.

IDK if this feature was ignored due to priorities or is just missing. Submodules should be expected for **any** git repository, since is a feature officially supported and documented by git.

I'm not even sure if we can contribute to this. Please, is there any maintainer to provide some guidelines?
