### ISSUE TITLE
Better Vue Sandbox starter

### ISSUE THREAD

**Issue by davestewart** [codesandbox/codesandbox-client#1610]
Not sure if this relates to other frameworks as well, but the view starter is not a particularly-development friendly starter.

I get that it demos a few key features, but there's a lot of deleting before something can be built.

It would be nicer if:

- the component was called Example not HelloWorld
- all content was in the Example
- everything was in the root folder
- remove all the links and tags
- there were no props passed in
- the styling was not centered
- there wasn't an image

That way we could just start writing code.

Thanks!

**Comment by lbogdan** [comment]
Hey @davestewart ,

While you have a point, we chose this starter specifically because that's what `vue-cli` (and, more recently, `@vue/cli`) generates. Also, it's very hard to have one that satisfies everybody's needs.

A workaround (and at least what I do) to this is to define your own "starter template" (mine is https://codesandbox.io/s/n0y593z354 ), and fork that every time you want to *just start writing code*. Pro tip: you can also mark it as "Frozen", so that you don't edit it, save and accidentally change it.

**Comment by davestewart** [comment]
> because that's what vue-cli (and, more recently, @vue/cli) generates

I guess it's good to have a baseline

> mine is https://codesandbox.io/s/n0y593z354 

I like it! Prepare to be forked 😜

**Comment by SaraVieira** [comment]
Closed as try to keep it aligned with the vue-cli and you can now create templates and re use them :)
