### ISSUE TITLE
Dependency on branch of git repo not working

### ISSUE THREAD

**Issue by masaeedu** [codesandbox/codesandbox-client#1642]
# 🐛 bug report

## Description of the problem

Hi there. It seems I can't take a dependency on a git repo containing an npm package. Here's what I have in package.json (most of this is just the `node` template):

```
{
  "name": "node-sandbox",
  "version": "1.0.0",
  "description": "Simple Node Sandbox",
  "main": "src/index.js",
  "scripts": {
    "start": "nodemon src/index.js localhost 8080"
  },
  "dependencies": {
    "@masaeedu/fp": "https://github.com/masaeedu/fp.git#dev"
  },
  "devDependencies": {
    "nodemon": "1.18.4"
  }
}
```

When I try to import the module using:

```
const { Fn } = require("@masaeedu/fp");
```

I get

```
Error: Cannot find module '@masaeedu/fp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/sandbox/src/index.js:1:78)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

## How has this issue affected you? What are you trying to accomplish?

I'm trying to discuss some code changes with a friend without having merged them (and therefore created an npm package they can use to play around with them). I was hoping codesandbox would help me do this.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | <whatever current is, I'm not sure how to look this up>
| Browser | Firefox 65.0.2
| Operating System | Linux

**Comment by lbogdan** [comment]
Hey @masaeedu ,

If you'll take a look in `node_modules` you'll see the files are there, the issue is that you don't have a root `index.js`, and your `package.json` points `main` to `dist/index.js`, which doesn't exist, either.

**Comment by masaeedu** [comment]
@lbogdan The module actually has a `prepare` script that builds it after it's installed as a dependency (using its own devdependencies). If you run the following in an empty directory you'll see that using it with yarn on a local system works ok:

```
yarn init -y
yarn add https://github.com/masaeedu/fp#dev
echo 'const { Fn } = require("@masaeedu/fp"); console.log(Fn.id(42))' >> ./index.js
node index.js
```

**Comment by lbogdan** [comment]
Hey @masaeedu ,

Do you remember how you got to this state? Did you first install the "regular" `@masaeedu/fp`, and then tried with the git link?

What I did to make it work:
- forked your sandbox (because we're caching `node_modules` and `yarn.lock`, the fork was using the same `node_modules` files as your sandbox, so it still didn't work)
- removed `@masaeedu/fp` from `package.json`'s `dependencies` (actually I removed the whole `dependencies` section), saved, you should see `yarn` running in the terminal output
- re-added `@masaeedu/fp`, saved - here it looks like we have a small bug, sometimes it doesn't re-run `yarn` when you save `package.json`, if that's the case, try to add / remove some white-space - in the terminal output I could see `yarn` building your module:

![image](https://user-images.githubusercontent.com/2083930/55572712-e2f04080-5710-11e9-8211-3e9e253f76c3.png)

- restarted the sandbox, everything works just fine.

Here's my fork: https://codesandbox.io/s/482xjz129 .

Please try the above and let me know if it worked.

**Comment by masaeedu** [comment]
Hi @lbogdan. Yup, creating a brand new vanilla sandbox and following your steps worked! Unfortunately I don't remember what I was doing exactly that caused the sandbox to get into a bad state, maybe I was using it wrong.

**Comment by masaeedu** [comment]
I'm working on a new codesandbox here and that seems to be in a weird state as well, although possibly this is unrelated: https://codesandbox.io/s/2vn5360z0

**Comment by lbogdan** [comment]
Hey @masaeedu ,

Since our last talk, we fixed the issue with `yarn` sometimes not running when changing `package.json`.

In your last comment you linked to a client sandbox, which behaves differently than a server one (like the one in the OP), and runs completely in-browser, instead of in a container. Is that what you intended?

**Comment by masaeedu** [comment]
Hi @lbogdan. Unfortunately I don't really remember anything about this issue, so I don't think I can provide any useful information for debugging purposes. If I run into similar problems in the future I'll try to capture more details and just open a separate issue.
