### ISSUE TITLE
CodeSandbox freezes when using `toMatchObject` in tests

### ISSUE THREAD

**Issue by CompuIves** [codesandbox/codesandbox-client#1710]
# 🐛 bug report

This one is an important one, we should fix it ASAP.

Reference tweet: https://twitter.com/IMatt611/status/1113494800441827328

## Description of the problem
Change `toMatchInlineSnapshot` to `toMatchObject`, the whole editor freezes.

## How has this issue affected you? What are you trying to accomplish?
Freezes editor.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | 
| Operating System |

**Comment by imatt611** [comment]
Thanks so much for looking into this! If it helps, once I reached the point I left this at, any method change there was triggering the freeze, but I was trying to work on it there because of the failing test. `toMatchInlineSnapshot` is a `jest` method, so that's confusing, too, but perhaps distinct.

I tested on Chrome 73.0 and Safari 12.1.

**Comment by batiskafff** [comment]
I can't reproduce it. Is it still an issue?

**Comment by imatt611** [comment]
I can't reproduce it anymore either, so I suppose not!
