### ISSUE TITLE
Can't read file contents with 'fs'

### ISSUE THREAD

**Issue by ygorbunkov** [codesandbox/codesandbox-client#1801]
# 🐛 bug report

## Description of the problem
Simple code
```
const fs = require("fs");
const html = fs.readFileSync("./frame.html", "utf-8");
console.log("html");
```
Throws an error
> Error: ENOENT: no such file or directory, open './frame.html'
While 'frame.html exists in the same directory as 'index.js'

## How has this issue affected you? What are you trying to accomplish?
Can't read other files, can't build up modular app structure.
### Your Environment
Windows 10 Enterprise; Mozilla Firefox 66.0.2 (64-bit)

**Comment by lbogdan** [comment]
Hey @ygorbunkov ,

As specified in the [Node.js documentation](https://nodejs.org/api/fs.html#fs_file_paths), file paths are relative to `process.cwd()` - the folder in which the app was started - which in a server sandbox is `/`, so `fs.readFileSync('./frame.html', ...)` tries to read `/frame.html`, but your file is actually under `/src/frame.html`.

You should either do `fs.readFileSync('src/frame.html', ...)`, or import `path` and use `fs.readFileSync(path.join(__dirname, 'frame.html'), ...)`.

Closing this, as it's expected behavior.
