### ISSUE TITLE
import-all.macro does not work in the react template

### ISSUE THREAD

**Issue by kentcdodds** [codesandbox/codesandbox-client#1862]
# 🐛 bug report

## Description of the problem

I believe that the react template is attempting to follow create-react-app which supports babel-plugin-macros out of the box. However, when I try to use `import-all.macro` I get an error:

> The macro imported from "import-all.macro" must be wrapped in "createMacro" which you can get from "babel-plugin-macros". Please refer to the documentation to see how to do this properly: https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/author.md#writing-a-macro

Or if I refresh the integrated browser, the error changes to:

> Error: ENOENT: No such file or directory., '/events'

## How has this issue affected you? What are you trying to accomplish?

I'd like to use the `import-all.macro` package for some of my workshops.

###  Link to sandbox: [link](https://codesandbox.io/s/lxlkxynrq9)

I get a similar issue using `preval.macro`: https://codesandbox.io/s/8kxlpnymvl

**Comment by CompuIves** [comment]
Hmm yes this one is a bit harder to fix. The `preval.macro` works by installing the preval macro (I should fix the dependency not found not showing issue), but the `import-all.macro` is harder to make work in the browser because I haven't been able to run `glob` yet in the browser. `glob` uses a lot of native node APIs. A way to fix it right now is to convert the sandbox to a container, so that it runs in the browser, but that's not the perfect solution. Let's keep it open, I can look into `glob`.

**Comment by sag1v** [comment]
@CompuIves is this relevant to [raw.macro](https://www.npmjs.com/package/raw.macro) as well? because its not working
> /src/App.js: raw.macro: Error: ENOENT: No such file or directory...

**Comment by kentcdodds** [comment]
Bump
