### ISSUE TITLE
🐛 TypeError Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by liub1934** [codesandbox/codesandbox-client#1912]
# 🐛 bug report

## Description of the problem

TypeError
Cannot read property 'toString' of undefined
![image](https://user-images.githubusercontent.com/29849550/57751697-2333dd00-7719-11e9-97fa-ff2f0cee18f7.png)
![image](https://user-images.githubusercontent.com/29849550/57751899-bff67a80-7719-11e9-9cfc-165ea77d66e2.png)

### Link to sandbox: 
[https://codesandbox.io/s/p52pl7vpoq](https://codesandbox.io/s/p52pl7vpoq)
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | new
| Browser          | Chrome 74.0.3729.131
| Operating System | win 10

**Comment by lbogdan** [comment]
Hey @liub1934 ,

It seems to be because of the empty `<style></style>` section, if you remove that the error goes away.

**Comment by liub1934** [comment]
> Hey @liub1934 ,
> 
> It seems to be because of the empty `<style></style>` section in `nav-menu.vue`, if you remove that the error goes away.

I removed the empty <style></style>,and has other problem
I used async component in `/components/nav-menu`
![image](https://user-images.githubusercontent.com/29849550/57752833-013c5980-771d-11e9-9eda-62c2eaf3a3d1.png)

**Comment by liub1934** [comment]
Maybe this problem is caused by https://vuejs.org/v2/guide/components-edge-cases.html#Circular-References-Between-Components

**Comment by lbogdan** [comment]
Does it work locally?

**Comment by liub1934** [comment]
> it work locally

It works  locally,I used width vue-cli-3

**Comment by coldbrewstudios** [comment]
for me it was adding `lang='scss'` to the `<style>` tag. It looks like "sass" is supported but "scss" is bugging out. Also I think the empty style tag as mentioned above will cause the issue too.

**Comment by c17r** [comment]
Seems if `<style>` is empty AND has `lang="scss"` is when it breaks. Remove either one of those conditions and everything works.

**Comment by alvarosaburido** [comment]
True story, cannot have the style tag importing a separate `.scss` file like this:

**Comment by c17r** [comment]
Just checked, still happening

**Comment by lbogdan** [comment]
Hey @c17r ,

What exactly is still happening, and can you please share a sandbox URL? Asking as there were more stated issues in the thread.

**Comment by c17r** [comment]
https://codesandbox.io/s/cool-river-lso2p?file=/src/App.vue

1. Create a VueJS sandbox
2. Click on App.vue
3. Empty the style tag
4. Set style tag to be `lang="scss"`

The compilation blows up with TypeError Cannot read property 'toString' of undefined.

This doesn't happen in a local setup, only on codesandbox (haven't tried it on Repl.it, stackblitz, etc to see if they have the same issue)

**Comment by lbogdan** [comment]
I see. While this indeed sounds like a bug, I'm not sure why would you want to have an empty `<style>` section in the first place, so I'd classify this as very low priority.

**Comment by c17r** [comment]
I'm not sure about others on this thread but I ran into it on code sandbox when I was testing something and when creating a Single File Component from scratch and utilizing the typeahead you quickly end up with:

```
<template>
</template>

<script>
export default {
  
}
</script>

<style lang="scss">
</style>
```

and since I was building a proof of concept for someone else, I didn't bother with the style tag and just built the HTML and JS that I needed to show the issue. And then spent quite a bit of time trying to figure out what the hell I was doing wrong.

Also, if you do `<style lang="scss"></style>` and get that error you're in for some fun figuring it out because changing it to `<style></style>` still breaks and removing the style block altogether still breaks. To get back to working, you have to put a non-empty style block with at least one non-empty rule to get it to compile and only then can you go back to either the empty style block without the lang attribute or removing the style block altogether.

I'd recommend at least putting a comment in the auto-generated style block or a linter rule or something to try to keep others out of the tar pit. It's a little bit Insider Baseball because, like I mentioned, having `<style lang="scss"></style>` works fine locally.

**Comment by CompuIves** [comment]
It's a good case, can be very confusing. I can take a second look at this!

**Comment by SaraVieira** [comment]
Hey

This seems to have been fixed in the meantime when @CompuIves did a lot of vue fixes

Cannot reproduce anymore.

Example sandbox: https://codesandbox.io/s/epic-cdn-v8b9m

**Comment by c17r** [comment]
I repo steps I mentioned back in https://github.com/codesandbox/codesandbox-client/issues/1912#issuecomment-687182690 does seem to be fixed now, excellent!

**Comment by SaraVieira** [comment]
Awesome! Have a great week 😀
