### ISSUE TITLE
Environment Variables for GitHub imported Repo

### ISSUE THREAD

**Issue by katiawheeler** [codesandbox/codesandbox-client#1920]
I have recently imported a GitHub repo to a CodeSandbox. The GitHub repo requires some environment variables for API keys. Maybe I completely missed it, but I am unable to add Secrets to the imported GitHub CodeSandbox. Is there a way to add environment variables to a sandbox that's from a GitHub repo?

Thanks for the help!

**Comment by lbogdan** [comment]
Hey @katiawheeler 

You're right that at the moment you can't add secrets to a github imported sandbox, because you don't actually own that sandbox. We're still to figure out how to let owners of the github repo also manage the imported sandboxes - it should be some sort of read-only management, though, as if you'd be able to change files' contents, the sandbox would diverge from the repo, which goes against the purpose of github imported sandboxes.

**Comment by katiawheeler** [comment]
Ahh, bummer! Yeah, I could definitely see a need for being able to manage those environment variables within a GitHub repo sandbox. I was hoping to be able to showcase some of my work from GitHub but don't necessarily want to expose those API keys that are managed within a .env file.

Thanks for the info!

**Comment by lbogdan** [comment]
If the repo doesn't frequently change, you can fork it and add the secrets to the fork, although you'll have to do that every time you push new commits. 😐

**Comment by katiawheeler** [comment]
Awesome, that will work for me! Thanks! 😄
