### ISSUE TITLE
Possible to configure ESLint?

### ISSUE THREAD

**Issue by rdmurphy** [codesandbox/codesandbox-client#1933]
# ❔ Question

Is it currently possible to configure ESLint at all? I can see that it's running, but its options don't appear in the VSCode preferences. I'm trying to find a way to change how it treats React pragma (so it doesn't consider preact's `h` to be "unused") but so far I've had no luck! I've tried to add my own `.eslintrc.json` but it didn't seem to take.

**Comment by agubler** [comment]
@CompuIves I have the same question, I am getting eslint errors in Dojo sandboxes for valid syntax.

**Link to sandbox: [link](https://codesandbox.io/s/dojocodesandboxtemplate-cusdj)**

**Comment by CompuIves** [comment]
Yep! We definitely want to support it, I was playing a bit with making that work before. I thought the "easiest" way would be to start supporting the `eslint` extension of VSCode, which handles the configuration resolving automatically. The challenge right now is that we need to install all custom eslint plugins that are defined in package.json, that's the last thing needed to make it work methinks.

**Comment by CompuIves** [comment]
I think your issue @agubler will be fixed with this! #1991

**Comment by agubler** [comment]
Awesome thanks @CompuIves 🎉

**Comment by jsejcksn** [comment]
Is this on a roadmap? Is there a CodeSandbox roadmap somewhere?

**Comment by rob2d** [comment]
@jsejcksn seems like #1991 was merged in but just needs explicit configuration added to CodeSandbox -- unless I'm missing something. Would also love to see this as needing === is not preferred for some people's preferences.

**Comment by dougllima** [comment]
Any news about this? How to configure this or anything like that.

**Comment by ecraig12345** [comment]
Any progress here @CompuIves? I'm getting false positives with eslint `no-undef` in my sandbox due to the lack of eslint/TS integration. The ability to have a custom eslint config or even disable eslint entirely would also be acceptable workarounds. (I'd rather not disable it manually in every file.)

**Comment by NickCarducci** [comment]
idk how eslint works but you could reserve something like {/% to disable %/} ux-wise
I'm just trying to handle an object in "dot notation" for firestore database
````
const updateObject = {
  events: [
    ...inter,
    {
      ...this.state.evHistory[p - 1],
      "rating": {
        [this.props.auth.uid]: {
          "updown": true,
          "authorId": this.props.auth.uid
        }
      },
      "ratingLevel": x.ratingLevel + 1,
      "votes": x.votes + 1
    }
  ]
};
````
 but it removes the quotes on "format document"

**Comment by ecraig12345** [comment]
@NickCarducci That’s not eslint doing the formatting, that’s [Prettier](https://prettier.io/). You *should* be able to put a `prettier-ignore` comment above the line you don’t want formatted using the syntax you described (though finding exactly the right place to put it to get the effect you want can be challenging).

**Comment by FrankSandqvist** [comment]
I found a decent workaround so far by just disabling specific rules at the top of my files
`/* eslint-disable no-undef, no-unused-vars */`

**Comment by allforabit** [comment]
This doesn't work for create react app apps as far as I can see. It's literally just that one rule that I want to disable!

**Comment by SaraVieira** [comment]
Hey!

This was never implemented at least until now, you will still need to do a workaround like @FrankSandqvist  mentioned

**Comment by allforabit** [comment]
Thanks @SaraVieira , that workaround would be acceptable but it doesn't seem to be working for me: https://codesandbox.io/s/disable-unused-vars-example-syt2t?file=/src/App.tsx

**Comment by SaraVieira** [comment]
Hey

In your case it needs to be these three: 

```
/* eslint-disable no-undef, @typescript-eslint/no-unused-vars, no-unused-vars */
```

because you are using TS and need to disable that too :(

**Comment by allforabit** [comment]
Oh brilliant thank you so much! Red squigglies be gone :-)

**Comment by SaraVieira** [comment]
Nice! Sorry, we do not allow for custom config yet :(

**Comment by jsejcksn** [comment]
Unresolved

**Comment by SaraVieira** [comment]
Hey

Thank you for bringing this to our attention, I have just added it to our internal backlog that we do want to make public but for now, it's all in notion.

I will be closing but to make sure what we have in GitHub is just issues and all our feature requests are tracked in our roadmap.

We will definitely make an announcement when this is done 

Again, thank you!

**Comment by jonathanSimonney** [comment]
Just in case given what I read from the discussion, getting the option to configure it for real (rather than just a pure way to disable it entirely) would be immensely helpful for me. 

My main goal was to reproduce / ensure I could reproduce a would-be bug with some specific plugin of eslint, and for this, to make a working codesandbox example with the behaviour shown clearly. 

Thank you very much for the tool and best of luck with your work on it. ❤️

**Comment by rajsite** [comment]
> Hey @sitek94 - This is still something that we're actively exploring but there are some issues that we haven't managed to resolve just yet. If we manage to resolve them we won't be able to release this until at least next year.

Interested for the use cases of eslint, typescript-eslint, and angular-eslint integration in the codesandbox editor 👍

**Comment by tjcrowder** [comment]
I wanted to demonstrate top-level `await` for someone, and couldn't use CodeSandbox to do it because there was no way to tell CodeSandbox not to run ESLint on the file -- and ESLint's parser failed on the top-level `await`! (It must be a bit out of date?) Since it's a parsing-level error, I can't just disable ESLint for that part.

I was surprised to see that adding an `.eslintIgnore` file didn't fix it, nor did adding an `"eslintIgnore"` entry in `package.json`.
