### ISSUE TITLE
Saved work got reverted

### ISSUE THREAD

**Issue by EnoahNetzach** [codesandbox/codesandbox-client#1975]
# 🐛 bug report

Sometimes (rarely), when I reload a sandbox, or when I open it twice, I find that some of the recent changes have been reverted.
I also noted that the transpiled files are still the correct ones (hence not reverted) until I save or reload again.
I didn't check the `localStorage` version of it, but will do next time it happens.

The sandbox where this happened the most is [this one](https://codesandbox.io/s/n7mo22qpjp), but it's the one I use the most as well.

I found some related issues:
 - https://github.com/codesandbox/codesandbox-client/issues/1724 but it happens without the app freezing;
 - https://github.com/codesandbox/codesandbox-client/issues/1770 but it happens without forking;
 - https://github.com/codesandbox/codesandbox-client/issues/1343 but it happens also without having multiple tabs.

I use codesandbox extensively (and **love** it!), but sometimes I'm scared of closing a tab, and end up duplicating it to check that everything is in its place, before closing them.

**Comment by lbogdan** [comment]
Hey @EnoahNetzach ,

Did you get a chance to debug this further?

**Comment by steveswork** [comment]
Dealing with the same issue right now. "Saved all" codesandbox work, updated local machine and reloaded codesandbox. Codesandbox says it recovered lost files. But there were no lost files prior to shutting down the machine. Now, my files are outdated and contained unfinished files. And several child components are breaking in several places. My intention was to start integrating the finished work to my main application but now I am redoing the work all over again since the extent of the damage is not yet clear to me.

I appreciate using codesandbox for doing one-off proof of concepts on new feature components and testing them before integrating them to my applications. I might have to stop using it for the time being.
