### ISSUE TITLE
Failed to import dependency. Could not find module in path.

### ISSUE THREAD

**Issue by Majed6** [codesandbox/codesandbox-client#2009]
# 🐛 bug report

## Description of the problem

Could not find module in path: 'js-dos' relative to '/src/index.js' when trying to import js-dos.

## How has this issue affected you? What are you trying to accomplish?

Trying to import js-dos.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1558343146-fac713406
| Browser          | Firefox 
| Operating System | Windows

**Comment by Saeris** [comment]
I believe this is because you're not importing the module correctly. According to the library's documentation, this is how you would use it as a module:

```ts
import { Dos } from "js-dos/dist/typescript/js-dos"

// your code....
```

I don't know what else you would need past that to accomplish whatever it is you're looking to run, but with this change the bundler appears to be able to find the library and it appears to be running.

**Comment by Majed6** [comment]
Thanks a lot. It's loading now.
