### ISSUE TITLE
BrowserMonkey tests broke in CodeSandbox

### ISSUE THREAD

**Issue by CompuIves** [codesandbox/codesandbox-client#2019]
# 🐛 bug report

## Description of the problem

BrowserMonkey tests broke when we started using JSDOM for the window.
https://codesandbox.io/s/2x8kv8voyn.

![image](https://user-images.githubusercontent.com/587016/58912509-7a2a4200-871a-11e9-9361-8593a4e9fa11.png)

## How has this issue affected you? What are you trying to accomplish?
BrowserMonkey uses CodeSandbox for their examples, the examples now broke.

A "fix" would be to use the native window again, but that would break other sandboxes as they assume that the window gets cleaned between different tests. I'm currently thinking of either:

1. Making the use of native window an option, default to jsdom
2. Find a way to detect when to use the native window

I'm curious what others think!

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by Saeris** [comment]
What would be the criteria for auto-detection here? I feel like if we were to go that route, we'd need to document it, and then people who want to opt-in to it would need to explicitly modify their code to use the native window, which wouldn't be any different than manually setting a config option somewhere.

Should this be part of a larger update for tests? AFAIK we only expose the testing interface within certain templates and don't have a way for users to manually enable it. This is also a consideration we need to take into account for custom templates (enabling editor features like this).

IMO the best way to go about this would be to read from `sandbox.config.json` to override the relevant parts of the editor state defaults. That way with the new custom templates feature we can save out editor configuration alongside the template files instead of persisting it to the database, and users can import projects from GitHub with their desired editor features without having to explicitly create a template.

**Comment by CompuIves** [comment]
Currently the tests are enabled for all templates, but it would be good to enable/disable them for templates.

I agree, the config option is the most transparent option and has a documenting function as well. We can even auto-detect when eg. browsermonkey is used and automatically create the config file.

**Comment by dereke** [comment]
Having a config option would be fine, the only negative to that is that users will get a cryptic error when they try and use browser monkey without the config option.
So if there is a way of detecting browser monkey is in use and prompting them to set the config option that would be ideal.

**Comment by dereke** [comment]
@CompuIves any progress on this?
Is there anyway I can add the fix myself? is it all open source?

**Comment by batiskafff** [comment]
@dereke  Yes, it is open source.

Most likely you will need one of these files:
https://github.com/codesandbox/codesandbox-client/tree/master/packages/app/src/app/components/Preview/DevTools/Tests/index.tsx

https://github.com/codesandbox/codesandbox-client/tree/master/packages/app/src/sandbox/eval/tests/jest-lite.ts
