### ISSUE TITLE
Symbol % in the address bar crashes the app

### ISSUE THREAD

**Issue by denexapp** [codesandbox/codesandbox-client#2050]
# 🐛 bug report

## Description of the problem

I was trying to check how react-router works with encoded url params but faced codesandbox crash when i typed the % symbol in the address bar.

## Steps to reproduce
Open sandbox: https://codesandbox.io/s/vanilla
Type % symbol in the address bar of browser window
Codesandbox will crash with errors in the console

I captured this on a video: https://streamable.com/sbjp0

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io/s/vanilla |
| Browser          | Yandex Browser 19.6 (like Chrome 74) |
| Operating System | Windows 10 Pro 17763.503 |

**Comment by pshrmn** [comment]
The quick fix is to catch the `URIError` and fall back to the `url` string; I haven't looked at the implications of that to see if it would cause any issues.

I was actually thinking about taking a closer look at the integration between the fake browser's history and the fake browser component because I believe that there is some overlap there that can be cleaned up. If someone wants to implement the quick fix, that would be great, otherwise I'll see if there is a better fix during my review.

**Comment by denexapp** [comment]
From my point of view, codesandbox should not decode the url string but rather keep it untouched.
For example: if I paste `%20` to the address bar it'll be replaced with space. It's not obvious and I don't think users expect it to behave like this

**Comment by pshrmn** [comment]
Oh, yeah, not decoding makes a lot more sense.
