### ISSUE TITLE
README.md does not display in embed when selected as "default module to show".

### ISSUE THREAD

**Issue by adamjaffeback** [codesandbox/codesandbox-client#2091]
# 🐛 bug report

## Description of the problem

When sharing a CodeSandbox, I clicked `README.md` to display as the default module users see when the embed opens. However, a random file is displayed instead of the `README.md`.

### Steps to reproduce
- Open [CodeSandbox](https://codesandbox.io/embed/code-challenge-uhz9n)
- Click _Share_
- In the _Configure_ section of the modal, click on _Sandbox options_
- In the _Default module to show_ section, click on `README.md`

In my case, `tests/state/reducers/gameReducer.js` shows, not `README.md` from the root directory.

## How has this issue affected you? What are you trying to accomplish?

This CodeSandbox is a solution to an interview problem. When the reviewing developer opens my solution, I'd like them to show them the `README.md`. The `README.md` shows my ability to write documentation and includes notes about my implementation.

Outside of the reviewing developer, visitors to the embed may be unfamiliar with [Conway's Game of Life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life). The `README.md` includes information about the purpose, rules, and gameplay.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1561388488-a3b21c078|
| Browser          | Chrome Version 75.0.3770.100 (Official Build) (64-bit)
| Operating System |macOS Mojave 10.14.4

**Comment by adamjaffeback** [comment]
![Screen Shot 2019-06-24 at 2 27 28 PM](https://user-images.githubusercontent.com/8163408/60053286-52305d80-968c-11e9-9e89-2296109fcd03.png)

**Comment by adamjaffeback** [comment]
When README.md is clicked, the embed links on the right don't update. However, I can access the README.md by directly editing the URL in the browser: [https://codesandbox.io/embed/code-challenge-uhz9n?fontsize=14&module=%2FREADME.md](https://codesandbox.io/embed/code-challenge-uhz9n?fontsize=14&module=%2FREADME.md)

**Comment by siddharthkp** [comment]
Debugging this issue - It seems like the issue might be a tiny variation of it:

The reason embed link doesn't contain `README.md` is because that is the default landing path. (code: [ShareModal/getCode.js](https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/app/pages/common/Modals/ShareModal/getCode.js#L45-L53))

You can test this by going to [/s/code-challenge-uhz9n](https://codesandbox.io/s/code-challenge-uhz9n), it opens `README.md`.

Buuuuut, in embed mode ([/embed/code-challenge-uhz9n](https://codesandbox.io/embed/code-challenge-uhz9n), it tries to find a js file to render. This is probably a 🐞. I'll look into this further to confirm.
