### ISSUE TITLE
Typescript types not working on embed

### ISSUE THREAD

**Issue by donifer** [codesandbox/codesandbox-client#2106]
# ❔ Typescript types not working on embed

I'm playing around with this sandbox which is a React + TS + styled-components setup. Everything is working fine, however, when I try to embed it on a page I can't get the TS types to work.

Is this expected? Eg: `React`, `styled`, etc are of type `any` and I don't get any TS errors/autocompletes.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1561557066-4a5dea6e4
| Browser          | Chrome 75
| Operating System | macOS

**Comment by SaraVieira** [comment]
Hey!

The embeded doesn't work mostly because it is not vscode. But it is a very requested feature so it will be something we will be adding in the future 

But no ETA

**Comment by elyalvarado** [comment]
Commenting just to keep the issue open, as I'm still interested in his improvement being implemented.

**Comment by SaraVieira** [comment]
Hey!



I will close this and add it to our internal backlog so that it gets more visibility and GitHub becomes for issues. Once this is done I will make this page public so that people can vote for features :)

I do not have an ETA for this tho as this would be super hard to implement since the embed does not use monaco

Thank you!
