### ISSUE TITLE
Typescript is not working in embedded sandboxes

### ISSUE THREAD

**Issue by Siegrift** [codesandbox/codesandbox-client#2157]
# 🐛 bug report
Typescript is not working in embedded sandboxes

## Description of the problem
I created following embedded sandbox: https://codesandbox.io/embed/tsfunct-zysfi
However when I open the link, the types after calling my library (which I am demoing) returns any according to TS.
When I fork the sandbox the typescript definitions are correct.

## How has this issue affected you? What are you trying to accomplish?
I want the type definitions to be correct in embedded version as well.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/embed/tsfunct-zysfi

**Comment by lbogdan** [comment]
Hey @Siegrift ,

That's pretty much expected, as the embed uses the [Monaco editor](https://microsoft.github.io/monaco-editor/), which only infers types from the current file, AFAIK. As a last resort, you can use the editor URL https://codesandbox.io/s/tsfunct-zysfi for embedding - although that's much heavier, as it loads the whole VSCode, including the TS language service.

**Comment by CompuIves** [comment]
Might be interesting to use a more sophisticated type autocompletion approach for the embed in the future.

**Comment by Siegrift** [comment]
Thanks, having the correct inference is what is the most important to me (and I guess other people and well). Having the link which is heavier is not a big problem I guess...

**Comment by amannn** [comment]
I have the use case that I'm preparing sandboxes for a lecture I'm giving. The sandboxes are embedded into reveal.js slides and I use them to develop certain features during the lecture. I'm freezing the sandboxes so that every time I open the slides, I can start from the same position.

The embed feature works well for this use case, but not being able to use TypeScript is a bit a dealbreaker unfortunately to demo features that are closely related to TS. Using the full editor URL requires creating forks all the time and also I have to login, which disrupts the flow a bit.

@CompuIves Any chance we could reopen this issue?
