### ISSUE TITLE
react client to connect to node container

### ISSUE THREAD

**Issue by NickCarducci** [codesandbox/codesandbox-client#2263]
1a. Can I use localhost in a node container? Is this trying to open a port on CodeSandbox servers?
I followed a tutorial to get this node app starting, but 502 bad gateway.  maybe something wrong with my package.json
1b. Do I have to use CORS?  
2. Can a node container connect to react container?
3. Can I run react & node in CodeSandbox and save user data on my own servers?

start of node project: https://codesandbox.io/s/suspicious-cloud-6dk2n?fontsize=14
reactjs: https://codesandbox.io/s/zen-dijkstra-1c31n?fontsize=14

### Environment

| Node  | I can't fine node version in package.json or dependencies.  yarn.lock, line 8443: "@types/node" "^10.1.0" dependency for protobufjs |
| React | "16.8.6" |
| ---------------- | ------------ |
| СodeSandbox  |
| Chrome |
| Mac OS |

**Comment by lbogdan** [comment]
Hey @NickCarducci ,

1a. I took a look at your [sandbox](https://codesandbox.io/s/suspicious-cloud-6dk2n), and the reason it's not starting is because you're using ES6 syntax (`import` & co.), and `node` doesn't know how to handle that. You'll probably want to use [babel-node](https://babeljs.io/docs/en/babel-node) to handle that.

1b. Yes, that's just how browsers work.

2. I'm guessing you actually meant if the react sandbox can connect to the node one? The answer is yes, here's an example of a `vue-cli` sandbox https://codesandbox.io/s/vue-intro-workshop-3lp05 , that is using another `node` sandbox https://codesandbox.io/s/lpykmjrl9l as its API - which I guess is what you're aiming for, too?

3. As long as you can access the data on your servers from the sandbox container, sure.

**Comment by NickCarducci** [comment]
1a] If I use `Localhost` will it run on your server?
1b] You say that like it is automatically applied but I'm sure you mean I have to implement CORS
2] Thanks for this I'll
3] probably host the node sandbox similar to this example on my computer for now

**Comment by lbogdan** [comment]
1a] What exactly do you mean by _"use localhost"_?

1b] What I meant is "Yes, you'll have to implement CORS". 🙂 For example, in the API sandbox I linked above I'm using [`json-server`](https://github.com/typicode/json-server), which comes with CORS enabled by default.

**Comment by NickCarducci** [comment]
1a] when _calling_ `localhost` as a port to get or set information in the node database like 
<img width="607" alt="Screen Shot 2019-08-09 at 11 35 04 AM" src="https://user-images.githubusercontent.com/12148373/62790795-d2bee800-ba99-11e9-97d4-5062a03fdf63.png"> would it try to connect with your server since this is a cloud ide? 1a*] `localhost` has no production use right? just for testing..
1b] Off CodeSandbox topic, but for closure: I want to wrap the (Graphql server with the public domain) in firewall, mirror & persist and find a way to do something like open one port for public data a port for each authenticated users separated by express router
thx @lbogdan

**Comment by NickCarducci** [comment]
Sorry, I'm still having trouble with 502 bad gateway.  I'm sure this isn't a CSB issue but I followed the tutorial.  Before when I opened this Question I used Ben Awad's slack clone to test node and now I'm using Traversy Media "Building a GraphQL server" which is simpler. 
 Still 502.  https://codesandbox.io/s/suspicious-cloud-6dk2n?fontsize=14
