### ISSUE TITLE
Close editor not working

### ISSUE THREAD

**Issue by kirubiel** [codesandbox/codesandbox-client#2264]
### Close Editor not working

Pressing the Close Editor in the drop down menu of "File" nor using the keyboard shortcut "Ctrl + F4" not working.

I was trying to close the current sandbox and move back to my dashboard.

Vanilla.js
Firefox Developer Edition 69.0b10 (64-bit)
Windows 10 Home Build 1903

**Comment by oskarabc** [comment]
"Not working" as in, not going back to Dashboard as you were expecting or "not working" as in: it shows you an error or it does nothing?

After a quick test it did react to my input. Close Editor is supposed to be closing the currently active file, which is shown in the Editor section of the user interface. That's why the naming can be a little confusing perhaps. It seems you experience it being more like in an app where you would expect to go back to Dashboard. Curious to learn if anyone else has the same experience and whether the Dashboard is the most intuitive state to return to.
