### ISSUE TITLE
Cannot change template to "node" for sandbox imported from GitHub

### ISSUE THREAD

**Issue by jsejcksn** [codesandbox/codesandbox-client#2354]
# 🐛 bug report

## Description of the problem

[While recently learning about Next.js](https://nextjs.org/learn/basics/navigate-between-pages/setup), I needed to clone a repo at:

https://github.com/zeit/next-learn-demo.git

so I followed the steps below:

 1. Copy repo URL (above)
 2. Create new sandbox
 3. Select the _Import_ tab
 4. Paste repo URL in the input box (which generated [this link](https://codesandbox.io/s/github/zeit/next-learn-demo))
 5. Click _Open Sandbox_. The sandbox was created and the environment was set to `create-react-app`

Following the instructions at the [Import from GitHub documentation](https://codesandbox.io/docs/importing#import-from-github), I see this:

> Additionally, you may specify a `template` property in your `./sandbox.config.json` file to override the detected template..
> 
> ```json
> {
>   "template": "node"
> }
> ```

Continuing:

 6. Click the _Configuration Files_ icon in the side bar
 7. Locate `sandbox.config.json` and click _Create File_. This action forks the sandbox and the file is created and opens in the UI view.
 8. In the UI view, there is no template choice for Node.js, so click _Open in file editor_
 9. Select all in the file and delete. Copy and paste the following code from the documentation and save the file:

```json
{
  "template": "node"
}
```
 10. The environment does not change. Refresh the page.
 11. The environment is still `create-react-app`

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | **I have no idea where to find this in the UI.** Where is it?
| Browser          | Chrome
| Operating System | Windows 10

**Comment by Saeris** [comment]
The root of your problem here isn't that you're following the instructions for specifying a sandbox environment wrong, it's that the repo you've imported is basically a mono-repo with multiple projects in it (there's not enough information in the top level package.json for CodeSandbox to figure out what to do with the imported repository).

Instead what you should be doing is importing each sub-directory individually, such as the following URLs:

https://codesandbox.io/s/github/zeit/next-learn-demo/tree/master/1-navigate-between-pages
https://codesandbox.io/s/github/zeit/next-learn-demo/tree/master/2-using-shared-components
https://codesandbox.io/s/github/zeit/next-learn-demo/tree/master/3-create-dynamic-pages
https://codesandbox.io/s/github/zeit/next-learn-demo/tree/master/4-clean-urls
https://codesandbox.io/s/github/zeit/next-learn-demo/tree/master/6-fetching-data
https://codesandbox.io/s/github/zeit/next-learn-demo/tree/master/7-styling-components
https://codesandbox.io/s/github/zeit/next-learn-demo/tree/master/8-deploying

While we do support a "Module View" which renders the currently selected file for client sandboxes (Downshift's examples use this), it doesn't work for container sandboxes.

**Comment by jsejcksn** [comment]
@Saeris Thanks for responding. I understand that I can import all of the directories individually, but that does not help me understand why the environment is not changing when I follow the correct steps in the documentation, or what the prerequisites are for the environment to change to Node. Will you please explain that?

**Comment by lbogdan** [comment]
@jsejcksn Currently it's not possible to switch sandboxes between client and server / container templates - in your case, from `create-react-app` to `node`. We have this feature on out short/medium-term roadmap, although I can't give you an exact ETA right now.

**Comment by jsejcksn** [comment]
@lbogdan So how would I explicitly start a Node sandbox and then clone in the contents of a git repo?

**Comment by lbogdan** [comment]
@jsejcksn You can "tell" CodeSandbox to import a GitHub repo using the `node` template by adding a `sandbox.config.json` file in the root, with contents
```json
{
  "template": "node"
}
```
and then (re)importing it in CodeSandbox by going to `https://codesandbox.io/s/github/owner/repo`.

**Comment by jsejcksn** [comment]
@lbogdan So if I don't control the repo (and therefore cannot add the config file), this is not possible? (I realize I can fork, but that's not in scope of my question.)

**Comment by lbogdan** [comment]
As I said, it's not possible right now, the only way that would work is to fork the repo, add that file to the fork, and import the forked repo in CodeSandbox.

Can you detail a bit what are you trying to do, exactly, maybe we can suggest a better workflow?

**Comment by jsejcksn** [comment]
@lbogdan I'm not trying to achieve a specific goal at the moment beyond the case in my initial post. I am just trying to understand the functionality and limitations of CodeSandbox so that I can use it with as little friction as possible (not needing to fork a repo to add a config, etc. vs knowing that I do need to do that and when).

I think my confusion came from the wording in the documentation:

> Additionally, you may specify a `template` property in your `./sandbox.config.json` file to override the detected template.

It did not specify that this file must be present in the repo before cloning, so I thought that creating or modifying after cloning would modify the environment.

Thank you for informing me about the details of this workflow. 🙏

**Comment by lbogdan** [comment]
@jsejcksn You're right, it is a bit confusing, mainly because that sentence was written before server / container sandboxes were a thing, and not updated since.
