### ISSUE TITLE
Stuck at Loading Sandbox

### ISSUE THREAD

**Issue by sdinesh86** [codesandbox/codesandbox-client#2365]
# 🐛 bug report

## I am not able to open any of my sandbox's, I also tried creating new sandbox's and the same thing happens with every one of them.
This is started happening after i tried moving 2 of my sandbox's from my folder to a folder in the team.

I had faced the same earlier ( after i tried creating a live session from one of my sandbox's ), but it somehow got resolved after some time, and i didnt look into it again as i felt it might be a one time thing but now its happening again.

Below is the console log for the window
![image](https://user-images.githubusercontent.com/4415575/64167873-f17d8800-ce67-11e9-8a83-d35081728a1b.png)

**Comment by CompuIves** [comment]
Interesting, it seems like some requests are blocked. What does your network tab say?

**Comment by sdinesh86** [comment]
I dont have access to the device now, but will check it and update the thread

**Comment by jnielson94** [comment]
I've run into the same issue at work (haven't tried it at home yet) where the websockets are being closed. The network tab didn't reveal anything too enlightening to me (I'll still attach a zipped up version of the HAR file though). 
[codesandbox.io.har.zip](https://github.com/codesandbox/codesandbox-client/files/3581413/codesandbox.io.har.zip)

It happened only with container/server sandboxes (the client-only ones worked fine), so like next and gatsby both failed but the plain react one works. 

Happened when I was logged in, as well as when not logged in on an incognito window.

Any ideas on what I could try? I know it's worked previously, but I couldn't say when it stopped since I don't usually use the server sandboxes (usually I just use my computer for them).
