### ISSUE TITLE
next.js and TypeScript support

### ISSUE THREAD

**Issue by paulbrie** [codesandbox/codesandbox-client#2371]
# 🐛 [next.js] Next and TypeScript Support

## Description of the problem
Although the code editor supports `.tsx` files and Next 9 supports them natively, the box crashes if it is a component, or doesn't find the page if it is in the `/pages/` folder. 

## How has this issue affected you? What are you trying to accomplish?
I can't use Codesandbox for this type of projects.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/hello-world-jsu2i

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1567437574-dd109d005
| Browser          | Chrome
| Operating System | Mac

**Comment by lbogdan** [comment]
Hey @paulbrie ,

Because of server sandboxes' persistent storage combined with how `node_modules` caching works in forked server sandboxes, the sandbox you linked still uses `next@8.0.3` - you can check by opening a terminal and running `yarn why next`. What you can do is:
- edit `next`'s version in `package.json` to `"next": "^9.0.5",`, save
- we will run `yarn install` inside the sandbox
- restart the sandbox to use the new version, it will error saying that it needs some TypeScript related packages
- open a terminal, run `yarn add --dev typescript @types/react @types/node`
- restart the sandbox again, now it should work: https://codesandbox.io/s/hello-world-p1tif .

**Comment by paulbrie** [comment]
This is awesome! I got confused by the next@latest indication. Thanks a lot for the quick response! ;)

**Comment by lbogdan** [comment]
You're welcome! When in doubt, always use `yarn why`. 🙂
