### ISSUE TITLE
💥 Crash Report: "has invalid format"

### ISSUE THREAD

**Issue by dotansimha** [codesandbox/codesandbox-client#2408]
<h1>💥 Crash Report</h1>

<h2>What were you trying to accomplish when the crash occurred?</h2>

Trying to load a repo from GitHub into CodeSandbox, repo is located in: https://github.com/Urigo/WhatsApp-Clone-Server

<h3>Link to sandbox:</h3>

https://codesandbox.io/s/github/Urigo/WhatsApp-Clone-Server

<h3>Crash Details</h3>

<details>
<summary>Environment</summary>

| Browser |  Version  | Operating System |
| ------- | --------- | ---------------- |
| chrome | 76.0.3809 | OS X 10.14.6           |

**Route:**
https://codesandbox.io/s/github/Urigo/WhatsApp-Clone-Server

</details>

<details>
<summary>Error Message</summary>

Getting it from `GET https://codesandbox.io/api/v1/sandboxes/github/Urigo/WhatsApp-Clone-Server`

```bash
{"errors":{"title":["has invalid format"]}}
```

</details>

**Comment by CompuIves** [comment]
Hmm, it seems to be caused by the filename "Unsplash.RandomPhoto.2019-05-09T14:45:43.850Z.graphql". We currently check against `:` and invalidate a file if it has that in the name, I always thought this was normal for every OS though. Need to do a bit of testing on my local fs to see if I can create `:` files, if that's the case I can just remove the validation.

**Comment by sanandnarayan** [comment]
facing the same issue when I am trying to import [this repo](https://github.com/Codebrahma/cbweb)

**Comment by SaraVieira** [comment]
On MacOS it is invalidated

![CleanShot 2020-07-17 at 18 12 29](https://user-images.githubusercontent.com/1051509/87807887-18169880-c859-11ea-9c55-55f6309f2813.png)

**Comment by ardatan** [comment]
No stale. It still persists

**Comment by jalajcodes** [comment]
This issue still exists.

**Comment by rayfoss** [comment]
This is odd... I have a project that imported fine when it had an old January version, but fails to import with the current version. I don't think I have assets with strange names.

Is there anyway for me to see what file is causing the issue?

**Comment by rayfoss** [comment]
@lbogdan This issue should be open... It's a live bitting and blocking bug

I'm thinking of working around this by manually hacking up a Node 14 instance to Node 16 and cherry picking my code into it. That sounds like an awful idea given git will not sync.

I have a project that imported fine when it had an old January version, but fails to import with the current version. I don't think I have assets with strange names.

Is there anyway for me to see what file is causing the issue?

Update: I had an ampersand in one of my file names... removed it and it didn't help. Every other file is named with roman characters dots, hyphens and underscores... that's it.

**Comment by sannek** [comment]
@rayfoss do you have a link to the repo you're trying to import, then I can try pinpoint what files are causing the issues and see if/how we can fix it on our end. (You can also email it to `hello@codesandbox.io` if you'd rather not post it here)

**Comment by rayfoss** [comment]
The issue was most likely 

> @rayfoss do you have a link to the repo you're trying to import, then I can try pinpoint what files are causing the issues and see if/how we can fix it on our end. (You can also email it to `hello@codesandbox.io` if you'd rather not post it here)

I'll figure it out eventually... Part of the issue is the importer detects the project as a Vue sandbox... when it should really be a container for any project with legacy and gravitas.

It sounds like the error comes from the container template in the sandbox rather than our own code... We can obviously trick it into using node and then "hydrate it".

Also the 500 module limit is really deceptive... I think I mentioned that somewhere here. I had 700+ and paired it down to sub 350... But it wasn't talking about node_modules, it's was concerned about csv files. I'll concatenate them and move on... but still

**Comment by Pete-Fowler** [comment]
I got the same error message trying to import this: https://github.com/Pete-Fowler/battleship

**Comment by sannek** [comment]
@Pete-Fowler -- If this is still happening for you,  can you make a new issue and give a little more information? I cannot reproduce the error when trying to import that repo. (See here on [CodeSandbox](https://codesandbox.io/s/github/Pete-Fowler/battleship) V1).

However, since you are working with a project existing on GitHub, you will probably have a better experience working in Projects / V2 -- see [here](https://codesandbox.io/p/github/Pete-Fowler/battleship/main?file=%2FREADME.md)

**Comment by Pete-Fowler** [comment]
Hi - I'm not sure what happened or what is different, but I just tried
again to import it and it worked. Thanks.
