### ISSUE TITLE
Re-Organization of Templates into their technology of concern.

### ISSUE THREAD

**Issue by NullVoxPopuli** [codesandbox/codesandbox-client#2421]
Currently, templates are organized by their implementation details -- I don't think users don't need to be concerned with this, and it hurts discoverability (I've heard from multiple people that they didn't think clicking on "container" made sense, so they assumed there was no X template).

It'd be cool if templates were organized by their intended use.

I propose the following categories:

 - Frontend
   - Angular
   - CxJS
   - Dojo
   - Ember
   - Marko
   - MDX Deck
   - Preact
   - React
   - React + TS
   - Reason
   - Static
   - Svelte
   - Styleguidist
   - Vanilla
   - Vanilla + TS
   - Vue

 - Backend
   - Node
   - Apollo
   - Nest
   - Unibit

 - FullStack
   - Next.js
   - Nuxt.js
   - Gastby
   - Grindsome
   - AdonisJs
   - Quasar
   - Sapper
   - VuePress

**Comment by Saeris** [comment]
That's a good suggestion! We're currently working on a new way to organize our official templates and provide a means for users to explore and follow community made templates, so the current categorization of Client and Container will be changing. It may be worth considering adding a filter for categorization as you've described here, the only question being how we'll apply this to user-created templates. Right now we have it divided up as we do because of the differences in the sandbox execution environments and the inability to switch between the two.

**Comment by SaraVieira** [comment]
Hey!

Right now we did change this to be able to have users creating them and also remove popular so you can control your modal and also in the explore they are organized by technology 🌈

**Comment by NullVoxPopuli** [comment]
The new organization is much better. The sorting is goofy, but at least everything is on the same page now
