### ISSUE TITLE
$5 minimum logic gets in way of typing custom value on patron page

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#2463]
# 🐛 bug report

## Description of the problem
Click into the value box on the patron page, and try to type 20. If you try this by first deleting the 1 in front of the 0 from the default 10 amount, and type 2 then it'll end up saying 50.

It looks like when you delete the '1' leaving just 0, it replaces the value in the box with the minimum 5. Then after you type the 2 it caps it at 50.

## How has this issue affected you? What are you trying to accomplish?
Confuses some folks when trying to add a custom amount.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/patron

**Comment by Jensderond** [comment]
Found the problem, not a solution...

https://github.com/codesandbox/codesandbox-client/blob/a0295e1fe337d330c66753e5098f74e3945134cf/packages/app/src/app/pages/Patron/PricingModal/PricingChoice/index.tsx#L51-L70

The onChange method is called twice and since the range component has a min value of 5 and a max value of 50 this gets reset. 

I added log statements in the onChange methods of both components and this is the result when typing **"20"**:
![image](https://user-images.githubusercontent.com/6972822/65956539-e4de5680-e44a-11e9-9da3-efefc4970f7d.png)

**Comment by arthurdenner** [comment]
@garethx, should we close this since the Patron was rebranded to Pro, the interface has changed and there is no value input anymore?
