### ISSUE TITLE
Preview Tabs Can't Be Closed

### ISSUE THREAD

**Issue by zsoltime** [codesandbox/codesandbox-client#2583]
# 🐛 bug report

## Description of the problem

When I open the _Server control panel_ and click on the main port, it opens a new browser tab which can't be closed. Opening other ports works fine; they're opened in a new tab and can be closed.

Reloading, toggling the preview doesn't help either.

![ScreenFlow](https://user-images.githubusercontent.com/3144128/65859273-b899db80-e35f-11e9-85e5-c52aa4ef67ab.gif)

## How has this issue affected you? What are you trying to accomplish?

I've got five useless browser tabs open 🤓It would be great to close them.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1569330198-771afd31e |
| Browser          | Chrome 77 |
| Operating System | MacOS Mojave |

**Comment by zsoltime** [comment]
It seems the problem is caused by this. `closeable: true` is not added to the `tab` object. 

https://github.com/codesandbox/codesandbox-client/blob/46f9d7c00afd659744053830be8e35e72eee6c16/packages/app/src/app/overmind/namespaces/server/actions.ts#L189-L195

Is there any way to check the number of tabs open on the main port? Or could we just set it to `closeable`?

**Comment by yeion7** [comment]
@CompuIves I'm not sure which is the best solution here, I thought in two options

* Disabled button to create  new main port tabs 
* Evaluate if there is one main port tab open and then add the  `closable` option to new ones

What do you think?

**Comment by zsoltime** [comment]
Almost forgot to mention that I would like to work on this one 😇 I'm happy to submit a PR if you know which option is better.

**Comment by CompuIves** [comment]
Hmm, I think the thing that goes wrong here is that we are not reusing the existing tab that's already open(?). If you open a tab with port 3000, and there is already a tab open on port 3000, it should open the existing tab instead of creating a new one. Maybe there's a bug somewhere there, I think we should look there

**Comment by CompuIves** [comment]
It seems like this broke when we moved to overmind, we had this logic before:
https://github.com/CompuIves/codesandbox-client/blob/623b4f3a5cb55adb14ea695ca96b1bb2324befd7/packages/app/src/app/store/modules/editor/sequences.js#L386-L396

That was responsible for getting the devtools tab, if it's there we would open that instead, otherwise we would create a new tab. Now it's just this logic:
https://github.com/CompuIves/codesandbox-client/blob/623b4f3a5cb55adb14ea695ca96b1bb2324befd7/packages/app/src/app/overmind/namespaces/server/actions.ts#L186-L202

Where there is no check at all. We need to get that check back in that checks whether the tab is already opened.

**Comment by aoberoi** [comment]
I understand that the above PR will prevent more than one main port tab from being opened.

But for a sandbox which already has several main port tabs open, once the above PR is deployed, will I be able to close them? Will they automatically be closed?
