### ISSUE TITLE
Modules not downloaded in CodeSandbox: Cannot find module

### ISSUE THREAD

**Issue by EddyVinck** [codesandbox/codesandbox-client#2589]
# 🐛 bug report

## Description of the problem

![image](https://user-images.githubusercontent.com/23434753/65906773-68546500-e3c3-11e9-9e93-0335f5c91b5f.png)

## How has this issue affected you? What are you trying to accomplish?

I am trying to set up an example for a TypeScript error I am trying to solve, but the `styled-system` packages don't seem to be working.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1569832586-d5f1897b0
| Browser          | Chrome Version 77.0.3865.90
| Operating System | Ubuntu 18.04

**Comment by lakhansamani** [comment]
@EddyVinck Modules are downloaded correctly in CodeSandobx. This is because you are using TypeScript
1. You either need to install types module in dev dependencies example `@types/styled-system`, if that is available
OR
2. You can add `.d.ts` file and declare module there. For this, you might have to include file in tsconfig.


https://codesandbox.io/s/laughing-greider-3ccsb

**Comment by CompuIves** [comment]
Thanks for the clear answer @lakhansamani! I think this answers the question correctly.
