### ISSUE TITLE
Cache Storage gets wiped on reload. How to stop this?

### ISSUE THREAD

**Issue by adrianloh** [codesandbox/codesandbox-client#2838]
# ❔ Question

When I hit reload, the entire Cache Storage gets wiped, including caches I created -- which I need to persist across reloads -- is this expected behavior? Is there a way to stop this?

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by lbogdan** [comment]
Hey @adrianloh ,

Can you please provide a link to your sandbox, and detail a bit current vs. expected behavior?

**Comment by lorisdev** [comment]
@adrianloh I'm guessing this is because of this line
https://github.com/codesandbox/codesandbox-client/blob/67a5a08568f3373c2afd31f20213c47016a93a91/packages/common/src/registerServiceWorker.ts#L94

it is triggered during the serviceWorker registration, if the installation state is `redundant` and the `navigator.storage.estimate()` gives a usage of at least 95% of the available quota.
Then the cache is deleted...

**Comment by lbogdan** [comment]
Hey @adrianloh ,

Did you figure this out, or it's still an issue for you?

**Comment by SaraVieira** [comment]
Closed for lack of activity
