### ISSUE TITLE
Codesandbox doesn't run

### ISSUE THREAD

**Issue by maniac0s** [codesandbox/codesandbox-client#2933]
I created this sandbox and it does nothing

https://codesandbox.io/s/romantic-cherry-l8g14?from-embed

**Comment by zzrez** [comment]
I have the same problem with a React starter I copied and was working 2 days ago. Now the Sandbox does not open, just shows the message "A sandbox error occurred, you can refresh the page to restart the container.". Refreshing the page results in same, opening the sandbox in another window just shows the whole control panel but with same error.

**Comment by CompuIves** [comment]
Hey @zzrez, the sandbox you mentioned tries to import `index.css`, but it seems like only `styles.css` is available. If you rename the import from `index.css` to `styles.css` it should work.

Which other sandbox do you have issues with?

**Comment by zzrez** [comment]
Thanks @CompuIves for answering. I didn't reference that sandbox, and think I deleted yesterday out of desperation when testing out. I am trying to find a good online editor close to VSCode for React & Gatsby projects. After simple tests setting up basic Gatsby starters on codesandbox, I signed up as a patron on Sat. But I fear prematurely, as since then have had difficulties.

As test I have been using https://github.com/thriveweb/yellowcake. On Sat I loaded this, it worked as sandbox. Then I changed gatsby-config.js, and it made no attempt to re-develop. So I reverted back to the original gatsby-config.js. It stayed stuck, no refreshing would put life in it.

Yesterday I loaded this twice (yellowcake & yellowcake2), without making any changes. They worked. Today they failed to start. A bad server connection sign flashed briefly on left, the preview showed "Initializing Sandbox Container" but the terminal showed "Sandbox Container: Starting sandbox 6pvl0.....", six times. 

Yesterday I also made another version, this time with minor changes, cake-mdx. Today this opened without problems.

So the problem so far is that CodeSandBox seems to work well for simpler sandboxes, but is unreliable for slightly more complex projects. If changes are made and it refuses to work, or the container doesn't start up although it was working before, this is a dev killer.

As a result I have been looking urgently at other solutions, eg glitch, codeanywhere, goorm, gitpod, repl.it. Of these gitpod so far looks good and seems to perform without glitches. But if codesandbox can work well and I am making mistakes, then could be worth carrying on. Grateful for help!

**Comment by zzrez** [comment]
Now I just again started yellowcake2 and yellowcake, the copies of the original Gatsby starter. Both threw out different error from the previous errors above, see below. This time yarn seemed to do its bit, and otherwise it looked almost processed. I had to refresh the preview browser to run it through again a couple of times. So each time it seems a different glitch can appear.

![image](https://user-images.githubusercontent.com/11816764/67800072-485ca380-fa4c-11e9-9787-a66a80e598a9.png)

**Comment by siddharthkp** [comment]
error Command failed with exit code 137.

If I'm not wrong 137 refers to out of memory. @lbogdan can probably check this out

Sandbox: https://codesandbox.io/s/github/thriveweb/yellowcake

**Comment by lbogdan** [comment]
As @siddharthkp said, we're currently limiting the sandbox container memory to 1GB, so if the dev server (which in Gatsby's case is webpack) tries to use more than that, it will get killed. Anyhow, I can see that https://codesandbox.io/s/github/thriveweb/yellowcake is working now. @maniac0s Did you change anything?

**Comment by nattri** [comment]
Error while starting sandbox container - 
https://codesandbox.io/s/milkman-express-api-2bhet

It was working fine till yesterday, but now seems to be broken.

**Comment by CodeSandboxNotifications** [comment]
Hey,


Can you please describe your problem? Because for me the sandbox is working, endpoints are reachable.


Thanks in advance.
András



--- original message ---
On July 15, 2020, 7:59 AM GMT+2 notifications@github.com wrote:



Error while starting sandbox container -

https://codesandbox.io/s/milkman-express-api-2bhet

It was working fine till yesterday, but now seems to be broken.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by SaraVieira** [comment]
Closed for lack of activity since the sandbox seems to now be working
