### ISSUE TITLE
Invalid plugin specified in Babel options: "proposal-optional-chaining"

### ISSUE THREAD

**Issue by andrei-cacio** [codesandbox/codesandbox-client#2974]
# 🐛 bug report

## Description of the problem

I am trying to use the babel plugin `proposal-optional-chaining` in a custom `.babelrc` file. I simply added the depedency `@babel/plugin-proposal-optional-chaining` via the Add Dependency button and then I added the `@babel/plugin-proposal-optional-chaining` plugin name in the `plugins` attribute in the `.babelrc` file. Just like the docs stated: https://babeljs.io/docs/en/next/babel-plugin-proposal-optional-chaining.html.

However there seems to be a problem detecting the plugin. 

## How has this issue affected you? What are you trying to accomplish?

Just wanted to play around with the optional chaining proposal

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/headless-http-io6xu

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |   PROD-1572624626-def377908
| Browser          |  Chrome latest
| Operating System | MacOS Catalina

**Comment by yiyi1026** [comment]
I got the same, showing "Transpiling Modules...".

**Comment by alekslario** [comment]
Bump

**Comment by siddharthkp** [comment]
Hi 👋 

I did some tweaking and was able to make this work: https://codesandbox.io/s/proud-hooks-icp6r

1. Move `@babel/core` to `dependencies` instead of `devDependencies`
2. In `.babelrc`, call it `proposal-optional-chaining` instead of `@babel/plugin-proposal-optional-chaining`

Both of these are workarounds and the parsing logic gone wrong, I'm keeping this open as a bug but have fun with optional chaining, such a cool addition! 😄

**Comment by andrei-cacio** [comment]
thank you @siddharthkp! I will give it a go.
