### ISSUE TITLE
Sign up/in using email and password

### ISSUE THREAD

**Issue by danieldanielecki** [codesandbox/codesandbox-client#2988]
# 🌈 Feature

It would have been good addition to give users a choice between GitHub's SSO and "traditional" email/password signing in/up.

**Comment by andrasbacsai** [comment]
@CompuIves Do we consider making email signups available?

**Comment by SaraVieira** [comment]
Hey!

Yeah, this is already in our backlog so I will close this one as it has more visibility in our backlog :)

Thank you

**Comment by jfines** [comment]
I apparently not released yet as I can not find a way to do this. Although codesandbox is far superior in its category I rarely use it because of this. In fact I'm offended by not having the option to sign up using personal email of my choice and I wonder how many others there are that feel the same way. I don't use gihub (I use gitlab - and have a huge investment of time, effort, and learning into it), I don't use google mail (it is configured not to accept messages and I never log into it unless there is a problem), and I don't want google or any other platform tracking my every move. Constraining people to use services that violate their personal security policies is just wrong. I want to use code sandbox and I don't think its fair to be forced into a position like this.

**Comment by JamesACS** [comment]
@jfines We offer signing in through Google, Github and Apple email addresses for standard user accounts. 

We do offer an SSO option, at additional cost, as a part of our Enterprise plans. 

Unfortunately, we have no plans at present to create a native CodeSandbox sign up flow.

**Comment by jfines** [comment]
I know. That's the problem and its the reason I don't use codesandbox (even though it is better than other options). What that means is I've become alienated from using something I wish I could use and I don't think that is fair. Consider the fact that there are many people just like me - in the same situation - who will not use platforms that force you to sign on with other services (such as google and so on) and who would love the opportunity to use codesandbox but that option has been taken from us. Many of those people (including myself) may readily upgrade later - after initially signing up with the free account - and end up increasing your revenue through additional subscriptions.

 

There is a whole community of people (a farily large one) of people who refuse to let google and any other platform interpose themselves in thier personal, daily lives. In addition to that it takes away our power to manage our own subscriptions and credentials in the way we are most comfortable (the same way we manage all our other subscriptions - using a specific, designated email for that purpose). Those people could be your customers if the right environment were provided for them. I just think there are many organizations (and individuals) who really don't understand how big of a deal it is and the very valid reasons why.

 
 

Sent: Friday, February 16, 2024 at 4:07 AM

**Comment by PlusoneWang** [comment]
I also choose not to use CodeSandbox for the same reasons, which is frustrating.
