### ISSUE TITLE
Vue template + Vuetify 2 extremely long building times with tree shaking

### ISSUE THREAD

**Issue by Genroa** [codesandbox/codesandbox-client#3029]
# 🐛 bug report

## Description of the problem

When building a Vue+Vuetify 2 application and following the recommended way of referencing components (for automatic tree shaking), the sandbox takes a very, very long time to transpile/build before displaying anything. The app works fine after that, but any modification causes the entire process to start again, even if only one file was modified. It doesn't seem to occur when manually importing each dependency where needed or rolling back to Vuetify 1.
Also, I seem to get CORS errors on all my projects now. I'll try to investigate it and maybe open another issue about that if no one already created one.

## How has this issue affected you? What are you trying to accomplish?

I am trying to use a Vue+Vuetify 2 boilerplate I made for my personal projects. Problem : it's now basically unusable.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest, I guess |
| Browser          | Chrome 77.0.3865.120 |
| Operating System | Windows 10 |

Packages versions : Vue template, with:
* vue 2.6
* vue-router 3.1.3
* vuetify 2.1.1.10
* vuex 3.1.2

**Comment by lbogdan** [comment]
Hey @Genroa ,

Unfortunately, given how the CodeSandbox in-browser bundler works, that's somehow expected, as we have to fetch and transpile all used components and their dependencies, which takes a lot of time. If you'll open the devtools network tab while we show the "Transpiling Modules..." animation, you'll see that we fetch hundreds of files, including `.sass` ones, that take the longest to transpile. If you think about it, using tree-shaking only makes sense when making a production build, and, as you've experienced, in development is counter-productive, because of all the transpiling.

So I think, in your case, you'd be better off using the full Vuetify bundle.
