### ISSUE TITLE
Live Coding erase whole file on save

### ISSUE THREAD

**Issue by MasGaNo** [codesandbox/codesandbox-client#3042]
# 🐛 bug report

## Description of the problem
Hi Team!
I'm using CodeSandbox for several months now, it's a great tool to have some technical interview (candidates love this approach) and also for me to give some training remotely.
But since 2-3 weeks, when I activate the Live Coding session, when we modify a file and save it, the whole file is erase (file empty), and I cannot use Cmd + Z to cancel, neither if I reload the whole CodeSandbox, the file remains empty, with the small `dot` for unsaved file:
![image](https://user-images.githubusercontent.com/5469433/69043888-554a3280-0a0d-11ea-9ec3-c5d4729ef3af.png)
So the file is definitely lost.
For interview, I can handle it by asking candidate to not save the file when we deal with JavaScript files, but if we need to update `index.html` file, as we need to save it and refresh preview, it erases everything:
Before:
![image](https://user-images.githubusercontent.com/5469433/69043993-8f1b3900-0a0d-11ea-9c75-cba62b28ba1b.png)
After "saving":
![image](https://user-images.githubusercontent.com/5469433/69044012-9b06fb00-0a0d-11ea-9f3c-9d15deeb3b75.png)

If I close the Live Session (I copy the files in local, save the file (erasing), close the live session, and copy/paste files from local to CodeSandbox), I can save again the file without any issue.
Then, if I create a new live session, and modify/save the file, I lose everything again.

This issue happens no matter if we are using the `live` URL or the `owner` URL.

## How has this issue affected you? What are you trying to accomplish?
Well... I lose the whole file, and need to regenerate from the original copy in local or in GitHub manually.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1573738286-c05030adf
| Browser          | Chrome (saw this issue with different Browser)
| Operating System | Mac 10.13.6 (saw this issue with all kind of OS)

**Comment by pckilgore** [comment]
As much as I hate "me too" reports, I want to emphasize how reproducible (and frustrating!) this bug is.  It also occurs for me in a Create React App project (so it does not seem to be limited to certain environments), it emerged in the last two weeks (I hope this helps you intersect the appropriate commit) and it can be triggered by a user on either side of the pairing session.

I'd also like to point out that it occurs regardless of whether you save the file with the menu (File->Save) or use a keyboard shortcut (Ctrl+S).

Thank you so much for developing codesandbox, and please let me know I I can contribute more detailed logs to help you debug!

**Comment by MichaelDeBoey** [comment]
Fixed by #3046
