### ISSUE TITLE
CodeSandbox CI: Support Containers

### ISSUE THREAD

**Issue by CompuIves** [codesandbox/codesandbox-client#3052]
# 🌈 Feature

Support containers in CodeSandbox CI. It should already work, but it seems like there's one thing missing. I created this issue for people to follow progress on this.

**Comment by geelen** [comment]
Thanks @CompuIves!

For reference, I'm trying to use this on [fab-spec/fab](https://github.com/fab-spec/fab).

I have a container that I've manually got working against a recent CI-published version of `@fab/static` here: https://codesandbox.io/s/pensive-wildflower-bnipe

I've taken that container, forked it and removed references to anything FAB-related, then have added that new sandbox ID to the CI config: https://github.com/fab-spec/fab/pull/34/commits/d79d72a0b60d0a098d02517ceded0fbaac203cb7

But when I push a commit, I only get the one sandbox being created: https://ci.codesandbox.io/status/fab-spec/fab/pr/34/builds/2174

Hope this helps track down what's happening!

**Comment by CompuIves** [comment]
Thanks for all the info @geelen. I'll keep you posted on this!

> removed references to anything FAB-related

By the way, you don't have to remove the dependencies, we will overwrite the existing entries with the newly built versions if we find them 😄.

**Comment by geelen** [comment]
Ooh dank. Also, it's now working!

One other bug report, if you have `"packages": ["packages/*"]` in your config, CodeSandbox doesn't inject all the NPM dependencies. Switching that to...

```json
  "packages": [
    "packages/fab-compile",
    "packages/fab-static",
    "packages/fab-serve"
  ],
```
 
...fixed the issue. I tried removing `fab-compile` there, since it's only a dependency of `fab-static`, but then since the old version was still referenced in the `yarn.lock` file, it didn't update. So specifying all three packages did, in fact, work!

Super awesome work though, v excited to drive out the new API with this as a test harness <3

**Comment by lbogdan** [comment]
As far as I know, this has been implemented. @CompuIves can you please confirm and close?

**Comment by CompuIves** [comment]
Confirmed! 🎉
