### ISSUE TITLE
patron plan removed? being force redirected to $12 pro plan page

### ISSUE THREAD

**Issue by knksmith57** [codesandbox/codesandbox-client#3146]
# ❔ Question
Have [patron subscription options (`/patron`)](https://codesandbox.io/patron) been removed?

I tried signing up for a patron subscription today ($5 / month) to gain access to private sandboxes, but after the page loads, I'm immediately force redirected (client side) to the pro plan ($12 / month) [page (`/pro`)](https://codesandbox.io/pro).

I can confirm that the redirect happens regardless of whether or not I am logged in:
![2019-12-07 12 42 14](https://user-images.githubusercontent.com/796851/70379201-3265bc80-18ef-11ea-936f-fbd1f18ad3d1.gif)
![2019-12-07 12 46 13](https://user-images.githubusercontent.com/796851/70379220-a011e880-18ef-11ea-8fec-d6c9c329465f.gif)

Are pro plans the only way to gain access to create private sandboxes?

**Comment by MichaelDeBoey** [comment]
Since [Wednesday's announcement](https://codesandbox.io/post/hello-template-universe-goodbye-project-setup) of Template Universe and [not having any sandbox limits anymore](https://codesandbox.io/post/hello-template-universe-goodbye-project-setup#no-sandbox-limits), the `patron` subscription is rebranded to the `pro` subscription.
From now on, it's only possible to visit the `patron` page when you were already a `patron`.

I think all `patron`s are going to become `pro`s eventually, but not sure how the team has figured that out tho.
@CompuIves or @garethx can give some more info about that I think 🙂

**Comment by knksmith57** [comment]
thanks for following up, @MichaelDeBoey!

it'd definitely be great to get some input from @CompuIves or @garethx whenever y'all have a chance.

**Comment by garethx** [comment]
What Michael said is true, Pro has replaced the Patron plan. The /patron page exists just for existing subscribers, new users should use the /pro page. What's available in the pro plan is indicated on the pricing page at https://codesandbox.io/pricing, but it does include private sandboxes.
