### ISSUE TITLE
Code being duplicated in live mode

### ISSUE THREAD

**Issue by NikhilVerma** [codesandbox/codesandbox-client#3231]
# 🐛 bug report

## Description of the problem

1. Start a live editing session - Open Mode (Parcel + Vanilla JS)
2. Have a Javascript file around 100 lines
3. Invite 3 attendees to the live editing session
4. Ask the attendees to make changes in different locations (e.g. Person A copy pastes a line from line 10 to line 20, Person B changes something in the middle of the file, Person C updates the end of the file)

Expected Result: Editing goes smoothly
Actual Results: A huge content of the JS randomly gets duplicated, with no way to undo it. Everyone has to stop and then one person has to manually fix everything back.

## How has this issue affected you? What are you trying to accomplish?

I was trying to do an online interview, and a couple of people started typing together. And the entire file was ruined, random pieces of code got duplicated.

**Update:** I want to add that this is not a new issue, I faced this similar issue around half a year ago but didn't get around to creating a ticket for it. I assumed it was a one-off thing. So I just want to clarify that this is not a regression.

### Link to sandbox: [link]() (optional)

N/A

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Live version on 19 Dec 2019 3:42pm GMT|
| Browser          |79.0.3945.79 (Official Build) (64-bit) |
| Operating System |OSX Catalina 10.15.1 (19B88) |

**Comment by shiftyp** [comment]
Possibly related to my issue #3228

**Comment by CompuIves** [comment]
Ahhh hmmm, I thought we had fixed this specific issue with the last Overmind move. I think this happens because of singing of changes, where someone broadcasts the changes they've received. Let's say you have User A and User B, and this happens:

- User A sends "aa"
- User B applies "aa", but there's a race condition where User B is not only applying the code, but also sending "aa" to everyone else as a change

That's probably the issue, and might be because something happens asynchronously. I wonder if there is a better way to handle this. cc @christianalfoni

**Comment by andrasbacsai** [comment]
There were a lots of changes with the Live mode, so I think it's not relevant anymore.
Closing now. If you have any question, let us know!
