### ISSUE TITLE
Issue transpiling modules

### ISSUE THREAD

**Issue by Josema** [codesandbox/codesandbox-client#3360]
This example that I modified from a template never gets transpiled:
https://codesandbox.io/s/preact-10-op53p

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  PROD-1577119298-c52f70238
| Browser          | chrome and brave
| Operating System | windows 10

**Comment by garethx** [comment]
The linked example sandbox looks to have been removed or set as private, so I'm not able to look into the cause of the issue. If it's still an issue, please provide an updated link. Thanks

**Comment by Josema** [comment]
Can you see this one? https://codesandbox.io/s/young-thunder-j536n

**Comment by CompuIves** [comment]
I think I found the issue here. It seems like the sandbox is in an infinite loop, because of line 27: in that line the state is flipped on every render because of the function that's executed in `onClick` every time. Making the `onClick` an arrow function (`() => setDrawerOpened(!drawerOpened)`) should fix it.

**Comment by ChambreNoire** [comment]
Mine is stuck too : https://codesandbox.io/s/rq-pagination-issue-cyjfcy
