### ISSUE TITLE
logging to console delivers strange location

### ISSUE THREAD

**Issue by NickCarducci** [codesandbox/codesandbox-client#3488]
<img width="507" alt="Screen Shot 2020-02-08 at 10 11 24 AM" src="https://user-images.githubusercontent.com/12148373/74087553-6f6b3e00-4a5b-11ea-8050-6ae4839b9a9f.png">
# 🐛 bug report

## Description of the problem
All my console.log() print `vendors~app~embed~sandbox-startup.963c66368.chunk.js:1` instead of location

## How has this issue affected you? What are you trying to accomplish?
I need to see location for my logs to debug

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome v.80.0.3987.87
| Operating System | MacOS v.10.15.3

Sorry if this isn't a bug and I messed something up in chrome settings, or something

**Comment by garethx** [comment]
The `vendors~app~embed~sandbox-startup.963c66368.chunk.js:1` bit is devtools telling you the file that's producing the logging, it's not the output of the logging itself.

**Comment by NickCarducci** [comment]
how can I show it, should I ask chrome devtools?

**Comment by garethx** [comment]
It looks like it already is being shown - the output before the file name e.g. outputs like 'New York City' and [40.71427, -74.00597] (GPS coordinates for new york) are what you're console logging.

**Comment by NickCarducci** [comment]
Oh I'm sorry I used to be able to see the line it is logging from in my code..

**Comment by garethx** [comment]
So by location you're meaning the whereabouts of the console.log in your code and not the location data you're logging? The number after the colon and filename in the output above is the line number. In this case, line 1. Since your script is being bundled and minified that's not a helpful reference. I find it useful to prepend a unique identifier to the output I'm logging so I know which console.log statement it's coming from e.g. `console.log("in function init: ", location)`. This is also useful for understanding the order in which code is being executed.

**Comment by NickCarducci** [comment]
I'll do that thanks
