### ISSUE TITLE
ModuleNotFoundError Could not find module in path

### ISSUE THREAD

**Issue by moroshko** [codesandbox/codesandbox-client#3507]
Locally, running with a fresh new Create React App everything works as expected.

In CodeSandbox, however, I get:

> ModuleNotFoundError
Could not find module in path: 'basis/dist/icons/arrow-back' relative to '/node_modules/basis/dist/components/Icon.js'

https://codesandbox.io/s/compassionate-surf-orpco

Any ideas?

(btw, is there a way in CodeSandbox to browse `node_modules`?)

**Comment by CompuIves** [comment]
Ah, yes, a tricky one. This line:

`  var IconComponent = require("../icons/".concat(name))["default"];`

Confuses our dependency resolver, since it's a dynamic require. I think we did support glob requires, but something might've gone wrong. Checking now...

> (btw, is there a way in CodeSandbox to browse node_modules?)

Yes, in the devtools you can find all executed files. Another way is to check `manager.transpiledModules` on the sandbox window!

**Comment by moroshko** [comment]
Thanks @CompuIves for looking into this!

Is there is any other way to write the dynamic require that CodeSandbox can understand (as a temporary workaround until this gets fixed)?
