### ISSUE TITLE
Error creating sandbox from git repository -- something went wrong

### ISSUE THREAD

**Issue by pkt4lli** [codesandbox/codesandbox-client#3741]
# 🐛 **something went wrong**

## Description of the problem
Getting back to coding after 15 yrs, to consider me a fresher. First timer with web programming.

Just started with [this book](https://www.newline.co/fullstack-react/) on React, and just uploaded their sample code as-is to github [here](https://github.com/pkt4lli/time_tracking_app). Then signed up on codesandbox using same git account.

But when I tried creating a sandbox from Git, I get this --
![sandbox_err](https://user-images.githubusercontent.com/62469347/77306574-e1eb6100-6d1d-11ea-887f-bf72b265b66a.png)

## How has this issue affected you? What are you trying to accomplish?
Trying to get started with web programming on codesandbox.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 
| Browser          | Opera
| Operating System | Windows 10

**Comment by Developerayo** [comment]
You are trying to import a repo from a private organization? @pkt4lli

**Comment by garethx** [comment]
@pkt4lli The repo fails to import due to it going over our 500 file limit. That looks mainly like it's caused because you've included the node_modules folder in the repo. It's not necessary to have the node_modules folder in the repo as it's created when your project is being set up. Try removing the folder and trying to import again.
