### ISSUE TITLE
:lock: - Lock Sandbox (from yourself)

### ISSUE THREAD

**Issue by styk-tv** [codesandbox/codesandbox-client#3743]
# 🌈 Feature

I have been more and more spending insane amount of time on your site. Above all: thank you!

Maybe this is buried somewhere in the documentation already, if not please consider the following.

<img width="456" alt="Screenshot 2020-03-23 at 19 44 51" src="https://user-images.githubusercontent.com/838921/77356751-d2304480-6d3e-11ea-8df3-d1a0a822a3ad.png">

That empty space next to the Like button. Would be great to have a :lock: lock next to it so you can lock a sandbox from yourself. I work a long time sometimes to figure something out, then i usually want to lock > fork a sandbox so i can continue but leave one in previous locked state. 

You will probably argue this is what github is for and you're probably right, but I think use cases are different, quick lock would prevent me form editing wrong one if i have two, or creating a fork if i have no working copy. Only when my new feature is fully developed in want to push the code in.

Thoughts?

**Comment by SaraVieira** [comment]
Hey!

I think we already have what you are looking for and we called it frozen and you can find it here:
![Screenshot_20200323-220259](https://user-images.githubusercontent.com/1051509/77362936-1d078780-6d52-11ea-86a0-4df6252a970f.jpg)

If the toggle is on you will not be able to save and it will be forked on save so you can keep your original sandbox untouched and keep a new version 


This was actually the first feature I built on CodeSandbox because I kept fucking up workshop starter files

**Comment by styk-tv** [comment]
@SaraVieira hahaha :) thank you very much for sending this. i will use it all the time. would be really great to have this in bunch of other locations like maybe at the top or on the lists or even sorting by which ones are locked etc, just something to think about for the future.

I will leave it open, but feel free to close if polluting. Again, many thanks.

**Comment by SaraVieira** [comment]
Hey!

I will leave this open as these are good visual ideas 

We will redesign the dashboard soon and this will be a really good addition and also I will think about some place in the header to show it's locked

Maybe in the name would be visible but not too much after the icon where it says public do the same thing for locked 

Thank you for doing the update! Helps a lot in making the product better
