### ISSUE TITLE
Codesandbox define API request need redirect

### ISSUE THREAD

**Issue by Rustin-Liu** [codesandbox/codesandbox-client#3769]
# 🐛 bug report
Codesandbox define API need redirect.
## Description of the problem
https://github.com/ant-design/ant-design/issues/22636
## How has this issue affected you? What are you trying to accomplish?
https://github.com/ant-design/ant-design/issues/22636
### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/define-api-post-request-qzlp7nw34q?from-embed
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  1.1.13
| Browser          | chrome Version 80.0.3987.149 (Official Build) (64-bit)
| Operating System | mac os 10.15.3

**Comment by garethx** [comment]
I'm not clear from the linked issue what it is you're requesting. You can already get the ID of a generated sandbox which you can use to create a redirect, see https://codesandbox.io/docs/importing#define-without-render

**Comment by karlhorky** [comment]
I'm running into this too (just noticed it since a few days). This causes a "redirect" link on `iframe`s using a `src` with `define`:

**Sandbox:** https://codesandbox.io/s/define-api-get-request-00f4f

![Screen Shot 2020-03-31 at 16 21 31](https://user-images.githubusercontent.com/1935696/78037472-e510cd80-736b-11ea-9448-df5b269d3696.png)

---

This causes solutions using things similar to [`gatsby-remark-embedded-codesandbox`](https://github.com/elboman/gatsby-remark-embedded-codesandbox/) to fail.

**Comment by CompuIves** [comment]
Looking into this now...

**Comment by CompuIves** [comment]
It should work as expected now again, I'm sorry for the inconvenience! This was a regression due to a recent CORS change.

**Comment by karlhorky** [comment]
Wow so fast Ives! 🚀💯 Looks good, back to normal! :)

@Rustin-Liu is it back to normal for you too?

**Comment by Rustin-Liu** [comment]
@karlhorky  @CompuIves  @garethx  Thank for your supporting, it's working now.
