### ISSUE TITLE
Export package-lock.json when pushing to github/etc

### ISSUE THREAD

**Issue by tjlav5** [codesandbox/codesandbox-client#3889]
# 🌈 Feature

When I add my dependencies, CSB updates `package.json`, but can we add the corresponding lock? e.g. Is it possible to expose the `package-lock.json` or `yarn.lock` when committing to github? 

I don't necessarily think this necessarily needs to work in an individual sandbox (when not exporting), but at a minimum I would like to be able to check my lock file into version-control.

**Comment by andrasbacsai** [comment]
@CompuIves What do you think? I think adding lock file to version-control would be really useful!

**Comment by SaraVieira** [comment]
Hey!

Unfortunately, this is not really possible at least for now since we don't use yarn/npm to install packages in the client sandboxes we use our own packager that gets the files from unpkg and therefore no lock file is ever created 


Will add this to our backlog for container sandboxes.

I will be closing but to make sure what we have in GitHub is just issues and all our feature requests are tracked in our roadmap.
