### ISSUE TITLE
Template Missing from Dashboard

### ISSUE THREAD

**Issue by ttseng** [codesandbox/codesandbox-client#3891]
# 🐛 bug report

## Description of the problem
I have a template that is connected with a private Github repo.  While the template was created as an imported project from Github, it does not appear as a template or a project on my dashboard.

![image](https://user-images.githubusercontent.com/519336/79194526-ae58ae00-7e67-11ea-943f-17de2dfeca39.png)

## How has this issue affected you? What are you trying to accomplish?
I bookmarked my template manually in my browser, but if I hadn't, there would have been no way for me to get back to the main project I'm working on.

**Comment by garethx** [comment]
Technically this isn't a bug, is as much as it is the expected way imported projects work at the moment (currently only templates created from sandboxes appear in the Templates section). However, I'll keep this open as it's not intuitive, and I think it's more a relic from how things used to work before imports were treated as templates, which has since evolved in the editor but the way we handle them on the dashboard hasn't.

**Comment by ttseng** [comment]
If this is the expected behavior, then how is a user expected to find their imported project?

**Comment by garethx** [comment]
You're able to use the bookmark template option which makes it available from the create sandbox modal, and/or fork the template creating a sandbox which is available in the dashboard. But to reiterate the above, this is not intuitive and needs to be re-worked.

**Comment by cyberbiont** [comment]
Forked templates lose their synchronization with GitHub repo (i.e. they are not updated anymore if I push changes to GitHub from a local repo copy, for example). So it is not an option.
As for the bookmarking, I cannot bookmark the template that I created myself.

**Comment by garethx** [comment]
This is now fixed by the Repositories tab in the dashboard, which lists imported GitHub repos: see https://codesandbox.io/dashboard/repositories
