### ISSUE TITLE
How to change errors language?

### ISSUE THREAD

**Issue by OnkelTem** [codesandbox/codesandbox-client#3923]
I cannot change the language, it's stuck to some randon nonsense. 
I've searched throught the Preferences but found nothing.
The cookies have been deleted several times, but it didn't help.
Logged out and logged in back with no result too.

I just want my messages to be in ENGLISH. 

P.S. I should also note, that the UI font used by messages is damaged, as it shows letters in different language in a wrong way: it uses a bigger font size and it looks pretty ugly.

**Comment by OnkelTem** [comment]
Hello? Is it so complicated to just switch language?

**Comment by SaraVieira** [comment]
Hey! 

You seem to have the configuration of your browser in a different language for some reason, I just checked and this happens in my wife's computer since she has Firefox in Spanish 
![IMG-20200419-WA0000](https://user-images.githubusercontent.com/1051509/79686372-2a743c80-8240-11ea-8885-564f2e3b0a91.jpg)


There is a way to fix it: go on your user settings (cmd+shift+p) and look for this 
![IMG-20200419-WA0001](https://user-images.githubusercontent.com/1051509/79686385-3fe96680-8240-11ea-8b07-5e0e44f86abe.jpg)

This will set the default errors in ts to English

**Comment by SaraVieira** [comment]
Also please don't call other languages randon nonsense, that's people's language 

We do have an issue with the font where it doesn't support cyrlic characters so it shows different

**Comment by OnkelTem** [comment]
> There is a way to fix it: go on your user settings (cmd+shift+p) and look for this

Thank you very much, it works now!

> Also please don't call other languages randon nonsense, that's people's language

Well I didn't mean something offensive, I just stated that from my point of view it was picked by a random. Because I have several languages in my browser and English is the main one - or at least it was on the top. Then after I made *it* the language I want other languages to be translated on, killed cookies and relogged-in, nothing has really changed.

> We do have an issue with the font where it doesn't support cyrlic characters so it shows different

Btw, Microsoft Teams has exactly same issues with fonts. Coincidence? And they don't provide also no way to change this. So you're stuck to an ugly font and have to use it. 

It looks like you've also been in some way forced to use this font. Because you see - neither of Linux' or Droid's fronts have been experiencing this sort of problem for decades so far. So it's pretty strange: why among miridans of fonts working well for the most languages was picked a font which has such an ugly issue with the language of the biggest nation in Europe? Just curious :)

**Comment by SaraVieira** [comment]
Honestly about the language you are completely right, we should definitely support cyrlic and weirder the font was also made in Europe.

To be honest we just didn't have time to find a new font to be the main one, you can also change it in the settings even though we do have a problem with getting people to even find the settings :/

I may push for https://www.jetbrains.com/lp/mono/#font-family as it's open source and does support more 

The saddest thing is that I was only made aware of this when I did a workshop in Ukraine and was like wtf?

I don't believe we use the same font as Microsoft teams we use https://dank.sh but as devs based in Europe it is our responsibility to fix this and I will take this on next week

**Comment by MichaelDeBoey** [comment]
I've been using Jetbrains Mono since it was released and I really love it.
It takes a little to get 100% used to it, but It's just the best standard WebStorm font I've ever had.
Haven't tried other fonts but the standard ones tho.

I agree that as a company based in The Netherlands, the default font should support all possible European characters (or as much as possible at least).
