### ISSUE TITLE
Edited files are not showing to create PR. It showing Fetching Changes... only

### ISSUE THREAD

**Issue by bhuvaneswari-bit** [codesandbox/codesandbox-client#4005]
# 🐛 bug report

## Description of the problem
Edited files are not showing to create PR. It showing like Fetching Changes...

## How has this issue affected you? What are you trying to accomplish?
I have created blog site through GatsBy and deployed it through Netlify. After deployment completed I copied my repo link and imported project and generated the CodeSandBox. After make changes in the files, the edited files are not listing down to create PR.

![image](https://user-images.githubusercontent.com/36919519/80513527-ce768a00-899c-11ea-9cce-c1f28c47c7a3.png)

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrom
| Operating System |  Windows 10

**Comment by garethx** [comment]
Do you see a 'request entity too large' error in the browser devtools console? If so, try https://codesandbox.io/docs/faqs#im-getting-a-request-entity-too-large-error-what-should-i-do and let us know if you're still having problems. If you are, please provide a link to the sandbox you're editing so that we can take a closer look. If it's private, then please make it unlisted and provide the link in an email to us at hello@codesandbox.io referencing this issue. Thanks.

**Comment by garethx** [comment]
Can you try it again? We've made some changes, which will hopefully have resolved this. Thanks.
