### ISSUE TITLE
Store preferences server side.

### ISSUE THREAD

**Issue by ryanpcmcquen** [codesandbox/codesandbox-client#405]
That way they will persist from machine to machine. This would be a nice user experience.

**Comment by CompuIves** [comment]
Thinking of making a CodeSandbox specific config file, like vscode does, that's tied per user. Then our UI can generate the config, or the users can share it by copying and pasting.

**Comment by mindplay-dk** [comment]
The settings UI distinguishes between "User Settings" and "Workspace Settings".

Wouldn't it make sense for "User Settings" to be saved to my user account?

And "Workspace Settings" to be saved to the project sandbox?

(For some reason, the app locks up for me a lot lately, and I have to clear the application cache - every time, I lose all my user settings, colors, etc... since prettier gets enabled by default,  all my source-formatting gets smashed whenever this happens, and since there's no git history, I have to manually clean up everything... It would be really helpful if user settings were saved to my account.)

**Comment by ryanpcmcquen** [comment]
Any progress here?

**Comment by Explosion-Scratch** [comment]
Bump!!!! Please do this!

**Comment by SaraVieira** [comment]
Hey,

Sorry I have added this to the backlog and we are scoping how to do this but it is on a high priority right now as it is a super requested feature.

I will close this since it is in our backlog and we are working from there and in here it gets lost, been doing this to feature requests to make sure we have everything in only one place to requests.

Will also work on making this backlog public 

Thank you!

When it is merged this issue is linked and I will say it here and probably make an announcment

**Comment by SaraVieira** [comment]
A first draft of this has been merged today 🎉

Christmas present I guess?

You now have a tab on your settings called preferences profiles where you can save your preferences 🎉🎉🎉
