### ISSUE TITLE
Codesandbox isn't allowed CORS ( HTTPS req ) from new Starwars  (swapi.dev) Api DJANGO . Maybe someone ask them? : ) 

### ISSUE THREAD

**Issue by stephyswe** [codesandbox/codesandbox-client#4064]
# 🐛 bug report

## Description of the problem
21,000 codesandboxes* was just rendered useless.
* = https://codesandbox.io/search?query=swapi&page=1&configure%5BhitsPerPage%5D=12
WHY?
API swapi.co was removed and replacement API swapi.dev isn't allowed to make HTTPS request on Codesandbox. Located the error in my own sandbox,, but playing around with others too. The same network issue occur in each of them. 

Just wanted to let you know this.

Kind regards,
Stephanie

### Error Message in Console
Mixed Content: The page at 'https://xxx.csb.app/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://swapi.dev/api/films/'. This request has been blocked; the content must be served over HTTPS.

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by lbogdan** [comment]
It works here: https://codesandbox.io/s/simple-vue-template-5gdqr?file=/src/App.vue . Actually, I had the same issue when leaving out the trailing `/`, because then it redirected me to the URL with added trailing slash (so from `https://swapi.dev/api/films` to `http://swapi.dev/api/films/`), but over `http` instead of `https` (which is most probably a bug on their side).

Closing this, as there's no other actionable here.
