### ISSUE TITLE
Closing sandbox without saving saves the content.

### ISSUE THREAD

**Issue by deadcoder0904** [codesandbox/codesandbox-client#4110]
# 🐛 bug report

## Description of the problem

I have a Codesandbox where I have a `Hello World` React app. Now I edit the content to be `Hell World` to share with a friend & I don't wanna save it. So I never click `Save`. I click on `Close Tab` but it automatically saves the content. This loses my original content.

## How has this issue affected you? What are you trying to accomplish?

This happened just now as I was answering a StackOverflow question which was a little modification of a Sandbox I earlier made. So I made the necessary changes to the file, got the expected answer to the question & copy-pasted the answer. Then I clicked close on Sandbox so that my earlier Sandbox content remained but it didn't happen. Instead it overridden it with the new answer that I created for StackOverflow.

This shouldn't be the case. It should be the same as text editors like VSCode where it asks whether to close without saving or not :)

**Comment by garethx** [comment]
I can reproduce the outcome of this, but your description doesn't seem strictly accurate and I don't agree it's a bug. In my tests at least, the change isn't actually saved, but it is applied to the preview if you have 'preview on edit' enabled. So if you leave/reload you're notified that changes might not be saved, but even if you reload, you still see the change in the preview because un-saved changes are retained and thus the edit is applied. Note though that the file still have its un-saved indicator because the change hasn't been saved yet. You can opt to discard changes at any time and revert the content and thus the preview. This behaviour seems consistent with the user's settings. Are you seeing something else?

**Comment by deadcoder0904** [comment]
I expect Codesandbox to work like other text editors by default. 

Like ask me to save the file if I close it without saving. That's why there is an unsave indicator (dot ⚫ i guess instead of close ✖ on the file). So it's definitely a bug to me.

**Comment by garethx** [comment]
It already alerts you to unsaved changes. So you'd prefer an option to discard changes instead?

**Comment by deadcoder0904** [comment]
Weird when I tried, it didn't alert the first time.

Second time I saw it turned the dot ⚫ into close ✖ even after I clicked close. Meaning first it was dot (unsaved state) then i clicked it to close tab (which should just discard) but it automatically removed the dot (became saved state) so i lost my edit.

Meaning my 1st time & 2nd time are both same but I didn't notice the 1st time that it will lose my content because I assumed it worked like VSCode.

But yeah I guess discarding changes when I dont save should be the default one.

**Comment by garethx** [comment]
I'll try and reproduce this. Can you confirm your browser version and OS. Thanks.

**Comment by deadcoder0904** [comment]
Thought I didn't need to so I removed it.

Here they are:

- Google Chrome Version 81.0.4044.138 (Official Build) (64-bit)
- Windows 10

**Comment by CompuIves** [comment]
I think I was able to reproduce it. This seems to happen when you navigate from the editor to another page within the application (eg. codesandbox.io/dashboard). If you navigate to eg. google.com it doesn't happen.

I think this is related to how we break down VSCode when going to another page. VSCode thinks we're closing all files and thus saves everything. We should find a way to let VSCode know that we're actually not closing the tabs.
