### ISSUE TITLE
Vue import is undefined

### ISSUE THREAD

**Issue by davestewart** [codesandbox/codesandbox-client#4145]
# 🐛 bug report

## Description of the problem

A standard import is not working:

```js
import Vue from 'vue'
console.log({ Vue })
```
```
Object {Vue: undefined}
```

## How has this issue affected you? What are you trying to accomplish?

Trying to test a new new library. Not sure if the bundling of the imported library is affecting it.

Tried just importing the library in another sandbox and it worked, but a Typescript version of the working JS module couldn't find it. 

### Link to sandbox: [link]() (optional)

Main CS I want to get working:

https://codesandbox.io/s/charming-framework-5wcx1?file=/src/index.ts

Smaller CS to try and isolate the problem:

https://codesandbox.io/s/vue-class-store-new-install-demo-cumo7?file=/src/App.vue

Link to library I am trying to test:

https://github.com/davestewart/vue-class-store

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | online
| Browser          | Chrome latest
| Operating System | Mac OSX

**Comment by andrasbacsai** [comment]
I think you cannot use vue-cli template with the Poi bundler, as the vue-cli template will always start the app with the template's default start script (`vue-cli-service serve` in this case).

If you would like to use Poi, you need to use the [node template](https://codesandbox.io/s/node). 

Here is an example (I only added your Demo.vue to this sandbox):

https://codesandbox.io/s/green-sunset-75nm8

(If it's possible, do not use npx in the start script, because it will fetch all required modules every time. I've added Poi as devDependencies)

**Comment by davestewart** [comment]
Hey, thanks! I'll take a look

**Comment by davestewart** [comment]
OK, this is a new Vue CLI project, and have some absolute craziness going on.

https://codesandbox.io/s/currying-silence-lp7c5?file=/src/main.ts

```
Vue is undefined
```

I guess CS has to handle a lot more complexity, but whereas it used to be flawless, these days I can rarely get it to work.

Any ideas?

**Comment by CompuIves** [comment]
Ah, I think that this is a TypeScript issue. It seems to work when changing
```
import Vue from 'vue';
```

to 
```
import * as Vue from 'vue';
```

But I'm not sure if this makes sense from the config. I thought that `allowSyntheticDefaultImports` would allow you to run `import Vue from 'vue';`. I'll check whether the config is read properly!

**Comment by davestewart** [comment]
Nice one Ives!

Yeah, this is a vanilla Vue CLI setup.

In this project, I migrated from Egoist's amazing Poi because it wasn't working, so it would be good to iron out whether his library was not at fault here too :)

**Comment by davestewart** [comment]
OK, I tried `import * as Vue from 'vue'` but that didn't work either.

**Comment by CompuIves** [comment]
I might have found what's causing it, I think that we ignored the tsconfig.json until now. Created a test PR to see if this fixes it...

**Comment by davestewart** [comment]
Surprising that I am the only one to come across this?

**Comment by CompuIves** [comment]
Yeah, I think that this is the first one with a custom tsconfig that's reported. Maybe most people gave up when they saw the issue? I can confirm that this fixes it. I stumbled upon two other problems still, first one is that it couldn't resolve `tslib`, that's because we don't install `devDepndencies` by default. I'm working on a fix for this by detecting dynamically which dependencies are used. The second issue is related to how files are resolved, it for some reason resolves in the `vuex/store` example when importing from `vuex` to the actual example. I need to look into why the path is resolved that way, maybe related to `tsconfig.json`.

I will merge this fix first at least!

**Comment by CompuIves** [comment]
Keeping this open until all issues are resolved :).

**Comment by davestewart** [comment]
Well, I'm glad to be able to find these edge cases for you!

Your fixes will make CS more robust :)
