### ISSUE TITLE
Duplicate File

### ISSUE THREAD

**Issue by deadcoder0904** [codesandbox/codesandbox-client#4246]
# 🌈 Feature

Would love to have a duplicate file option in Codesandbox.

Currently only **Rename** & **Delete** is there on right-click.

**Comment by SaraVieira** [comment]
Hey

I would like to point out there is no option to duplicate a file on VScode, that is a plugin in my case

**Comment by deadcoder0904** [comment]
Sure, but I think it should be a core feature but your call :)

**Comment by SaraVieira** [comment]
Makes perfect sense. Just changed the description and gonna remove the stale label as I also would love to see this

**Comment by sladyn98** [comment]
@SaraVieira I would like to contribute to this feature. Any tips on getting started

**Comment by SaraVieira** [comment]
Hey

It's weirdly so much harder than it looks, I banged my head for hours a couple of months ago :/

I am gonna close this but I just added to our internal backlog where it will have more visibility and I definitely still want this, basically everyday

Hope this makes sense, when all the features are over in our backlog I will work on making a page with all of these so that our community backlog is public
