### ISSUE TITLE
Malware Warning (Malicious Website Suspected) LinkedIn

### ISSUE THREAD

**Issue by danieldanielecki** [codesandbox/codesandbox-client#4257]
Similarly to GitHub/GitLab etc. profiles sometimes we put link to our profile at CodeSandbox. Unfortunately, for some reason LinkedIn marks this as malicious website. It would be a good idea to check out with them what's the problem. Screenshot below.

<img width="1088" alt="malicious" src="https://user-images.githubusercontent.com/12736263/83349572-286cc580-a336-11ea-9258-36ff53d0196b.png">

**Comment by CodeSandboxNotifications** [comment]
Hello,


This should have been resolved by removal from the Spamhaus DBL database as of yesterday. Could you please confirm?


Kind regards,

Regards,
Oskar van Eeden

--- original message ---
On May 31, 2020, 12:01 PM GMT+2 notifications@github.com wrote:



Similarly to GitHub/GitLab etc. profiles sometimes we put link to our profile at CodeSandbox. Unfortunately, for some reason LinkedIn marks this as malicious website. It would be a good idea to check out with them what's the problem. Screenshot below.


—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by oskarabc** [comment]
This should have been resolved per our removal from Spamhaus DBL registry per yesterday. Could you please confirm this has been resolved @danieldanielecki?

**Comment by danieldanielecki** [comment]
@oskarabc yes, this is no longer happening. Therefore, closing this issue.

**Comment by Bapu921112** [comment]
Hi @oskarabc 

I have facing same kind of issue (malicious website suspected) with my email Id's. When we are sharing my ID on Linkedin than given url has generating. Can you let me know, how we can solve this issue? 

https://www.linkedin.com/redir/general-malware-page?url=sagar%40pharmazon%2eltd

Thanks
Sagar - [Phamazon](https://pharmazondirect.com/)

**Comment by oskarabc** [comment]
@Bapu921112 Looks like you're trying to share email addresses via linkedin and not a CodeSandbox domain (either csb.app or codesandbox.io): Can you please share the link to the sandbox? We're currently not listed in the Spamhaus DBL, so CodeSandbox domains should be able to be shared on LinkedIN without warnings.

**Comment by samiam1247** [comment]
![image](https://user-images.githubusercontent.com/87391191/125511228-a9fd7d35-5fee-4fac-8e26-e57eeef67a07.png)
I am getting this error, please help me

**Comment by CodeSandboxTeam** [comment]
This doesn't seem like its scanning or detecting codesandbox.io, can you please provide a sandbox link or some more context? Currently we're not blocklisted in any of the known databases afaik. Happy to help, –Oskar



--- original message ---
On July 13, 2021, 9:11 PM GMT+2 ***@***.*** wrote:




I am getting this error, please help me

—

You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by babson89** [comment]
Hello, 
I am trying to add my portfolio website on linkedin and I am getting the same error.
can you please help me ?
![linkedin](https://user-images.githubusercontent.com/54966085/126389067-c35f1c10-7b8d-475c-b1c8-826ceede5ece.png)

**Comment by markpenguinstrategies** [comment]
how do we fix this? https://www.linkedin.com/redir/general-malware-page?url=https%3A%2F%2Fwww%2esony-semicon%2eco%2ejp%2Fe%2Fnews%2F2021%2F2021092901%2ehtml

**Comment by ahnaf-tahmid-chowdhury** [comment]
I have the same problem. I am unable to access my portfolio website. And I don't know how to fix this. My website is: [https://tahmid.pages.dev/](https://tahmid.pages.dev/)
Whenever I try to go through linkedin, it redirect me to the following page: [https://www.linkedin.com/redir/redirect?url=https%3A%2F%2Ftahmid%2Epages%2Edev%2F&urlhash=3uuW&trk=public_profile-settings_website](https://www.linkedin.com/redir/redirect?url=https%3A%2F%2Ftahmid%2Epages%2Edev%2F&urlhash=3uuW&trk=public_profile-settings_website)

**Comment by Vipin-himflax** [comment]
Hi @oskarabc , Greetings .
Could you please assist me with the same kind of issue. My company url is www.himflax.com but whenever someone post any e-mail or website domain on linkedin then it is getting converted into some other link by  linkedin: https://www.linkedin.com/redir/general-malware-page?url=himflax%2ecom . Could you please help me ? 

![image](https://user-images.githubusercontent.com/81432793/147097733-95a614ff-75a1-455c-a6f4-d38636690026.png)
![Capture](https://user-images.githubusercontent.com/81432793/147097765-f5a40e7a-e232-4ce7-a27c-d366fce7c473.JPG)

**Comment by oskarabc** [comment]
Hey Vipin, 


Unfortunately, we don't have any control or ability to change how Linkedin processes links - It may be best to contact their support about this and see if they have a solution? 

—
James
Support
CodeSandbox.io

--- original message ---
On December 22, 2021, 1:09 PM GMT ***@***.*** wrote:



Hi @oskarabc , Greetings .

Could you please assist me with the same kind of issue. My company url is www.himflax.com but whenever someone post any e-mail or website domain on linkedin then it is getting converted into some other link by linkedin: https://www.linkedin.com/redir/general-malware-page?url=himflax%2ecom . Could you please help me ?



—

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---

**Comment by ibrahim119** [comment]
![image](https://user-images.githubusercontent.com/111316689/184716026-632b410a-356c-43ec-9a9d-e82f2b14be89.png)
I have the same problem

**Comment by ibrahim119** [comment]
![Untitled](https://user-images.githubusercontent.com/111316689/184716232-69032c58-4ef7-45ce-8150-812aa8a8fbd3.png)
I have the same problem with my company domain

**Comment by NibeluR** [comment]
same issue here. Stupid linkedin tags my pages.dev as malicious....

**Comment by ZarantechMarketing** [comment]
Hi @oskarabc we are facing the same issue on our company site,

Please find the doc which specifies the same, https://docs.google.com/document/d/1buhztAlPkHY7Fk1o_BK7FjZbPVD-cBvSuNs-wYRT7hE/edit

Following is the screenshot:

[https://www.linkedin.com/redir/general-malware-page?url=info%40zarantech%2ecom](https://www.linkedin.com/redir/general-malware-page?url=info%40zarantech%2ecom)

[WhatsApp Image 2022-09-22 at 18 58 08 (1)]

(https://user-images.githubusercontent.com/110378799/192151790-1c0d3c75-4c34-497e-9a61-e4da4efcaf70.jpeg)

I contacted AWS (where our site is hosted) and got this response....

I contacted our Email Marketing specialist and they checked for the Malicious website thing and this is the response we got

Please help me to get this resolved

**Comment by claudiomoramarco** [comment]
hi, i have the same problem here! Please someone could help me?
https://www.linkedin.com/redir/general-malware-page?url=http%3A%2F%2Fwww%2edetergo%2eeu 
![image](https://user-images.githubusercontent.com/75493295/229069669-cddb4e12-3a28-4f45-a194-82175fd8f7cd.png)

**Comment by ajinendra05** [comment]
https://www.linkedin.com/redir/general-malware-page?url=https%3A%2F%2Fajinendra05%2e42web%2eio%2F&lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base%3BMcQRP8dYStOVIrM9SbtyrQ%3D%3D

![image](https://github.com/codesandbox/codesandbox-client/assets/92153036/b83f2c3a-d4cb-4a01-b8fa-21dc0098c1fd)


Hey @oskarabc I also get same problem can you help me out.

**Comment by milad145** [comment]
hello every one
you can change your url by URL SHORTENER sites like 
https://free-url-shortener.rb.gy
or you can use another sites

**Comment by AmonKissi** [comment]
Going through the same issue in 2024. First time this is happening.

https://www.brstore.us

https://www.linkedin.com/company/bandr/

There is not actual solution for this?

**Comment by VIgyaniv** [comment]
![image](https://github.com/codesandbox/codesandbox-client/assets/165822482/f3f5328d-f45e-4edb-bcdd-898801a64d06)
