### ISSUE TITLE
Tests Tab do not work on Firefox

### ISSUE THREAD

**Issue by silviubogan** [codesandbox/codesandbox-client#4303]
# 🐛 bug report

## Description of the problem
The browser page with the sandbox is blocked. I can close the page, or click a button to stop the script forcefully, but it is not ideal.

## How has this issue affected you? What are you trying to accomplish?
I was trying to see if the tests in the Tests tab are passed or not.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | The latest version in codesandbox.io as of 03.06.2020
| Browser          | Firefox 76.0.1 (64 de biți) (Ubuntu version)
| Operating System | Ubuntu 20.04

**Comment by CodeSandboxNotifications** [comment]
Hi Silviu,


Just to make sure I understand the issue. You have a sandbox where you run a script that blocks the browser? 


You can add "?runonclick=1" to the url of your Sandbox, to prevent it from running immediately. 


Does this solve the issue or you?


Best regards
Christian



--- original message ---
On June 3, 2020, 2:07 PM GMT+2 notifications@github.com wrote:



🐛 bug report

Description of the problem

The browser page with the sandbox is blocked. I can close the page, or click a button to stop the script forcefully, but it is not ideal.

How has this issue affected you? What are you trying to accomplish?

I was trying to see if the tests in the Tests tab are passed or not.

Link to sandbox: link

Your Environment
Software Name/Version 
Сodesandbox The latest version in codesandbox.io as of 03.06.2020 
Browser Firefox 76.0.1 (64 de biți) (Ubuntu version) 
Operating System Ubuntu 20.04 


—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by silviubogan** [comment]
Hello!

Many things might have changed since I posted this issue, but currently this is the situation.

When switching to the Tests tab of the sidebar on the right, I see this:

![image](https://user-images.githubusercontent.com/198924/92256925-0e1a2900-eedd-11ea-8338-2db05b2b5688.png)

The browser does not crash but the tests are not run. The loading indicator for tests shows up and stays there indefinitely.

Thank you.

**Comment by CompuIves** [comment]
Ah, I think this is because in Firefox `Error.captureStacktrace` is not available. Jest uses this function to determine where the error happens. I thought we had added it as a polyfill with `error-polyfill`, but it seems like it doesn't work 100%.

**Comment by christianalfoni** [comment]
This the error I am getting when opening the tab in Firefox:

![Screenshot 2020-09-09 at 10 20 14](https://user-images.githubusercontent.com/3956929/92573418-0e704680-f286-11ea-93a0-b914d29ac5b5.png)

**Comment by ryanpcmcquen** [comment]
I'm getting bit by this bug again on Firefox 83 and Brave (Chromium) 86.

**Comment by SaraVieira** [comment]
Hey

This is a different thing, a bug was created by @ryanpcmcquen
