### ISSUE TITLE
Implicitly installed DefinitelTyped types take over "builtin" ones

### ISSUE THREAD

**Issue by Andarist** [codesandbox/codesandbox-client#4307]
# 🐛 bug report

## Description of the problem

Previous versions of the `react-textarea-autosize` package were not written using TypeScript so DefinitelyTyped community has created their `@types/react-textarea-autosize`. However, recently published `react-textarea-autosize@8` has been rewritten to TS and naturally it ships its own type definitions now.

Problem is that CodeSandbox is still using `@types/react-textarea-autosize` over the builtin types, even though they have not been installed explicitly:
![screencast 2020-06-03 18-09-37-2](https://user-images.githubusercontent.com/9800850/83661071-ece82a80-a5c5-11ea-9b2e-0217fcf7faf2.gif)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | latest (?)
| Browser          | latest Chrome 
| Operating System | OSX

**Comment by CodeSandboxNotifications** [comment]
Hi there and thanks for reporting the problem!


We automatically download types from @types if they exist. We are in a discussion now on how we can detect if the package has internal typing, so that we avoid trying to grab types from the @types project. I will keep you posted when we have a solution 




Best regards
Christian



--- original message ---
On June 3, 2020, 6:14 PM GMT+2 notifications@github.com wrote:



🐛 bug report

Description of the problem

Previous versions of the react-textarea-autosize package were not written using TypeScript so DefinitelyTyped community has created their @types/react-textarea-autosize. However, recently published react-textarea-autosize@8 has been rewritten to TS and naturally it ships its own type definitions now.

Problem is that CodeSandbox is still using @types/react-textarea-autosize over the builtin types, even though they have not been installed explicitly:


Link to sandbox: https://codesandbox.io/s/react-typescript-playground-0do5g?file=/src/index.tsx

Your Environment
Software Name/Version 
Сodesandbox latest (?) 
Browser latest Chrome 
Operating System OSX 


—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by Andarist** [comment]
No worries, it has been the first time I've stumbled upon this so it's probably not that big of a deal (but at the same time can be very annoying). 

Just remember that using sibling `.d.ts` files (`dist/foo.js`+`dist/foo.d.ts`) without providing additional `package.json` metadata like `"types"` field is a valid strategy for distributing types within a package.

**Comment by CodeSandboxNotifications** [comment]
Hello Mateusz,


We had a review of our typing resolver and we found a good hook to fix this, it is on my schedule for tomorrow. So there will be a fix for this soon :-)




Best regards
Christian



--- original message ---
On June 8, 2020, 11:56 AM GMT+2 notifications@github.com wrote:



No worries, it has been the first time I've stumbled upon this so it's probably not that big of a deal (but at the same time can be very annoying).

Just remember that using sibling .d.ts files (dist/foo.js+dist/foo.d.ts) without providing additional package.json metadata like "types" field is a valid strategy for distributing types within a package.

—

You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---
