### ISSUE TITLE
The editor focus just switch to the simulator(display) when I run this code in React.js 

### ISSUE THREAD

**Issue by ranjithpmankada** [codesandbox/codesandbox-client#4483]
# 🐛 bug report

### Link to sandbox: https://codesandbox.io/s/autumn-glitter-fzgrv?file=/src/Ref.js### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser  | Brave Browser |
| OS | Ubuntu Mate 20.04 |

**Comment by ranjithpmankada** [comment]
```
import React from "react";

export default class Ref extends React.Component {
  constructor(props) {
    super(props);
    this.inputRef = React.createRef();
    this.pRef = React.createRef();
  }
  componentDidMount() {
    this.inputRef.current.focus();
  }
  render() {
    return (
      <div>
        <input ref={this.inputRef} />
        <p ref={this.pRef} />
      </div>
    );
  }
}
```
This is the code. When I make changes to any code and the hot reloading changes the focus to the content in the display. It is difficult when you are working on the code.

**Comment by CodeSandboxNotifications** [comment]
Hi there Ranjith!


We are currently reviewing our whole hot reloading story and there will be coming some changes soon. We have already done a few changes to prepare for this.


1. We had a regression that caused turning off "Enable Live Preview" (From your preferences->preview) would cause any saved changes to reload the preview. Now it properly hot reloads
2. By hitting CMD + SHIFT + R you can reload the preview


So a more "relaxing" flow now is to trun off "Enable Live Preview" in your perferences. Then whenever you save it will hot reload. If you need to reload the preview you can hit CMD + SHIFT + R.


There are more things coming here, but this should improve your experience for now. 


Would love your feedback on comparing the recommended flow here VS the automatic hot reload your are experiencing now. Which one feels more natural to you?



--- original message ---
On June 28, 2020, 5:47 PM GMT+2 notifications@github.com wrote:



import React from "react";

export default class Ref extends React.Component {
constructor(props) {
super(props);
this.inputRef = React.createRef();
this.pRef = React.createRef();
}
componentDidMount() {
this.inputRef.current.focus();
}
render() {
return (
<div>
<input ref={this.inputRef} />
<p ref={this.pRef} />
</div>
);
}
}

This is the code. When I make changes to any code and the hot reloading changes the focus to the content in the display. It is difficult when you are working on the code.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---
