### ISSUE TITLE
Cant access user sandboxes after the latest UI update

### ISSUE THREAD

**Issue by NawarA** [codesandbox/codesandbox-client#4499]
# 🐛 bug report
When you launch the PWA, what now loads is a dialog that looks like this:
![image](https://user-images.githubusercontent.com/2067616/86296228-2738ed80-bbad-11ea-98a0-4c215878457c.png)

My intent is to reach my sandbox so I can keep coding.

This dialog presumes users only want to "Create Sandbox" "Explore Templates" or "Import Project". There is zero options to "quick access" my existing sandboxes.

This is a bug b/c users can no longer cancel out of the dialog. They're being forced to create a new sandbox, aka they cant exit the dialog and open a sandbox that exists.😆

## Description of the problem
A user who is opening the PWA in order to continue coding in an existing sandbox are stuck with a dialog they cannot exit out of.

The dialog presumes users only want to "create" as an action, yet the normal user journey is "resume" as an action. The dialog (which cannot be exited), has no options to quickly access a user's existing sandboxes. Thus users are stuck right now, unable to access their sandboxes, if they open the PWA.

## How has this issue affected you? What are you trying to accomplish?
To access my sandbox, I need to exit the PWA and open the site on Chrome and then navigate to my sandbox. The PWA feels broken, since you have to do weird things to try to exit the prompt.

Please make the prompt togglable or add a quick access that makes it easy to access existing sandboxes.

That should fix the open issue.
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 1010deccc |
| Browser          | Chrome 83 |
| Operating System |

**Comment by CodeSandboxNotifications** [comment]
Hey!


Can you confirm that when you install the PWA again you don't get the dashboard as the start page?



--- original message ---
On July 2, 2020, 12:23 AM GMT+2 notifications@github.com wrote:



🐛 bug report

When you launch the PWA, what now loads is a dialog that looks like this:


My intent is to reach my sandbox so I can keep coding.

This dialog presumes users only want to "Create Sandbox" "Explore Templates" or "Import Project". There is zero options to "quick access" my existing sandboxes.

This is a bug b/c users can no longer cancel out of the dialog. They're being forced to create a new sandbox, aka they cant exit the dialog and open a sandbox that exists.😆

Description of the problem

A user who is opening the PWA in order to continue coding in an existing sandbox are stuck with a dialog they cannot exit out of.

The dialog presumes users only want to "create" as an action, yet the normal user journey is "resume" as an action. The dialog (which cannot be exited), has no options to quickly access a user's existing sandboxes. Thus users are stuck right now, unable to access their sandboxes, if they open the PWA.

How has this issue affected you? What are you trying to accomplish?

To access my sandbox, I need to exit the PWA and open the site on Chrome and then navigate to my sandbox. The PWA is feels broken, since you have to do weird things to try to exit the prompt.

Please make the prompt togglable or add a quick access that makes it easy to access existing sandboxes.

That should fix the open issue.

Link to sandbox: link (optional)

Your Environment
Software Name/Version 
Сodesandbox 1010dec 
Browser Chrome 83 
Operating System 


—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by NawarA** [comment]
Currently when I open the PWA

![image](https://user-images.githubusercontent.com/2067616/87803628-9c403000-c807-11ea-844d-714705dfd67d.png)

After uninstalling and reinstall PWA...

![image](https://user-images.githubusercontent.com/2067616/87803798-da3d5400-c807-11ea-9de1-071f335a164e.png)


Looks like you're correct, reinstalling the PWA somehow affected the flow. Good catch! Rock on 🚀
