### ISSUE TITLE
Links with src="#target" do not trigger 'click' event

### ISSUE THREAD

**Issue by cyberbiont** [codesandbox/codesandbox-client#4523]
# 🐛 bug report

Just faced this very strange behaviour.

A link, which src attribute is set to '#void" or "#0" or something alike (that I usually do to disable links) does not trigger click event.
A link with src="#" does.

Sample sandbox:
https://codesandbox.io/s/void-event-listener-bug-udnit?file=/src/index.js

On Codepen the example works fine
https://codepen.io/cyberbiont/pen/PoZejJr?editors=1111

**Comment by oskarabc** [comment]
Hello @cyberbiont,
Not seeing errors here. Can you do a hard refresh, to upgrade to the latest version of CodeSandbox and confirm status of your issue?

**Comment by cyberbiont** [comment]
Status confirmed.
Do you get message in console when you click 'doesnt work' links in my example sandbox?

**Comment by CodeSandboxNotifications** [comment]
Hi,


I don't get messages in browser or CodeSandbox console upon clicking the links in https://codesandbox.io/s/void-event-listener-bug-udnit?file=/src/index.js


I've shared this with one of our devs. It's probably due to our runtime design choices that may differ from codepen.


–Oskar



--- original message ---
On July 25, 2020, 1:27 PM GMT+2 notifications@github.com wrote:



Status confirmed.

Do you get message in console when you click 'doesnt work' links in my example sandbox?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by christianalfoni** [comment]
Hi there @cyberbiont and so sorry for late response!

This does seem like a bug and we have a pending PR here: https://github.com/codesandbox/codesandbox-client/pull/4809

Thanks for the examples!
