### ISSUE TITLE
Svelte + material design

### ISSUE THREAD

**Issue by KCErb** [codesandbox/codesandbox-client#4550]
I was trying to use material design with Svelte and found a few examples but they are all broken. The error in the console indicates a svelte issue but they think it's an issue with your software/process:

https://github.com/sveltejs/svelte/issues/5145

I have code running locally that works perfectly and I uploaded it with the CLI tool:
https://codesandbox.io/s/intelligent-kapitsa-ilog1?file=/package.json

You can see there that the button is default, gray, flat. Also the icon is not showing. If you clone that locally you'll see a purple material button with a thumbs up symbol. It 'ripples' when it's clicked etc.

**Comment by KCErb** [comment]
I'll just point out that the starter svelte template shows the same error in the console: https://codesandbox.io/s/romantic-bassi-ncq2v?file=/rollup.config.js

**Comment by CodeSandboxNotifications** [comment]
Hey!




We currently do not transpile the (s)css files and that's why there are some problems when using the material-ui library. We only support inline style in the .svelte file


I will work on this and add this support so that the transpiler can work better


For now, it works when using the same technique as the online svelte repl: https://codesandbox.io/s/dreamy-darkness-4un65?file=/App.svelte​


Here is the issue where someone asked about it in the repo: https://github.com/hperrin/svelte-material-ui/issues/28




You may also close the issue opened in their repo as this on us to improve the compiler



--- original message ---
On July 15, 2020, 3:41 AM GMT+2 notifications@github.com wrote:



I'll just point out that the starter svelte template shows the same error in the console: https://codesandbox.io/s/romantic-bassi-ncq2v?file=/rollup.config.js

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by KCErb** [comment]
Whoops, looks like I missed my chance to comment and keep this alive.

I haven't had a chance to check if this is fixed though...
