### ISSUE TITLE
Cursor Position jumps to new line, is out of sync with keystroke, lags the true position of typing.

### ISSUE THREAD

**Issue by ya332** [codesandbox/codesandbox-client#4577]
# 🐛 bug report
Cursor forcefully jumps to new line even before the end of the line even though there is text on that line. 
Cursor position lags the starting position of keystrokes when near the end of line. The cursor lags about 5 characters on the screen from the position of the newly appeared characters when you type. 

## Description of the problem
If the cursor is at position X in my screen, when I start type it jumps to a new line. This happens only when I am near the end of the line. It seems like area where you can type is not the same size as the editor size. The cursor also lags about 5 characters on the screen from the position of the newly appeared characters when you type. But this happens only near the end of the line.
## How has this issue affected you? What are you trying to accomplish?
Can not type/edit properly.
### Link to sandbox: [link]() (optional)
https://codesandbox.io/embed/competent-pine-qxluj?fontsize=14&hidenavigation=1&theme=dark
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Couldn't find it.
| Browser          | Chrome Latest
| Operating System | windows 10

**Comment by christianalfoni** [comment]
Hi there @ya332,

This sounds very strange. Could you let us know exact Chrome version you are using? And on what site you open the embed? We are not able to reproduce it here. It might be related to a bug on your Chrome version on Windows 10, or the site the embed is included somehow affects this behaviour.

**Comment by ya332** [comment]
I am using Version 83.0.4103.116 (Official Build) (64-bit). I am using the link that I have posted. If you go to the link, do you experience any of the problems that I have mentioned?

**Comment by CodeSandboxNotifications** [comment]
Hi again and thanks for the info!


Yeah, that is the weird thing, no experiencing the behaviour you describe here. But I am sitting on a Mac, version 84.


But are you using this link directly or from within an other page? The only thing I can think of is that VSCode does "measure" your font. Could you use the element selector and select some code in the editor and take a look at the CSS inspector? Look at which font is active?




Best regards
Christian



--- original message ---
On August 1, 2020, 6:45 AM GMT+2 notifications@github.com wrote:



I am using Version 83.0.4103.116 (Official Build) (64-bit). I am using the link that I have posted. If you go to the link, do you experience any of the problems that I have mentioned?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---
