### ISSUE TITLE
Editor context menu opens to the left

### ISSUE THREAD

**Issue by techboyg5** [codesandbox/codesandbox-client#4590]
The monaco editor context menu opens to the left instead of the right, which it is supposed to do.

**Comment by CodeSandboxNotifications** [comment]
Hi! 


I'm afraid I didn't understand what you mean, can you give me a screenshot to show what you mean


Thanks!



--- original message ---
On July 23, 2020, 3:03 AM GMT+2 notifications@github.com wrote:



The monaco editor context menu opens to the left instead of the right, which it is supposed to do.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by techboyg5** [comment]
![image](https://user-images.githubusercontent.com/63317676/88553289-ba1d4a00-cfea-11ea-8860-784d09be0a85.png)
The mouse cursor is not shown in the screenshot, but this context menu opens to the left when it is supposed to open to the right.

**Comment by siddharthkp** [comment]
Ah, I understand now. I'll look into it. 

Meanwhile, does this cause hinderance in using the menu? Example: Can't select options / hides the code in context, etc.

**Comment by techboyg5** [comment]
> 
> 
> Ah, I understand now. I'll look into it 👍
> 
> Meanwhile, does this cause hinderance in using the menu? Example: Can't select options / hides the code in context, etc.

No.

**Comment by siddharthkp** [comment]
Thanks, good to know!

**Comment by techboyg5** [comment]
Can we continue now?

**Comment by siddharthkp** [comment]
> Can we continue now?

@techboyg5, sorry what do you mean?

**Comment by SaraVieira** [comment]
Hey,

This expected behavior as the menu calculates the space it needs to open and it has more space to open to that side, if you slide or close the preview that will not happen anymore since now it has more space to the right.

We do this to prevent things from opening on top of the preview, it may seem like there is enough space but the calculation is done assuming hover states like in typescript or in an error where you get more info and it gets quite large.
