### ISSUE TITLE
Overlapping labels

### ISSUE THREAD

**Issue by andrasbacsai** [codesandbox/codesandbox-client#4595]
# 🐛 bug report

## Description of the problem
Opening `package.json` & searching for something makes 2 labels overlapping & cannot close the search bar.
![image](https://user-images.githubusercontent.com/5845193/88367242-98725780-cd8b-11ea-9913-35a469a0cb31.png)

## How has this issue affected you? What are you trying to accomplish?
It's not a big deal, but still. :smile: 

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 1ed71a491
| Browser          |  Chrome Version 83.0.4103.116 (Official Build) (64-bit)
| Operating System | Ubuntu 20.04 LTS (Focal Fossa)

**Comment by CodeSandboxNotifications** [comment]
Thanks for reporting Andras 



--- original message ---
On July 24, 2020, 8:59 AM GMT+2 notifications@github.com wrote:



🐛 bug report

Description of the problem

Opening package.json & searching for something makes 2 labels overlapping & cannot close the search bar.


How has this issue affected you? What are you trying to accomplish?

It's not a big deal, but still. 😄

Link to sandbox: all

Your Environment
Software Name/Version 
Сodesandbox 1ed71a4 
Browser Chrome Version 83.0.4103.116 (Official Build) (64-bit) 
Operating System Ubuntu 20.04 LTS (Focal Fossa) 


—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by andrasbacsai** [comment]
It is already solved. Closing.
