### ISSUE TITLE
Middle click seems to be broken everywhere?

### ISSUE THREAD

**Issue by NullVoxPopuli** [codesandbox/codesandbox-client#4668]
# 🐛 bug report

## Description of the problem

When I middle click a link (such as my profile image), I expect a new tab to open

## How has this issue affected you? What are you trying to accomplish?

It makes my use of codesandbox harder as this behavior breaks my expectations with the rest of the web.

### Link to sandbox: [link]() (optional)

n/a

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | caab652ef
| Browser          | FireFox
| Operating System | Windows

My hunch is that codesandbox maybe overuses buttons where things should be links instead? with links, this behavior is built in to the platform.

![image](https://user-images.githubusercontent.com/199018/89732319-f6ee3580-da1b-11ea-91ff-4c7a020be711.png)

**Comment by SaraVieira** [comment]
Hey!

In the case of that particular case, it is not a link because what happens when you hover or click is that you get a tooltip to view your profile
![CleanShot 2020-09-01 at 15 02 43](https://user-images.githubusercontent.com/1051509/91854558-33503280-ec64-11ea-98a8-00d7ffdef7b4.png)

In the case of another user when you click it follows them in the live session instead of going to their profile

I hope this makes sense

**Comment by NullVoxPopuli** [comment]
Shouldn't it semantically be a link tho?

Not supporting default browser behaviors seems broken, yeah?

**Comment by SaraVieira** [comment]
Not really because it doesn't link you anywhere, in any case, you stay on the same page

It runs a javascript function in both cases:

One of the cases just opens a tooltip and the other case focuses your view on the user

None of these cases change the route, just run JS functions
