### ISSUE TITLE
Could not load the source sandbox for this GitHub sandbox, please refresh or report the issue.

### ISSUE THREAD

**Issue by IsaacGHoward** [codesandbox/codesandbox-client#4751]
# 🐛 bug report

## Description of the problem
My codesandbox project won't load, and the github section doesn't work
## How has this issue affected you? What are you trying to accomplish?
I can't work on my project further
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 0d15157e6 |
| Browser          | Chrome | 
| Operating System | Windows 10 |

**Comment by SaraVieira** [comment]
Hey!

Do you have a link to this sandbox?

**Comment by IsaacGHoward** [comment]
> Hey!
> 
> Do you have a link to this sandbox?

I can't really link to it as it's a private sandbox of mine

**Comment by SaraVieira** [comment]
Then I need some more info 

Do you have any errors in the console? Can you send some screenshots?

Anything would help

**Comment by IsaacGHoward** [comment]
![githubbroke](https://user-images.githubusercontent.com/14202682/93955942-c4677600-fd05-11ea-8ef7-422d6838fe70.PNG)
Sorry for the late response @SaraVieira but this is all it's giving me. Don't really know what to do about this. Maybe I should just create a new sandbox and set everything up again?

**Comment by SaraVieira** [comment]
Yeah, I can't really tell a lot from that

Is there a way you can open your developer tools and see if there is any errors there?

**Comment by guillaume-dorczynski** [comment]
Hello, I have the same kind of issue.

One thing I've noticed is that the "path" to this sandbox, that appears at the top center of the codesandbox editor, is wrong. What I mean is, I did change my Github username but codesandbox seems to use the old username.

For example, I created a sandbox with codesandbox editor, then exported it to github as "DecodeXY", it exported successfully to https://github.com/guillaume-dorczynski/DecodeXY, but when I reopen my sandbox in codesandbox editor I have the same error message as in the title of this issue, and the "link" is set to "Guillaume57/DecodeXY/master", where Guillaume57 is my old Github username. And in the Sandbox Info, the Template link is set to "Guillaume57/DecodeXY" and when I click this link it opens "https://codesandbox.io/s/github/Guillaume57/DecodeXY/tree/master/", which shows an error page "Something went wrong", because again it's using the old username.

Hope you can solve it because I'm stuck here, I can't push changes as the "Github" tab is empty like in @IsaacGHoward 's picture above.

**Comment by christianalfoni** [comment]
Hi there @guillaume-dorczynski ,

I have a feeling this is related to the way Github keeps a reference to your existing repos when you change your username. We most likely get some old information in the API when you try to open your repo with the new username.

This is very tricky for us to test and verify, and it seems like a pretty epic edge case 😄 

Would it be troublesome for you to move your project to a new repo on your Github account? I feel very confident that would solve it.

**Comment by guillaume-dorczynski** [comment]
Actually I solved it by deleting my sandbox then reimporting from github

**Comment by SaraVieira** [comment]
Since this seemed to be hiccup I will close this issue and feel free to reopen or ping me if it happens again
