### ISSUE TITLE
Add Ctrl-C and/or button for Container restart

### ISSUE THREAD

**Issue by karlhorky** [codesandbox/codesandbox-client#4920]
# 🌈 Feature

Changes to the `package.json` are not easily updated in the running application in a Container sandbox.

A solution that came to mind would be to add UI for container restart in the running server Terminal area in the bottom right - either or both of:

1. When the terminal is focused, respond to Ctrl-C by restarting the server
2. Show a small button to restart the running server

Why? It's not simple to see how to restart a Container sandbox - it is currently packed away in the Server Control panel (ref: https://github.com/shikijs/shiki/pull/82#issuecomment-686692670):

> Now, whenever you change the scripts in `packge.json`, you need to restart the sandbox with the "Restart Sandbox" button in the "Server Control Panel" side tab, so that we stop the running server and start the new one.

cc @lbogdan

**Comment by SaraVieira** [comment]
Hey Karl!

We are adding all feature requests that come in into our internal backlog so that+s easier for us to keep track and also adding the issue where it was mentioned to come back and let the person know.

This would be a super nice feature and we have added it in.

I will also be working on making our roadmap/backlog public but for now its a notion page

Thank you!

**Comment by karlhorky** [comment]
Ok, thanks for letting me know :)

**Comment by karlhorky** [comment]
I'll watch for any news about a public roadmap too - in case it would come into question, specific Notion pages can be made public without the whole workspace being public.

**Comment by SaraVieira** [comment]
I know but I wanna add a rating system so that people can login and vote on feature requests so I would rather do that :)

**Comment by karlhorky** [comment]
Oh, fancy!
