### ISSUE TITLE
Could not find module in path: 'readable-stream/errors' relative to '/node_modules/readable-stream/lib/internal/streams/state.js'

### ISSUE THREAD

**Issue by harryEth** [codesandbox/codesandbox-client#4957]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Could not find module in path: 'readable-stream/errors' relative to '/node_modules/readable-stream/lib/internal/streams/state.js'

![image](https://user-images.githubusercontent.com/33265609/94625897-bd44e880-026e-11eb-8895-d27fe666168b.png)

This error happens on 2 of my projects. This package should be a node js native package.
All projects works well on the local and built production environment. Just not working on the codesandbox.

Does anyone know how to fix this?

## How has this issue affected you? What are you trying to accomplish?

my project is blocked by this error.

### To Reproduce
Just go to the link below, it shows directly.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/github/MagicLabs/example-avalanche

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome Version 85.0.4183.102 (Official Build) (64-bit)
| Operating System | Mac OS Catalina version 10.15.3 (19D76)

**Comment by siddharthkp** [comment]
Hi Harry, I'm not aware of avalanche, so i'm not fully sure what's going on. But it seems to be a missing link between the packages `stream-browserify` and `readable-stream`

When I add `stream-browserify` as an explicit dependency to the sandbox, it works, here's the sandbox: https://codesandbox.io/s/repro-4957-qvpzw

I'm inclined to believe that this is an issue with the package itself, and not CodeSandbox but I could be wrong.

Let me know if the above sandbox helps and feel free to reach out to me if you have more context into the issue.

**Comment by CompuIves** [comment]
I went down a rabbit hole on this one. It turns out that for dependencies that specify two different versions for the same dependency we don't handle moving correctly. So in this scenario:

```
- a
  - b
    - c@1.0.0
  - d
    - c@2.0.0
```

We wouldn't include both versions of `c`, just the first version that we found. Which led to this bug. We always did handle it for these cases:

```
- a
  - b
    - c@1.0.0
- f
  - d
    - c@2.0.0
```

But not for the case where they originate from a single dependency. It should now be fixed though! The packager that handles this has been updated and for new dependencies everything should work as expected. It unfortunately only works for new packages though, due to our cache.

The solution of @siddharthkp works well, because with that change we actually end up in case 2, which we already work well with.

**Comment by siddharthkp** [comment]
We have a fix ✨ I tested the sandbox from your description, it's works

Thanks again for reporting this, it helped us find sneaky issues in our bundler. 

If you run into any other issues, feel free to reach out to us. Thanks!

**Comment by NickCarducci** [comment]
Yes @JamesACS , I put the edit last, appended, "now it works." But on Sept 17 I recall now my case is one of many potential with this error message and process
