### ISSUE TITLE
Can't delete template

### ISSUE THREAD

**Issue by m-thomson** [codesandbox/codesandbox-client#5026]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Attempting to delete a template results in error.

## How has this issue affected you? What are you trying to accomplish?

I'm trying to delete a template.

### To Reproduce

See screenshot.

### Link to sandbox: [link]() (optional)

N/A

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome/latest
| Operating System |

![CleanShot 2020-10-18 at 10 36 08@2x](https://user-images.githubusercontent.com/5273016/96375545-7c821600-112e-11eb-84d5-b5006ae434af.png)

**Comment by m-thomson** [comment]
Similarly, I can't make a sandbox into a template. See screenshot.  FYI, I tried clearing all caches and local storage and both problems persist.

<img width="1601" alt="CleanShot 2020-10-18 at 10 50 06@2x" src="https://user-images.githubusercontent.com/5273016/96375778-e0590e80-112f-11eb-80ba-4aa6ae627816.png">

**Comment by christianalfoni** [comment]
Hi @m-thomson ,

I am unable to reproduce this issue. Do you have a link to a sandbox causing this issue?

**Comment by sahil-sawant** [comment]
Hey @m-thomson !

I was having this same issue earlier today while trying to delete templates. I would click the 3 dot menu icon, select delete template, and the same "Could not delete custom template" error would slide in from the bottom of my screen. 

I came here to see if anyone had the same problem and find a fix. Seeing only this issue and no fix, I decided to search through my Codesandbox dashboard and figured out why this happens.

> Attempting to delete a template results in error.

In order to delete templates, you must make sure that you have no sandboxes which use the template in your recently deleted sandboxes. You can fix this by navigating to the "Recently Deleted" page in your dashboard. Next, permanently delete all the sandboxes that use the template you'd like to delete. After doing so, you'll notice that the template will disappear from your "Recently Used Templates" list. 

> Similarly, I can't make a sandbox into a template.

That aside, I'm not sure why you aren't able to create a template from a sandbox through the dashboard. I also was not able to create the template from clicking the 3 dot menu icon and selecting "Make Sandbox a Template". However, you can always convert a sandbox to a template by navigating to the sandbox info through the sandbox editor and then selecting the "Save as template" button. That worked for me.

**Comment by SaraVieira** [comment]
Hey

I know this is confusing but you can't delete templates from there since those templates are not yours and that's also why you can't make them into sandboxes, they are GitHub templates.

The issue is that we were not supposed to show that option since it will always return an error for lack of permissions

Currently, there is now way to delete them from that view only but that is a good feature we will work on :)

**Comment by arihantverma** [comment]
Hi @SaraVieira 

Even though I'm the owner of the github repository which was imported, I do not see a delete button in the fly out menu. Am I looking at the wrong place / understanding something wrongly?

![Screenshot 2021-01-26 at 8 55 10 PM](https://user-images.githubusercontent.com/43805922/105865293-c9706500-6018-11eb-8914-a5850367579b.png)

**Comment by SaraVieira** [comment]
Hey!

The fact that you own the GitHub repo doesn't change anything in our backend, we do connect the both since you can also login with Google so my answer still stands

You own the repo but not the template

**Comment by arihantverma** [comment]
@SaraVieira thank you for the super quick response! I meant being able to delete a github template. I checked the [docs](https://codesandbox.io/docs/templates) and couldn't figure it out. Is there no way to delete a template that I added through importing a github repository I own?

**Comment by SaraVieira** [comment]
Wait? It showed in chrome? And it worked?

If so it's a service worker not updating issue

**Comment by arihantverma** [comment]
Yes, it had showed in chrome, and had worked as well ( was able to delete the template ). But after clearing service worker and installing it again by loading codesandbox.io, and importing a github repo as template again, the option doesn't come on either chrome and safari. Which is intended as much I understood from your comments.

But wouldn't it make sense to be able to delete templates made out of one's own repository? Otherwise it'd keep getting added in the UI with no way to clean it up. This was my initial thought process. I'm sure I'm missing something.

**Comment by Aleksand-S** [comment]
Hi!
The same problem! I can't delete template from my GitHub Repo.
It's important for me to delete it... Help me please!

**Comment by Aleksand-S** [comment]
Hi!
The same problem! I can't delete template from my GitHub Repo.
It's important for me to delete it... Help me please!

**Comment by mitaosi** [comment]
> Hi! The same problem! I can't delete template based on my GitHub Repo. It's important for me to delete it... Help me please!

I have met exact same issue, super annoy, have you solved it, bro?

**Comment by nonoumasy** [comment]
also encountering this issue. I delete the github repo associated with the CSB template hoping it would solve the issue, but that didn't work either.

**Comment by HarshithMjh** [comment]
Hi @andrasbacsai , Even I am facing the same issue. Its super annoying to have so many Github templates in my account with no delete option. When user doesn't need these, I think its a waste of resource to the platform too. Is there any plan to add "Delete" option for these GitHub templates?

**Comment by JaimeGSandoval** [comment]
I'm just going to delete my account and make a new one or go to a different sandbox site. I can't believe there's no delete option for a template made from a forked repo.

**Comment by yuigoto** [comment]
Hi, and sorry for re-opening this issue, but I've got the same problem as above. I thought importing a repo into a sandbox wouldn't turn it into a template. I plan to have other templates, but not this one specifically, as it was for testing purposes.

So could this template be deleted, please? https://codesandbox.io/s/sveltekit-base-om0oe 

Thanks. :)

**Comment by andrasbacsai** [comment]
> Hi @andrasbacsai , Even I am facing the same issue. Its super annoying to have so many Github templates in my account with no delete option. When user doesn't need these, I think its a waste of resource to the platform too. Is there any plan to add "Delete" option for these GitHub templates?

We will talk about this internally! Thanks for the suggestion!


> Hi @andrasbacsai, and sorry for commenting this issue, but I've got the same problem as above. I thought importing a repo into a sandbox wouldn't turn it into a template. I plan to have other templates, but not this one specifically, as it was for testing purposes.
> 
> So could this template be deleted, please? https://codesandbox.io/s/sveltekit-base-om0oe
> 
> Thanks. :)

Sure. Deleted. :)

**Comment by AKiranB** [comment]
This is very frustrating. There should at least be a notification telling you that you can't delete the template after creating (I mean, who would expect this to be the case). 
I can't even rename the template.
Any suggestions?

**Comment by arnoldsandoval** [comment]
@andrasbacsai apologies to pile on here, but I too am having the same issue. I wish I had run in to this thread earlier and will be mindful going forward! Can you please remove these two:

- https://codesandbox.io/s/frontend-masters-xstate-react-5gfjw2
- https://codesandbox.io/s/frontend-masters-xstate-react-6kiqif

Thanks in advance!

**Comment by Naguib01** [comment]
Hello, I apologize for the inconvenience, I brought my project intentionally, can you delete it please it's really urgent.

- https://codesandbox.io/s/poster-app-iz0y3e

Thanks in advance !

**Comment by newac-it** [comment]
Hi @andrasbacsai, 
I'm not able to delete a template. Luckily found this thread. Can you pls delete this template?
[](https://codesandbox.io/s/test-quiz-7ndx0u)

Just in case there is an option available for users to delete templates, pls do mention.
Thanks!

**Comment by andrasbacsai** [comment]
@sannek, could you please take over these tasks from me?

@JamesACS FYI.
