### ISSUE TITLE
Vim copy buffer should use local storage

### ISSUE THREAD

**Issue by micheal-w-wells** [codesandbox/codesandbox-client#5103]
# 🌈 Feature

Stick vim yank contents into local storage

If i copy in one tab I should be able to paste in the other.

Use local storage.

**Comment by SaraVieira** [comment]
Hey

First of all please use the template to help us figure out what is wrong.

As for the issue, we do not have any control over VIM, we use the https://github.com/VSCodeVim/Vim extension that does not support that because it's an extension for VSCode.

Sorry for the issue but there is not a lot we can do here since we want to keep the extension up to date
