### ISSUE TITLE
502 bad gateway for GitHub import

### ISSUE THREAD

**Issue by rrjanbiah** [codesandbox/codesandbox-client#5129]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [ ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

There are 502 error reports. But, for this repo, there is no other error except lint warning. Was trying to check quick preview of the fork https://github.com/onepointWill/react-datasheet

## How has this issue affected you? What are you trying to accomplish?

Thought of escalating as never faced such issue before personally

### To Reproduce

https://codesandbox.io/s/github/onepointWill/react-datasheet

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Browser          | Chrome
| Operating System | Ubuntu

**Comment by SaraVieira** [comment]
Hey

You are running into this issue because the repo you are pointing to does not have any start or dev script so Codesandbox just builds the package but has nothing to show so you get a 502.

Can you explain what you were trying to see in the repo? Because it doesn't seem to have any examples, it's the source code of the library itself

**Comment by rrjanbiah** [comment]
@SaraVieira Thanks for your quick reply. Apologies for the delay due to Diwali.

You may be right. Examples are in another folder and that might be the reason. Though that doesn't build either https://codesandbox.io/s/github/onepointWill/react-datasheet/tree/master/docs/src/

**Comment by SaraVieira** [comment]
Interesting, this one seems to happen because the folder does not have a package.json and when that happens we default to static and you cannot install dependencies and also because the lib folder is not the actual folder but a link to it

**Comment by rrjanbiah** [comment]
@SaraVieira Thanks for your insights. If this is not an issue in codesandbox, do you think, this is worth for enhancement? If not, please close it.

I was just tying to quickly run a GitHub fork through codesandbox as it didn't have a demo link.

**Comment by SaraVieira** [comment]
I think it's mostly a matter of us not doing a good on teaching :/

Because in these cases you can switch the template and create a package.json using just the UI but we lack the docs and helpers to let people know and this is something I am working on, creating better docs on how to use our tool

I will close this for now but expect a good education platform for codesandbox soon :)
