### ISSUE TITLE
HTML Template Support: image sources

### ISSUE THREAD

**Issue by renenoel** [codesandbox/codesandbox-client#5156]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
I am trying to use [HTML templates](https://www.html5rocks.com/en/tutorials/webcomponents/template/) and when I use a template with an image inside it (without a specified source), I get an error: `Error: Cannot import an empty path`.

## How has this issue affected you? What are you trying to accomplish?
I am trying out using HTML templates within Codesandbox.

### To Reproduce
- Create an HTML page with an HTML template in the `HEAD` or `BODY`. Use a template with image without source -- i.e.
```
<template id="mytemplate">
  <img src="" alt="great image">
  <div class="comment"></div>
</template>
```
You should be able to observe the error `Error: Cannot import an empty path` in the console.

### Link to sandbox: [link]() (optional)
[https://codesandbox.io/s/upbeat-faraday-ye4hh?file=/index.html](https://codesandbox.io/s/upbeat-faraday-ye4hh?file=/index.html)
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome 86 & 88, Firefox 83, Safari Tech Preview 115 |
| Operating System | MacOS 10.15.7 |

**Comment by SaraVieira** [comment]
Hey!

I'm sorry but this not really something to fix because even though it's true it shouldn't break it also will not show anything and create malformed HTML in localhost using parcel.

If you want to test things like these I would suggest using the static template that does no bundling and will just give you an empty page in these cases: https://codesandbox.io/s/weathered-cdn-e9ppp?file=/index.html

In this template, we will simply print whatever you put on the editor without importing images and everything using javascript

If you need Parcel I tested it and you can add "/" to the inside of the image and it now works without a problem just showing nothing:
https://codesandbox.io/s/sad-dirac-zwjui?file=/index.html

Sorry for the issue but because we treat our issues list as the team's backlog, and therefore we close issues like these since they don't represent a task needing to be completed.
