### ISSUE TITLE
As a noob, I get throttled when I code inside a database snapshot onSnapshot() for instance

### ISSUE THREAD

**Issue by NickCarducci** [codesandbox/codesandbox-client#5164]
# 🌈 Feature

Discipline break UI

top right red bar

As a noob, I get throttled when I code inside a database snapshot onSnapshot() for instance.  When I do, can I get a progress bar of what is happening (or a pause button to code)

**Comment by SaraVieira** [comment]
Hey

Can you explain what you mean? If you don't want code to run automatically you can click on three dots on the top right and go to preferences and there is a preference to turn the auto run off

**Comment by SaraVieira** [comment]
You can also change that through our configuration ui

https://codesandbox.io/docs/configuration

**Comment by NickCarducci** [comment]
Great, I turned off (three dots)>Preview>PreviewOnEdit.  Sometimes when React doesn't catch an infinite loop in a function (I'm unsure exactly how this happens sometimes) the editor pauses & it feels like you might appropriately slow my window.  Or my browser does it. I don't know if your preview is done locally to me or you.

If it is your catch method, could we have a visual of how much you throttle (if you do..)?  I just propose the space in the top right a horizontal progress bar. So that I know how long to break or do something else.  If not, then there is basically nothing useful I've said - but I'm happy to know about that setting.  Thanks so much

**Comment by SaraVieira** [comment]
Hey!

Most of the times we cannot tell that, that's why we run the preview in a different domain, it's supposed to help in not crash between domains but doesn't always work.

We have another setting to prevent this kind of things if you want more of a run on click scenario: https://codesandbox.io/docs/faq#i-cant-edit-my-code-because-of-an-infinite-loop

I hope this helps and I will definitely add this to the docs to help improve the docs

Thank you for coming out of your way to make the issue

**Comment by NickCarducci** [comment]
If this ever happens, one might try and **rename the file *with the typo*** to force the error up in the tree (which also is not stalled by the... unkeyed loop inside `return`, `componentDidUpdate`, or *my error today thrown inside of a setInterval* I accidentally saved before catching all errors in `render`).
