### ISSUE TITLE
Codesandbox does not install dependencies with the specified range

### ISSUE THREAD

**Issue by djhi** [codesandbox/codesandbox-client#5199]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

We provide a link to a codesandox to our users so that they can give us a reproduction scenario of any reported issue.

## How has this issue affected you? What are you trying to accomplish?

This example has a package.json with a dependency to material-ui set to `^4.11.1` (notice the carret). However, codesandbox installs the latest alpha which is `5.0.0-alpha-17`. Due to this, the sample application fail to load.

### To Reproduce

Follow the link: https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Brave 1.17.73
| Operating System | PopOS 20.10

**Comment by lbogdan** [comment]
Hey @djhi ,

Where did you see we're installing `@material-ui/core@5.0.0-alpha-17`? That's not what I'm seeing inside the sandbox:
```
$ yarn why @material-ui/core
yarn why v1.22.4
[1/4] Why do we have the module "@material-ui/core"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@material-ui/core@4.11.1"
info Has been hoisted to "@material-ui/core"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "13.13MB"
info Disk size with unique dependencies: "19.29MB"
info Disk size with transitive dependencies: "27.31MB"
info Number of shared dependencies: 27
=> Found "react-admin#@material-ui/core@4.11.0"
info This module exists because "react-admin" depends on it.
info Disk size without dependencies: "11.72MB"
info Disk size with unique dependencies: "17.88MB"
info Disk size with transitive dependencies: "25.91MB"
info Number of shared dependencies: 27
```

**Comment by djhi** [comment]
Here's a screenshot of the dependencies tab:
![image](https://user-images.githubusercontent.com/1122076/100636500-134b1080-3332-11eb-8b17-2ac4c8316c0e.png)

When we start the codesandbox, we also have errors regarding duplicate `material-ui/styles` package which is due to this v5 being installed

**Comment by djhi** [comment]
Besides, if you manually select the latest version matching the specified range, everything works

**Comment by CompuIves** [comment]
Right, this is a mistake and a bug from our side in displaying the right version. Right now the sidebar doesn't show which version is installed correctly, because it's not basing it on the `yarn.lock` or `package-lock.json` that's in the sandbox if the sandbox is a container. In reality `@material-ui/core@4.11.1` is installed, but the sidebar is specifying that `15` is installed. 

This is something that we should fix really soon, as it can generate a lot of confusion. We probably should disable showing absolute versions for SSE sandboxes in the meantime, to prevent any confusion on it.

**Comment by lbogdan** [comment]
Oh, right, that's just an UI bug, for server sandboxes we don't actually show the version installed inside the container. As I've showed above, those are the versions installed inside the container you linked to.

An important thing to note here is that with server / container sandboxes we don't do anything special except running `yarn` (by default, if the sandbox doesn't have a `package-lock.json`, otherwise we use `npm`) to install packages and then run the main script of the sandbox, so it should work exactly as it would locally (minus the fact that if you import a subfolder of a monorepo you lose all context of the monorepo, which might be the issue here?).

**Comment by djhi** [comment]
I'm not sure it is. The application does not display anything unless I manually select the material-ui packages versions matching the one specified in the package.json.

**Comment by lbogdan** [comment]
OK, I'm gonna restart the sandbox and remove the persistent volume, so that packages will be installed from scratch.

**Comment by djhi** [comment]
Thanks a lot for the very fast answers! And for codesandbox btw, it's a game changer for maintainers :heart:

**Comment by lbogdan** [comment]
Now it's working. I think the main issue here is there's no package lock in the example folders, so unpredictable things happen whenever changing versions in their `package.json`.

**Comment by djhi** [comment]
Thanks a lot! Yes, that's one drawback of monorepos. I can confirm it works as expected now :+1:
