### ISSUE TITLE
Couldn't install rollup@2.34.1 package

### ISSUE THREAD

**Issue by jacobsun** [codesandbox/codesandbox-client#5228]
# 🐛 bug report

## Preflight Checklist

- [x ] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x ] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
JS project, the error:
```
 Error: Could not fetch dependencies, please try again in a couple seconds: Something went wrong while packaging the dependency rollup@2.34.1: Cannot find module 'fsevents/package.json' from '/tmp/2485614777/node_modules/rollup'
```
### To Reproduce

Create a new JS project, try to add the latest rollup package, the error occurs.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by SaraVieira** [comment]
Hey!

Roll-up is not going to work in client sandboxes because it needs fs and you don't have in the client ones.

I think a container like https://CodeSandbox.io/s/node may be better for what you are looking for 

You can change all the files bad package.json and it works like your local machine with a terminal 

You can read more about our container environment here 

https://codesandbox.io/docs/environment

**Comment by jacobsun** [comment]
Thanks for your clarify, it violent my instinct. Here is a project created by others, it did include the `rollup`, maybe the problem is from the new rollup version, thanks.
https://codesandbox.io/s/zim5s

**Comment by SaraVieira** [comment]
Yeah, seems version two just won't install. I will take a look but another way to go around this is also to open the package.json and move to dev deps since in a client sandbox we don't install them but when deploying they will be installed.

We don't have a UI for it because you can just paste it there

**Comment by jacobsun** [comment]
It works, didn't know the different mechanism between dev deps and deps. Thanks.

**Comment by SaraVieira** [comment]
Awesome! And thank you for the feedback! I will be working on some docs will be sure to add that 

Have a great weekend :)
