### ISSUE TITLE
NotSupportedError Failed to execute 'define' on 'CustomElementRegistry': the name "igc-template-content" has already been used with this registry - WebComponents

### ISSUE THREAD

**Issue by mddifilippo89** [codesandbox/codesandbox-client#5314]
## Description of the problem

NotSupportedError
Failed to execute 'define' on 'CustomElementRegistry': the name "igc-template-content" has already been used with this registry

## How has this issue affected you? What are you trying to accomplish?

Customer facing issue. A little background from our components, we explicitly do not re-register our modules if you ask us to reregister them a second time (which is what the issue is complaining about) but I think the issue is that codesandbox  appears to yank all of our modules and reload them, so because we don't shove something in the global state (we avoid polluting global state deliberately) we no longer know that we've already registered the modules.

As this doesn't happen in a normal app and even happen in other hot reloading implementations (for example webpack) so seems to be specific to how codesandbox implements the hot reload.

We could conceivably work around it by being a bit dirty and storing some global flags somewhere, or se other solution, but might be better to check if you just has a bug first.

Thanks. 

### To Reproduce

Access sample here:
[https://codesandbox.io/s/github/IgniteUI/igniteui-wc-examples/tree/master/samples/grids/data-grid/accessibility?file=/index.html](https://codesandbox.io/s/github/IgniteUI/igniteui-wc-examples/tree/master/samples/grids/data-grid/accessibility?file=/index.html)

Open index.html add a new line within <igc-data-grid>...</igc-data-grid>. Let the preview refresh. Issue arises.

**Comment by SaraVieira** [comment]
Hey!

I know we used to have this issue and had the idea it was still around but I can't seem to reproduce it with your sandbox?

Did you fix it on your side?

Thank you

**Comment by mddifilippo89** [comment]
Thanks for following up. 

The issue still happens with the sample above. All you have to do is open index.html and add a new line anywhere. 

Just click anywhere in the markup and press enter.

**Comment by SaraVieira** [comment]
Ohh, I see it. We seem to have some issues when it comes to double registering elements, there a couple of issues related to that in web components

Will take a look next week

Sorry for the confusion and the problem

**Comment by CompuIves** [comment]
Ah yep, our hot module reloading system reloads the `js` files if you change `index.html` (or any other `js`/`ts` file for that matter if they're in the dependency graph).

I thin there are three fixes we could do:

### Force manual reloads
This is the easiest short term solution until we've found a long-term solution. By enabling `Hard Reload on Change` in the `sandbox.config.json`, we will force to reload the full state when a change is made. It should still be relatively fast, because we do store the bundler cache in `IndexedDB`.


### Enable 'Hard Reload on Change' automatically
We should most probably also just enable this automatically when the bundler sees that we're working in a web components environment. 

### Add `module.hot` hooks
We can prevent the need to do a full reload if we add `module.hot.accept` hooks in the code that automatically unregisters the web component as soon as the file is changed. It would be faster, but this would add code to the sandbox itself.

So I think that option 1 is the easiest to circumvent this right now, and we can build option 2 in the short term. Option 3 is most ideal I think, as you'd get full HMR capabilities, but it's more involved in implementation on the user side.

**Comment by MattSidor** [comment]
I am still running into this issue, which makes it very difficult to use CodeSandbox with Custom Elements.

**Comment by JamesACS** [comment]
Hey @MattSidor - Have you tried following the sandbox.config.json  with “hard reload on change” suggested above? This should work!
