### ISSUE TITLE
It will be better if when I choose a react template I can operate with terminator.

### ISSUE THREAD

**Issue by iam-frankqiu** [codesandbox/codesandbox-client#5325]
# 🌈 Feature
Now. when I choose a react template. I can't use a terminator.  I can use terminator only when I create a server-side app. Sometimes. I create a react app with `react-scripts`. But what I want to do is `eject` all the Webpack configuration. It seems like I can't do that thing. So I pretty hope it can support one day. Thanks.

**Comment by SaraVieira** [comment]
Hey!

This is impossible for us to do in the client sandboxes, you can only do that with a container sandbox like you said since that one actually uses Node and webpack to build it.

Here is a template you can fork and bookmark that is a container CRA: https://codesandbox.io/s/react-container-template-5qiks

Here you can click to add a new tab on the terminal in this button:

![CleanShot 2021-01-06 at 16 04 11](https://user-images.githubusercontent.com/1051509/103783335-df51c200-5038-11eb-8505-5d2f4338580c.png)


And here you can just run `yarn eject` since it's a node environment you can do anything you want.


Unfortunately, our browser-based sandboxes do not run node or react scripts
