### ISSUE TITLE
Add Stencil JS Support

### ISSUE THREAD

**Issue by bernardodsanderson** [codesandbox/codesandbox-client#533]
It would be great to have Stencil support.

Repo: https://github.com/ionic-team/stencil

Getting started:
```
git clone https://github.com/ionic-team/stencil-starter.git my-app
cd my-app
git remote rm origin
npm install
```

**Comment by jimthedev** [comment]
Worth noting that [this](https://codesandbox.io/s/wo9j867ln7) seems not to work in codesandbox yet if you download and run it locally, it works! Not sure what is going on with the packaging but it seems like the same happens in stackblitz. Perhaps the stencil compiler isn't adding a package format that codesandbox is looking for?

**Comment by CompuIves** [comment]
Ah, that's interesting. It seems like the file mentioned on `main` of the `split-me` package.json only has this code:

```
// SplitMe: CommonJS Main
```

Url: https://unpkg.com/split-me@0.3.1/dist/index.js

I think that explains why it isn't a function, we prefer `main` over `module` since that's less transpiling work on our side.


Regarding Stencil support, I agree! That would be great to add!

This looks super interesting, so there is absolutely no build step? In that case maybe it makes sense to add a `static` template that just hosts the files so you can use them directly with Stencil. What do you think?

**Comment by jimthedev** [comment]
It depends who you are, if you are producing Stencil components then there is a build step. In order to consume them, you can do so without a build step.

From their site:

>
>
> Stencil is a compiler that generates Web Components (more specifically, Custom Elements). Stencil combines the best concepts of the most popular frameworks into a simple build-time tool.
>
> Stencil takes features such as
>
> - Virtual DOM
> - Async rendering (inspired by React Fiber)
> - Reactive data-binding
> - TypeScript
> - JSX
>
> and then generates standards-based Web Components with these features baked in.

So then producers of components like split-me have [a build step](https://github.com/alesgenova/split-me/blob/master/package.json#L13) that uses the stencil compiler.

**Comment by jimthedev** [comment]
Good catch on the main. That is kinda what I was thinking. IMO they should just not have the main field if they aren't going put anything in that bundle. Alternatively then they could bring in npm.im/esm and just point to the esm bundle if the commonjs is going to be empty. Either way it seems like it is something they would need to implement, no?
