### ISSUE TITLE
localStorage "SecurityError: Access is denied for this document" in Chrome

### ISSUE THREAD

**Issue by rafgraph** [codesandbox/codesandbox-client#5397]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Accessing `window.localStorage` results is a "SecurityError: Access is denied for this document" in Chrome v88 on Mac OS v11.1.
<img width="521" alt="Screen Shot 2021-01-24 at 11 23 15 AM" src="https://user-images.githubusercontent.com/11911299/105636525-cb7ace00-5e36-11eb-9d8e-7f5c42609500.png">

Note that I have confirmed it persists in an incognito window with all content blockers off, so it seems different than https://github.com/codesandbox/codesandbox-client/issues/5157.

Also note that this is only an issue with Chrome. In Safari, Firefox and Edge on Mac OS v11.1 this is not an issue.

## How has this issue affected you? What are you trying to accomplish?

I use the githubbox.com feature, and often the apps use `loacalStorage`, but now any app that tries to access `localStorage` fails to run in Chrome.

### To Reproduce

Open this sandbox in Chrome: https://codesandbox.io/s/blazing-sound-ozjf5?file=/src/App.js

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 6a844e4f7 |
| Browser          | Chrome v88 |
| Operating System | Mac OS v11.1 |

**Comment by SaraVieira** [comment]
![CleanShot 2021-01-25 at 20 39 28](https://user-images.githubusercontent.com/1051509/105756841-72ea2480-5f4d-11eb-81f4-d3ae0675d1ef.png)


Seems to work fine here, you may have third party cookies disabled and that may be what is causing it since codesandbox.io and csb.app are different domains.

That was the only way I could repdroduce

**Comment by rafgraph** [comment]
Thanks @SaraVieira, that's what's causing it. It would be nice to be able to use CodeSandbox with 3rd party cookies disabled (as most are for ad-tracking), but that would would require serving everything from the same domain (maybe something to consider?).

**Comment by SaraVieira** [comment]
We had that in the past and it caused a bunch of issues because a loop on your code would mean all of codesandbox would be stuck in a loop with no way out :(

Both solutions have their issues :(


Doing this on the settings works and I will add it to the docs 

![CleanShot 2021-01-26 at 12 32 42](https://user-images.githubusercontent.com/1051509/105840027-a327d680-5fd2-11eb-8c6d-2570e3966b61.png)

We should check if you have them blocked and send you there in case of an error
