### ISSUE TITLE
Simple React test failing.

### ISSUE THREAD

**Issue by kentcdodds** [codesandbox/codesandbox-client#5605]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Basic React tests are failing.

## How has this issue affected you? What are you trying to accomplish?

This demo is something I use in a talk: https://codesandbox.io/s/github/kentcdodds/confident-react-examples

### To Reproduce

Open the sandbox and notice all three tests are failing. They did not fail last time I pulled this up a year ago or so...

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 2d40f51ad
| Browser          | Tried several browsers
| Operating System | macOS

**Comment by andrasbacsai** [comment]
It's clearly something on our side, as locally it works.

**Comment by CompuIves** [comment]
I found the issue here, we're running the tests within the context of `jsdom`, because we don't want to influence the main html of the app itself. However, in this case a native event is dispatched to JSDOM, which it rejects because JSDOM only wants a JSDOM event.

This code:
```js
  const submitEvent = new Event('submit', {
    bubbles: true,
    cancelable: true,
  })
```

Works if we change it to:
```js
  const submitEvent = new window.Event('submit', {
    bubbles: true,
    cancelable: true,
  })
```

Because `window` is JSDOM, whereas not all globals are apparently mocked. We need to mock `Event` as well with the JSDOM version instead, but it would first be good to find out if we can mock all globals altogether with the JSDOM equivalent.

**Comment by kentcdodds** [comment]
Thanks! 👏
