### ISSUE TITLE
Docker-compose to run locallay

### ISSUE THREAD

**Issue by dustinlacewell** [codesandbox/codesandbox-client#5645]
Any possibility of a docker-compose setup to run the whole codesandbox shebang locally with relative ease?

**Comment by CodeSandboxTeam** [comment]
Hey,


You can only run the client locally. The whole codesandbox, like the server-side things, are not open-sourced.


Andras



--- original message ---
On April 9, 2021, 3:29 AM GMT+2 ***@***.*** wrote:



Any possibility of a docker-compose setup to run the whole codesandbox shebang locally with relative ease?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---
