### ISSUE TITLE
Resolved package versions is sometimes incorrect

### ISSUE THREAD

**Issue by clauderic** [codesandbox/codesandbox-client#5687]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Description of the problem

The package version resolution logic is incorrect. Root dependencies should be processed first to give them priority before processing transient dependencies.

Even though the version of `@dnd-kit/core` specified in the `package.json` is `^3.0.1`, the resolved version is `3.0.0`.

<img width="286" alt="Screen Shot 2021-04-20 at 11 37 18 PM" src="https://user-images.githubusercontent.com/1416436/115493242-60704600-a231-11eb-89d2-a38c9a71be00.png">

Logs of `manager.manifest`:

<img width="839" alt="Screen Shot 2021-04-20 at 11 36 58 PM" src="https://user-images.githubusercontent.com/1416436/115493340-8e558a80-a231-11eb-8173-dcf789eb3c6a.png">

It's getting that version from the dependencies of `@dnd-kit/sortable`, which has a dependency on `@dnd-kit` of `^3.0.0`, so even then, the resolved version should be `3.0.1`, not `3.0.0`.

<img width="849" alt="Screen Shot 2021-04-20 at 11 41 19 PM" src="https://user-images.githubusercontent.com/1416436/115493538-eee4c780-a231-11eb-8ebc-2d19f5a6d905.png">

### To Reproduce

https://codesandbox.io/s/test-dnd-kit-forked-zcczy?file=/src/App.js

cc @CompuIves

**Comment by CompuIves** [comment]
It looks like we're wrongly overwriting the root dependency (3.0.1) with a transient dependency (3.0.0), which means that it goes wrong in this place:

https://github.com/codesandbox/codesandbox-client/blob/master/packages/sandpack-core/src/npm/merge-dependency.ts#L143

I thought we had initially fixed this, but it looks like in this case it still goes wrong... @DeMoorJasper do you have time to look at this issue? I think this bug is exclusively in the function linked up here. The function is responsible for merging all different dependencies (with transient dependencies) into one big bundle, deduplicating as much as possible.

**Comment by clauderic** [comment]
Similar problem with this story https://codesandbox.io/s/dnd-kit-flex-wrap-layout-forked-4jvw7?file=/src/index.js

<img width="319" alt="Screen Shot 2021-04-21 at 9 44 16 AM" src="https://user-images.githubusercontent.com/1416436/115564156-372dd500-a286-11eb-9c94-81c74c71ccf9.png">

<img width="369" alt="Screen Shot 2021-04-21 at 9 44 38 AM" src="https://user-images.githubusercontent.com/1416436/115564177-3b59f280-a286-11eb-8a27-3b8500497d76.png">

In this case two versions of `@dnd-kit` are installed instead of being de-duplicated, which leads to the story not functioning properly because two versions are used in parallel
