### ISSUE TITLE
Embed disable edits unless opening sandbox

### ISSUE THREAD

**Issue by jpoehnelt** [codesandbox/codesandbox-client#5776]
# 🌈 Feature
Add a query param to completely hide the editor for embeds.

`hideeditor=1`

The editor doesn't work when embedding a sandbox based upon a GitHub repository and branch as it needs to be forked for edits.

**Comment by danilowoz** [comment]
Hey @jpoehnelt!

In the Embed screen, we have a couple of options for visualizing the embed, and these options aren't enough for your issue?
<img width="300" alt="Screenshot 2021-05-13 at 09 14 46" src="https://user-images.githubusercontent.com/4838076/118098333-abfab780-b3cb-11eb-8279-979204de01e1.png">

I'm trying to figure out the main issue here, like we still show the editor in an embed to endorse the user explorer the current codebase, even though they can't make any change there. So basically, the editor's main purpose is still there because we want to allow the user to see how the preview works.

An another solution for your issue could be sharing only the URL-preview instead of the embed:
<img width="231" alt="Screenshot 2021-05-13 at 09 18 18" src="https://user-images.githubusercontent.com/4838076/118098730-29262c80-b3cc-11eb-8c05-d5d27500fdb2.png">

In the following [sandbox](https://codesandbox.io/s/vanilla-ts), you could share the preview [URL](https://vanilla-ts.csb.app/), which only contains the preview and not the editor. Does it make sense?

**Comment by jpoehnelt** [comment]
A little more on my use case, I have hundreds of samples for which I am attempting to create embeds. These samples are **automatically** generated and placed in a branch of a repository. This automation rules out using the preview url. 

The primary issue is that a non-forked GitHub based sandbox( and by extension embed) is read-only. This leads to confusion when the user edits code and nothing happens.

The warning for this case is slightly more prominent when not in embed mode.

![Screenshot 2021-05-13 7 57 15 AM](https://user-images.githubusercontent.com/3392975/118136092-f75b9880-b3c0-11eb-825a-69f0ba19d201.png)

Each of the following options would work for my use case.

1. **prevent edits** - `hideeditor=1` or similar query param for embeds
2. **warn about edits** - a warning/popup to suggest forking when edit is not allowed without forking
3. **allow edits** - allow editing non-forked GitHub sandboxes??

**Comment by danilowoz** [comment]
Got it! Yeah, it makes sense, as we're not showing any warning in the editor, it's not clear enough when it's a read-only embed. So I have added your feature request to our internal backlog which we use to prioritize what to build next. We can't make any promises about the timing, but it's on the list!

Thanks
