### ISSUE TITLE
SharedArrayBuffer is not defined on Firefox

### ISSUE THREAD

**Issue by magicmatatjahu** [codesandbox/codesandbox-client#5780]
# 🐛 bug report

## Preflight Checklist

- [X] I have read the [Contributing Guidelines][contributing] for this project.
- [X] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.
      
I found one pull request related to my problem ([link](https://github.com/codesandbox/codesandbox-client/pull/4935))

## Description of the problem

I created simple codesandbox ([link](https://codesandbox.io/s/asyncapi-react-next-in-action-4en9x)). The problem is that if I open sandbox in Chrome everything works, problem is with Firefox and `SharedArrayBuffer is not defined` error:

![image](https://user-images.githubusercontent.com/20404945/118124625-23454100-b3f6-11eb-86ab-fe0eeb10d15f.png)

## How has this issue affected you? What are you trying to accomplish?

I wanna show usage of simple React component.

### To Reproduce

Open sandbox in Chrome and then in Firefox.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io  |
| Browser          | Google Chrome, version 90.0.4430.93 (Official Build) (64bit) and Firefox 84.0.2 (64bit)  |
| Operating System |  macOS Catalina 10.15.7  |

Thanks in advice with any helps!

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by magicmatatjahu** [comment]
EDIT: I also updated Firefox to the newest version `88.0.1` and it doesn't work, also in `incognito` mode.

**Comment by smhutch** [comment]
Hi @magicmatatjahu I had a look into this today and found that:

- SharedArrayBuffer was disabled by default in all major browsers in response to security issues. [Source](https://blog.mozilla.org/security/2018/01/03/mitigations-landing-new-class-timing-attack/).
- For it to work in FireFox, a few [headers need to be set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements).
- Although Chrome doesn't throw an error, please note that this might change soon, since [new restrictions are planned](https://blog.chromium.org/2021/02/restriction-on-sharedarraybuffers.html).

Since this seems to be a general browser issue, I'm going to close this for now. To get your sandbox running in all browsers, you may need to track down which library uses `SharedArrayBuffers`, and raise an issue with them about the things I highlighted above.
