### ISSUE TITLE
Testing FrontApp response

### ISSUE THREAD

**Issue by smhutch** [codesandbox/codesandbox-client#5794]
# 🐛 bug report

## Preflight Checklist

- [ ] I have read the [Contributing Guidelines][contributing] for this project.
- [ ] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [ ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |              |
| Operating System |              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by CodeSandboxTeam** [comment]
Thanks for reaching out!


We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.


Thanks for understanding and meeting us half way 



--- original message ---
On May 17, 2021, 5:21 PM GMT+1 ***@***.*** wrote:



🐛 bug report

Preflight Checklist

I have read the Contributing Guidelines for this project.

I agree to follow the Code of Conduct that this project

adheres to.

I have searched the issue tracker for an issue that matches the one I want

to file, without success.


Description of the problem

How has this issue affected you? What are you trying to accomplish?

To Reproduce

Link to sandbox: link (optional)

Your Environment
Software Name/Version 
Сodesandbox 
Browser 
Operating System 


—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---
