### ISSUE TITLE
team functionality or enterprise (self-hosted) offering?

### ISSUE THREAD

**Issue by knksmith57** [codesandbox/codesandbox-client#581]
Heya @CompuIves, really love the product. Thanks for putting together such a high quality tool!

I became a patron a few weeks ago to test drive the private sandbox functionality. The primary motivator was to enable hosting of sandboxes that may contain proprietary or sensitive code that I could hide from the public and easily share w/ coworkers.

The bummer I'm running into is the constant sharing and cataloging of the private links. AFAIK there's no way for me to add people I "trust" to view my private sandboxes.

Do you have any plans to offer team functionality? What about an "enterprise" license to self-host the stack?

Thanks!

**Comment by CompuIves** [comment]
Hey @knksmith57,

I think this is a really good question, something we'd definitely like to explore more. I have something interesting in the works that'll make CodeSandbox more interesting for companies. Nothing is set in stone yet though, so I think it's better to discuss this by email or via Skype first.

Could you send us an email to hello@codesandbox.io?

**Comment by canda** [comment]
Could you help me understand why would I need an enterprise license? The license included in the repo says it's free software. Do I have any restrictions if I want to host it myself inside our company?

**Comment by CompuIves** [comment]
Hey @canda,

The CodeSandbox client itself is distributed with the GNU GPLv3 license, which means that you can freely copy and distribute the client, as long as modifications are open sourced as well.

The CodeSandbox server is closed source currently, which means that self hosting is quite hard at this moment. We're still exploring options with regards to self hosting, which is why we haven't open sourced it yet. We also don't know how much demand there is for an on-premise solution, currently. That's why we encourage all companies interested to send us a message to hello@codesandbox.io, so we can discuss it 😄.

**Comment by NMinhNguyen** [comment]
Hey @CompuIves, I sent a message to hello@codesandbox.io, not sure if you've seen it, but I'd also like to discuss the possibility of self-hosting the CodeSandbox server :slightly_smiling_face:

**Comment by lperlaki** [comment]
Hello @CompuIves, are there any updates on Self hosting Codesandbox? I would like to introduce it at my school and it would be awesome if we could host it internal.

**Comment by prmichaelsen** [comment]
This is really interesting as a concept! I am keen to follow this closely!

**Comment by ebartz** [comment]
Please do not close. I am looking forward to such a feature :)

**Comment by NMinhNguyen** [comment]
Please don't close

**Comment by Weilbyte** [comment]
Please don't close

**Comment by andrasbacsai** [comment]
The initially requested functionality already exists. You can share public/private sandboxes with others by email/username. Also, there are lots of other team features implemented since then.

We currently don’t have an enterprise license, but we’re exploring it. So I would say that we’re working on it and that you can contact us to talk about it.
