### ISSUE TITLE
Import from GitHub is broken

### ISSUE THREAD

**Issue by jpoehnelt** [codesandbox/codesandbox-client#5954]
From the documentation, https://githubbox.com/reduxjs/redux/tree/master/examples/todomvc, should open a new sandbox based on this branch.

This also fails when using the format suggested by the import wizard: https://codesandbox.io/s/github/reduxjs/redux/tree/master/examples/todomvc

### Your Environment

Chrome, MacOS

**Comment by CodeSandboxTeam** [comment]
Hi Justin,


Is this still not working for you? Both those links show a correclty imported github sandbox for me, that you could fork to continue working on (github sandboxes themselves are immutable, so you need to fork before you can edit).


Kind regards,
Sanne



--- original message ---
On July 8, 2021, 10:57 PM GMT+2 ***@***.*** wrote:



From the documentation, https://githubbox.com/reduxjs/redux/tree/master/examples/todomvc, should open a new sandbox based on this branch.

This also fails when using the format suggested by the import wizard: https://codesandbox.io/s/github/reduxjs/redux/tree/master/examples/todomvc

Your Environment

Chrome, MacOS

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by jpoehnelt** [comment]
They are working today, sorry I don't have any more information to debug this. Closing for now.
