### ISSUE TITLE
Webpack project does not reload when updating files

### ISSUE THREAD

**Issue by tzachbon** [codesandbox/codesandbox-client#5992]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

We have a [template](https://codesandbox.io/s/create-stylable-app-3b1tc) that uses webpack for transpilers our code.
Everything looks nice but the issue is that we need to manually refresh to see the changes,
I'm not sure why the auto reload does not work.

## How has this issue affected you? What are you trying to accomplish?

This won't be the best UX for our users that needs this template

### To Reproduce

Just use the template and try to change any `tsx` file and see that it does not refresh by itself but you will need to do it manually

**Comment by lbogdan** [comment]
Hey @tzachbon ,

Thanks for your report!

Because of how auto-refresh (HMR) works in `webpack` and the fact that it expects the dev server to be accessed on `localhost:8080`, you need some additional `devServer` config in your `webpack.config.js`:

```js
{
  // ...
  devServer: {
    host: '0.0.0.0',
    sockPort: 443,
    disableHostCheck: true
  }
}
```

I forked your linked sandbox and made it work [here](https://codesandbox.io/s/hardcore-wave-yk1dx?file=/webpack.config.js:682-768).

Please let us know if this fixes your issue.

**Comment by tzachbon** [comment]
@lbogdan Thanks for the help

**Comment by lbogdan** [comment]
@tzachbon You're welcome! I'm assuming it worked, so I'm closing this.
