### ISSUE TITLE
Private sandboxes cannot fetch their own resources

### ISSUE THREAD

**Issue by zocky** [codesandbox/codesandbox-client#630]
Any files that are put into `/public` cannot be accessed if the sandbox is set to private.

E.g. creating a file called `/public/example.json` and then trying to load it with `fetch` will not work.

**Comment by SaraVieira** [comment]
hey!

Doing some issue revisiting. Can you send a sandbox where this happens and I will set it to private to test?

**Comment by lbogdan** [comment]
This is a limitation of private sandboxes, as we assume all sandbox contents is sensitive, and we deny any request trying to access it.

As an aside, instead of `fetch`ing a `.json` file, you can simply `require` it.

I'll leave this open, maybe we can find a way to allow access to a private sandbox's resources to its owner.
cc @CompuIves

**Comment by SaraVieira** [comment]
Closing as this is how it's supposed to work for security reasons
