### ISSUE TITLE
Add One Dark Pro theme

### ISSUE THREAD

**Issue by Binaryify** [codesandbox/codesandbox-client#6440]
# 🌈 Feature
## Add One Dark Pro theme
One Dark Pro is Atom's iconic One Dark theme, and one of the most installed themes for VS Code
Here is the repo https://github.com/Binaryify/OneDark-Pro

And here are the themes files
https://github.com/Binaryify/OneDark-Pro/tree/master/themes

here are the jsdelivr links of themes files
https://cdn.jsdelivr.net/gh/binaryify/OneDark-Pro/themes/OneDark-Pro.json
https://cdn.jsdelivr.net/gh/binaryify/OneDark-Pro/themes/OneDark-Pro-flat.json
https://cdn.jsdelivr.net/gh/binaryify/OneDark-Pro/themes/OneDark-Pro-darker.json

**Comment by CodeSandboxTeam** [comment]
Hey @binaryify ,


Thank you for this feature request - it's been added to our internal board. 



--- original message ---
On February 3, 2022, 4:26 AM GMT ***@***.*** wrote:



🌈 Feature

Add One Dark Pro theme

One Dark Pro is Atom's iconic One Dark theme, and one of the most installed themes for VS Code

Here is the repo https://github.com/Binaryify/OneDark-Pro

And here are the themes files

https://github.com/Binaryify/OneDark-Pro/tree/master/themes

—

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
--- end of original message ---

**Comment by Binaryify** [comment]
thx~

**Comment by JamesACS** [comment]
I'm afraid we haven't got any updates on this just yet @Binaryify
