### ISSUE TITLE
GitHub integrations show Bad Credentials. Also can't import Private nor public repo

### ISSUE THREAD

**Issue by MJDKhalil** [codesandbox/codesandbox-client#6556]
I upgraded to pro to import Private repo but I didn't manage so I searched for solution ; I did Revoke access from gitHub but now I can not import Private nor Public repos. I can't even create a repo from codesandbox (bad credentials). if I want to import I get error UNKNOWN_ERROR - 401 - Bad credentials.

Please help

**Comment by MJDKhalil** [comment]
Now, I can no longer signin to my codesandbox. when I press signin with GitHub I get this message 'Something went wrong'

**Comment by CodeSandboxTeam** [comment]
Hey @MJDKhalil


Sorry to hear that you're having trouble logging in. We can manually resolve any conflicts in our database, and make sure that you can sign in again. 



To make sure we can find all relevant accounts, can you please let us know any Github usernames and/or e-mail addresses you have used to create CodeSandbox accounts? If you recently changed your username or email-address on Github, please also let us know what they used to be, since this is usually where the problem comes from.


Once I have this information from you, we can find all conflicting accounts, and - with you - decide how best to merge them so you can log in again. 



Please make sure you email this information to ***@***.*** - do not post it in Github


Thanks,

—
James
Support
CodeSandbox.io

--- original message ---
On March 21, 2022, 8:59 AM GMT ***@***.*** wrote:



Now, I can no longer signin to my codesandbox. when I press signin with GitHub I get this message 'Something went wrong'

—

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
--- end of original message ---

**Comment by MJDKhalil** [comment]
Hi James,

Thanks for your reply.

I didn't change my username or email on GitHub but I tried to modify them on codesandbox. Here are my details ;

email ; ***@***.***
username; MJDKhalil<https://github.com/MJDKhalil>

Thanks,

Moammer,
________________________________

**Comment by MJDKhalil** [comment]
Hi James,

I emailed you the required details. I didn't change my username or email on GitHub.  

Thanks

**Comment by MJDKhalil** [comment]
Thanks James for your support.

I will share the solution as it may help somebody ;

Try disconnecting Github in the preferences and then reconnecting the account. That should refresh the credentials and get rid of anything that could be causing the problem

**Comment by MJDKhalil** [comment]
Thanks James for your support.

I will share the solution as it may help somebody ;

Try disconnecting Github in the preferences and then reconnecting the account. That should refresh the credentials and get rid of anything that could be causing the problem

**Comment by CodeSandboxTeam** [comment]
Hey Moammer, 


You need to make sure Github is linked in your CodeSandbox preferences, as well as being the way you log in (if you log in using Github). 


If Github is linked there, this will be something their support would be best placed to help you fix. 

—
James
Support
CodeSandbox.io

--- original message ---
On March 21, 2022, 10:32 AM GMT ***@***.*** wrote:


Hi James,

Thanks for your reply.

I didn't change my username or email on GitHub but I tried to modify them on codesandbox. Here are my details ;

email ; ***@***.***
username; MJDKhalil<https://github.com/MJDKhalil>

Thanks,

Moammer,
________________________________
