### ISSUE TITLE
Is there a way to deploy private code sandbox to Heroku?

### ISSUE THREAD

**Issue by kavink** [codesandbox/codesandbox-client#671]
Is it possible to deploy code sandbox server and UI on heroku for private teams? i.e. not use the code sandbox site ?

**Comment by CompuIves** [comment]
Not yet! But would certainly be good functionality to have. I'm wondering if Heroku has a kind of API for this?

**Comment by mikstur** [comment]
I haven't worked with the Heroku api in depth before, but I know they have this deploy now button. This could be a good starting point for a feature like this.

https://devcenter.heroku.com/articles/heroku-button

Is anybody working on something like this already?

**Comment by lbogdan** [comment]
I think what OP meant is running a private version of CodeSandbox in Heroku (not deploying a sandbox to Heroku). @kavink , can you please clarify?

**Comment by kavink** [comment]
Exactly what @lbogdan said do not want to deploy sandbox but is it possible to deploy private version of CodeSandbox or some basic instructions to create build pack /procfile etc to deploy private version CodeSandbox.

**Comment by CITGuru** [comment]
You should probably read this article if you want to deploy to heroku using my codesandbox fork. https://dev.to/oyetoket/how-i-deployed-codesandbox-apps-to-heroku-ndo

**Comment by CITGuru** [comment]
@CompuIves Heroku dont really have an API but we can use their deploy to button or build one that does it.

**Comment by jmorrell** [comment]
@CITGuru 👋 Heroku has a pretty extensive API: https://devcenter.heroku.com/articles/platform-api-reference 

Specifically I suspect that these docs would be helpful: https://devcenter.heroku.com/articles/build-and-release-using-the-api

This section shows how to deploy an application via uploading a tarball instead of deploying via git: https://devcenter.heroku.com/articles/build-and-release-using-the-api#sources-endpoint

A good bit of this is wrapped up in the [heroku-client](https://www.npmjs.com/package/heroku-client) npm module, which is used by the CLI.

Here is an example of some JS code that uses the API to: create an app, upload and build source, and execute a command on that dyno that might be helpful: https://gist.github.com/jmorrell/959e30d6f5ba5cdbb62a8557af03ff6d

@CITGuru Feel free to reach out to me on twitter or via email if you have any questions: jmorrell@heroku.com or [@jeremymorrell](https://twitter.com/JeremyMorrell)

**Comment by CITGuru** [comment]
Cool, I am checking it out @jmorrell

**Comment by kavink** [comment]
@SaraVieira sure paid version is fine too if it can be deployed to aws/ or some kubernetes cloud. Any timelines when paid product might be available ?

**Comment by SaraVieira** [comment]
The idea is that you get a on premise version. Not sure on the details if we deploy it or you deploy it but it will support all of that 

We are starting the work now but it's all still pretty coupled with the domain so it will be a while :/
