### ISSUE TITLE
Ant Design React library not working in Remix Template (nodejs based template) -- `larger than maximum allowed file size`

### ISSUE THREAD

**Issue by cliffordfajardo** [codesandbox/codesandbox-client#6786]
# 🐛 bug report

## Preflight Checklist
- [X] I have read the [Contributing Guidelines][contributing] for this project.
- [X] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
The Ant Design react component library  is not working inside of Remix template.
Worth noting is that Remix does server side rendering so when I load my Ant Design into my `.tsx` files the bundle size for the route appears to balloon.

![CleanShot 2022-07-16 at 15 15 08@2x](https://user-images.githubusercontent.com/6743796/179373493-76e3b2da-c2d0-49c8-9bbd-89b345e4f669.png)

Error message:
```
/public/build/_shared/chunk-SKUYH24L.js.map is larger than maximum allowed file size (1260191 > 524288), not synchronizing
```

## How has this issue affected you? What are you trying to accomplish?
This error occurred when I was creating a small Remix app that I wanted to share on Github to show a bug reproduction 🐛 
I imagine that this will continue to happen as more people start using Remix to create their code sandboxe's.

### To Reproduce
1. Visit this codesandbox: https://codesandbox.io/s/damp-currying-r1okqz?file=/app/routes/index.tsx
 - Codesandbox and stackblitz have different implementations, but I wanted to mention that this same code example does work on stackblitz (https://stackblitz.com/edit/node-6z19rg?file=package.json,app%2Froutes%2Findex.tsx)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |     codesandbox.io         |
| Browser          |      Google Chrome        |
| Operating System |      MacOS latest        |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by kettanaito** [comment]
Hey, @cliffordfajardo. Thanks for reaching out. 

That container warning you see shouldn't affect your application. It's related to some internal container synchronization logic. 

The issue seems to be related to CSB trying to synchronize files from the `build` folder (you can spot it from the path `/public/build/_shared/chunk-SKUYH24L.js.map`). You don't really want to sync build artifacts. 

To resolve this, try adding `build` to the root-level `.gitignore` file in your sandbox. I've tried that [in this fork](https://codesandbox.io/s/remix-ant-design-container-warning-5ui4vw). I don't seem to be getting that container warning anymore. 

Please let me know if that solves the issue. Thanks.

**Comment by cliffordfajardo** [comment]
Thanks @kettanaito !
I just noticed this template I forked didn't have a `.gitignore` - just added one ✅ 
I'll also reach out to the creator of this remix template to see if he can add a `.gitignore` to hopefully prevent this from happening to more folks 😄

**Comment by kettanaito** [comment]
Sounds like a good strategy! Thanks for making that template better.
