### ISSUE TITLE
cannot find module <package-name> or its corresponding type declarations errors

### ISSUE THREAD

**Issue by MananTank** [codesandbox/codesandbox-client#6801]
# 🐛 bug report

I've been getting "cannot find module <package-name> or its corresponding type declarations errors" on a lot of sandboxes from yesterday.

I know that these packages have proper types defined, they work locally just fine and even works fine on stackblitz.

( I know it takes a while to load the types in sandbox, but some errors just don't go away no matter how long you wait )

---

## Examples 1: React TypeScript Template

https://codesandbox.io/s/vibrant-curran-0hlop5?file=/src/index.tsx

![image](https://user-images.githubusercontent.com/22043396/180925568-1baa71a9-e7ac-4fad-97ef-4b210947b830.png)

<br/>

## Example 2: My Library/Framework

https://codesandbox.io/s/todos-indexed-list-qs5uj6?file=/src/index.tsx

![image](https://user-images.githubusercontent.com/22043396/180925876-fb7c1ac7-548d-4a92-95d7-f041ed60b727.png)

<br/>

### Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |  Chrome 103, Safari 15.5           |
| Operating System |       macOS 12.4 Monterey       |

**Comment by aj-foster** [comment]
Hi @MananTank!

In the first sandbox, it looks like the `@types` packages for `react` and `react-dom` are out-of-date. You're seeing this with `react-dom/client` because that particular module is new for React 18. Forking and fixing the version of those packages fixed it for me.

For the second sandbox, I can't explain it, but loading the sandbox a few times fixed the issue for me. That package definitely takes longer to load than normal.
