### ISSUE TITLE
【bug】Cannot find module '../components' or its corresponding type declarations when import tsx file in node_modules/lib

### ISSUE THREAD

**Issue by fantasticsoul** [codesandbox/codesandbox-client#6862]
<img width="474" alt="image" src="https://user-images.githubusercontent.com/7334950/187818334-4aff891c-612d-47a2-8f4a-08c873eee84f.png">

![image](https://user-images.githubusercontent.com/7334950/187818413-1c8febaf-122d-4c63-a412-90c66b5305c4.png)

**Comment by CodeSandboxTeam** [comment]
Hi,


Can you send a link to the sandbox? Otherwise it is hard for us to debug.


Thanks,
Sanne

—
CodeSandbox
***@***.***

--- original message ---
On September 1, 2022 at 4:20 AM GMT+2 ***@***.*** wrote:





—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
--- end of original message ---
