### ISSUE TITLE
TypeScript null check is off in embedded mode

### ISSUE THREAD

**Issue by alexvictoor** [codesandbox/codesandbox-client#708]
Hello
First thanks for your work on this wonderful tool.
When codesandbox is embedded in a iframe, TypeScript null checks seem disabled. For example if I have something like below:
```
  const myLambda = (input: string | null) => {
     return input.length;
  };
```
In the 'full screen' codesandbox I get a TypeScript warning (this is the expected behaviour) whereas there is no warning in embedded mode.

**Comment by CompuIves** [comment]
Hmm interesting, this is probably because I forgot to add the `tsconfig` as a value in the embed mode here: https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/embed/components/Content/index.js#L367-L377. In the app we do give the config here: https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/pages/Sandbox/Editor/Content/index.js#L433. I can fix this either this week or next week, or if someone is interested in taking up this issue it can be done sooner 😄
