### ISSUE TITLE
Download local dependency while Export to zip

### ISSUE THREAD

**Issue by gudipudipradeep** [codesandbox/codesandbox-client#7181]
Download local dependency while Export to zip. I am extended the existing codesandbox project. But while Export zip not exporting the local npm package. so we can get those. i spent lot of my time to do. but no option and my project in pending state.

Please can help me on download the local npm package or Export with full solution including packages.

![image](https://user-images.githubusercontent.com/8638634/203580361-191e4125-fdae-4d58-87c6-8ac2da4572e9.png)

**Comment by tristandubbeld** [comment]
Hi @gudipudipradeep! We cannot download the `node_modules` because of how the bundler works. If it were possible, it wouldn't be reliable and might not work on every platform. What exactly is the problem when downloading the `zip` and installing the packages manually? Thanks!

**Comment by gudipudipradeep** [comment]
Few of node_module implementation are not able get from the npm public repos. Due to old version or the owner might be stopped support for development for important. 

@modules are local to the project better have download.

**Comment by gudipudipradeep** [comment]
Especially attached module I can't able to get from npm repo while pulling. It is not available or some other reason. So it stopped to explore on it.

**Comment by tristandubbeld** [comment]
Hmm it seems that the package you're referring to is indeed [no longer available](https://rowsncolumns.app/). It might be possible to get the `node_modules` manually though.

When you open your sandbox in Chrome, you can go to the Sources tab in the browser devtools. In the page tab you will find various urls, one of which is the url of your sandbox preview (something like `xxxxxx.csb.app`, where `xxxxxx` is your sandbox id). In there, you can find the `node_modules` folder and you should be able to download these files manually. You can then add these to your project manually.

Please let us know if this works for you.

**Comment by gudipudipradeep** [comment]
all *.js file have import and exports got changed to some notation like below. can we do something bring as actuals @tristandubbeld 

`(function $csb$eval(require, module, exports, process, global, __dirname, __filename, $csbImport) {"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const Tabs_1 = __importDefault(require("./Tabs"));
exports.default = Tabs_1.default;
//# sourceMappingURL=index.js.map
//# sourceURL=https://8pfk3.csb.app/node_modules/@rowsncolumns/spreadsheet/dist/Tabs/index.js
})`

**Comment by tristandubbeld** [comment]
I'm afraid that isn't possible @gudipudipradeep. The `@rowsncolumns/spreadsheet` was probably compiled before being published to npm, hence the `dist` folder. If you want to make sure the package doesn't "disappear" I think you can create your own `@rowsncolumns/spreadsheet` folder in your project instead of installing it as an npm package and import from there. You'd have to download every file from the sources panel though, but there seem to be some tools for that.

However, since the package isn't published to npm anymore I guess there is a reason for that. Maybe there's a newer version available or there was a problem with the previous package. I'd recommend contacting the package author to figure out what happened to it, and maybe the code is still available somewhere. Hope this helps a bit!
