### ISSUE TITLE
unable to create repository from sandbox

### ISSUE THREAD

**Issue by h5gq3** [codesandbox/codesandbox-client#7222]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## How has this issue affected you? What are you trying to accomplish?

When trying to create a repository from sandbox, after configuring a unique name and setting privacy to public and hitting "Create Repository" button, the following error is shown:
 
<img width="947" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/31214990/206745787-45e2739f-43a4-4e4c-ab7a-c3983b714859.png">

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |    latest          |
| Browser          |      safari        |
| Operating System |      macos        |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by h5gq3** [comment]
also to note:
I had contents created at `/project/home/h5gq3` (other than default `/project/home/h5gq3/workspace`)
that were not persisted after ca ~1 day.
also the shell sessions were terminated

**Comment by h5gq3** [comment]
the [docs](https://codesandbox.io/docs/learn/repositories/env#persistence) note that everything in `/project` is persisted but this wasn't at first clear if this only applies to repositories or for cloud sandboxes too.
probably my fault for not grasping this separation between sandboxes and repositories being different things

**Comment by JayaKrishnaNamburu** [comment]
Hello @h5gq3 this issue is fixed now, Thanks for reporting this 😄. To see the new changes, you can visit you sandbox. And click the "Restart Sandbox" option. This will update codesandbox environment. And you will be able to convert your sandbox to repository.
Here is how, you can update the environment. The option is on the top left menu-bar. 
![Screenshot 2023-01-04 at 11 54 07 AM](https://user-images.githubusercontent.com/11075561/210540389-d607f4a1-0ab0-4154-9bf4-cda34248b4cd.png)

And after updating you can check the version of pitcher will be `0.219.3` or higher.
![Screenshot 2023-01-04 at 11 53 58 AM](https://user-images.githubusercontent.com/11075561/210540383-2cec5ec9-8a0a-47b9-8991-256e5a212f6b.png)

**Comment by JayaKrishnaNamburu** [comment]
Closing this, please let us know if this happens again 👍
