### ISSUE TITLE
Example Domain Issue.

### ISSUE THREAD

**Issue by braden697** [codesandbox/codesandbox-client#8079]
# 🐛 bug report

Hi, so I'm trying to generate some new AI generations but somehow it only goes to Example Domain pages. I don't know how to make my AI generators work.

**Comment by CompuIves** [comment]
What do you mean with example domain pages?

**Comment by braden697** [comment]
Well looks like it is gone now, but now I cannot figure out how to play my custom AI Generator video. I made a custom AI Generator but the thing is, the text-to-video generated video is not playing the video. May I share the issue with you so you can look at it?

**Comment by braden697** [comment]
This is what happens when I try to show my generate my art, video, etc.
![AI Issue](https://github.com/codesandbox/codesandbox-client/assets/97651892/97bf046f-ca87-4bd8-a658-2297bc2e0a6a)

**Comment by CompuIves** [comment]
Ah, `example.com` is a website that's often used by generators, but that website owned by someone else. You will need to replace `example.com` URLs to the ones that you own, they only act as a placeholder in the generated code. I will close this issue for now, because it's out of scope for CodeSandbox. Feel free to reopen if you see something that CodeSandbox can do here!
