### ISSUE TITLE
Import repository UI

### ISSUE THREAD

**Issue by RexRowan** [codesandbox/codesandbox-client#8205]
# 🐛 bug report

## Preflight Checklist

- [x ] I have read the [Contributing Guidelines][contributing] for this project.
- [x ] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

The UI does not display the full repo list through scrolling.

## How has this issue affected you? What are you trying to accomplish?

Nothing. I can use URL

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |              |
| Operating System |              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hello @RexRowan 

Could you please clarify what you mean? The Dependency search will only list the most relevant packages to your input. Otherwise it would quickly become extremely difficult to find what you actually needed if you searched for example 'react', which as of this moment returns over 6000 different packages on the NPM sites native search. 

You'll be able to find packages you need by making the search term more specific

**Comment by RexRowan** [comment]
understood
