### ISSUE TITLE
Codesandbox editor freezing on load

### ISSUE THREAD

**Issue by rogama25** [codesandbox/codesandbox-client#8230]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
The editor crashes just after loading, sometimes freezing and sometimes I get a SIGILL error. It seems to only happen after updating to the latest version. Clearing browser's cache resolves the problem for a while. Tried both with extensions and disabling them all
![image](https://github.com/codesandbox/codesandbox-client/assets/11318350/58291765-1749-463b-9bb5-9ced5ea02074)

## How has this issue affected you? What are you trying to accomplish?
I can't load any sandbox in codesandbox

### To Reproduce
1. Load a sandbox (it loads fine)
2. Update to the latest version clicking the yellow indicator at the top-left
3. Restart the browser
4. Load a codesandbox editor

### Link to sandbox: [link](https://codesandbox.io/p/sandbox/b22b7) (optional)
It seems to affect any sandbox, tho

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | (can't get info) |
| Browser          | Chrome 120.0.6099.109 64-bit |
| Operating System | Ubuntu 23.04 X11 |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by CompuIves** [comment]
Hey! Thanks for this report, we're looking into it right now. Could you share what the network tab is showing when you get this error? We're curious which network request is failing and why.

**Comment by christianalfoni** [comment]
So just wanted to mention we have done some improvements.

- We have removed a dependency that caused us to install almost 900 SVG files during the install of new editor version
- We have moved the precaching of next version to happen after the editor loads, instead of during its load

You will not really see the effect of this AFTER updating to the new version. So if it still fails on the next update that would be expected. Please keep in touch with us so we can verify together when we do deploy the next version where these changes would start to take effect for you 😄

**Comment by rogama25** [comment]
Thanks for the work! For now it seems to be working fine on Firefox, I'll be looking forward to hearing from you

**Comment by christianalfoni** [comment]
Hi again @rogama25!

I was wondering how your experience has been updating to the latest versions since last time? There should at least have been a couple of new versions since you last updated to the hopefully fixed version 😄 

We have also made some additional strides to make it more clear when new versions are available related to any errors that could appear.

We are also planning to implement a "refresh" endpoint which will automatically clear out the service worker and bring you to the latest version. Though hopefully that will not be a common thing to be used 😄

**Comment by rogama25** [comment]
Hey! So I've tried again to use codesandbox on Chrome and the problem seems to be fixed for me, so I'll close the issue. Thanks again for the hard work
