### ISSUE TITLE
Wasm mime type

### ISSUE THREAD

**Issue by salzhrani** [codesandbox/codesandbox-client#948]
# 🐛 bug report

## Description of the problem
.wasm files need to be served with mime-type `application/wasm` in order for it to work

## How has this issue affected you? What are you trying to accomplish?
run a wasm module.

### Your Environment

Browser : google chrome
Operating System: mac os

**Comment by SaraVieira** [comment]
Issue closed due to lack of activity

**Comment by hexrcs** [comment]
Can this be reopened? :)

It seems that CodeSandbox currently serves WASM binaries as `application/octet-stream` instead of `application/wasm`. This should probably be fixed from the serverside instead of the client.

![Screen Shot 2020-03-14 at 15 05 02](https://user-images.githubusercontent.com/26751752/76683740-b920e880-6606-11ea-9560-858a05af55e3.png)

Looks like it's probably because `express` is not up-to-date - `4.17` seems to have the fix ([related issue](https://github.com/webpack/webpack-dev-server/issues/1575)). Not sure if this repo contains related code, but `standalone-packages/codesandbox-browserfs` has version `4.15.4` https://github.com/codesandbox/codesandbox-client/blob/13c9eda9bfaa38dec6a1699e31233bee388857bc/standalone-packages/codesandbox-browserfs/yarn.lock#L1443

**Comment by SaraVieira** [comment]
Hey!

Reopened and let me ping @compuives

**Comment by lbogdan** [comment]
Binary files are actually served from a Google Cloud Storage bucket, and GCS doesn't have a custom MIME type for `.wasm` files, so it falls back to the default `application/octet-stream`. The solution is to explicitly set the `Content-Type: application/wasm` header for `.wasm` files when we upload them to GCS. This might also happen for other "exotic" file types.

Cc @CompuIves

**Comment by lbogdan** [comment]
@hexrcs In the meanwhile, I manually set the proper content type for `https://uploads.codesandbox.io/uploads/user/5b0619d8-6846-415b-b3f2-5f62a6b67a40/eRQ5-main.wasm`, can you confirm it's now working?

**Comment by hexrcs** [comment]
@lbogdan Yes it is :)

**Comment by n0x3u5** [comment]
Hi!

I seem to be stuck on the same issue here. I still seem to be receiving an incorrect MIME type for WASM files in my Sandboxes.

Is there some way for me to set the proper content type manually like @lbogdan has done? I don't think https://uploads.codesandbox.io/ is meant to be accessed by me.

cc @SaraVieira @CompuIves

**Comment by CompuIves** [comment]
Oh yeah you're right! The server probably doesn't upload this file with the right mime types to the bucket, do you have time to double check this @sannek ?

**Comment by pjoe** [comment]
What about `.wasm` files from npm packages? Not working for me, see e.g. https://codesandbox.io/s/friendly-yonath-is9ut

**Comment by sannek** [comment]
We've just (finally) deployed a fix for this, and `.wasm` files should now have the proper content types! Let me know if you encounter any further issues.

**Comment by leoplaw** [comment]
wasm streaming compile failed: TypeError: WebAssembly: Response has unsupported MIME type 'text/html' expected 'application/wasm' 

Error from this sandbox
https://d2mcgn.csb.app/
