### ISSUE TITLE
support for Angular 6 ?

### ISSUE THREAD

**Issue by arangates** [codesandbox/codesandbox-client#984]
# 🌈 Feature

support for angular 6  github repositories

import angular 6 cli generated projects from github directly

Eg repo: https://github.com/arangates/junicorn

**Comment by lbogdan** [comment]
Hey @arangates ,

Since the introduction of [server sandboxes](https://medium.com/@compuives/codesandbox-containers-out-of-beta-improvements-be79679df4cc) it's possible to run virtually anything you'd run in a local environment. You can see an Angular starter here https://codesandbox.io/s/github/lbogdan/cs-angular-starter , I tried doing that with your repo, too, but it has more than 250 files, which is out current file limit for github imported repositories. We're also gonna add an Angular server template pretty soon, too!

If that answers your question, please help us keep the issue count low! 🙂

**Comment by SaraVieira** [comment]
Issue closed as answer was provided.

Please reopen if you have any issue with the container :)

**Comment by mohammedzamakhan** [comment]
@SaraVieira The answer is about server sandboxes by @lbogdan. But we want latest Angular CLI template when we open from the home page, as most of the users would be trying that, not by using server sandboxes!

Please open this issue back
